"""Stub responder self-tests (KIT_SPEC 4.17, 11.3, 12.4 acceptance: stubs produce contract-valid output for every
contract type and every template kind listed in 6.12). Owner: B4."""

import itertools
import json
import os
import re
import sys
import tempfile
import time
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "harness"))
import paths  # noqa: E402

from ublib import stubs, validate  # noqa: E402

SCHEMAS = os.path.join(paths.FIX_E2E, "schemas")
CRITERIA = ["Value", "Feasibility", "Fit", "Distinctiveness", "Evidence"]
AXES = {"Moment": ["planning", "handover", "night shift"], "Channel": ["mobile", "desk", "paper"]}
ALIAS_RX = re.compile(r"\b(S\d+|G\d+|R\d+|L\d+|H|HP|H2|IMP|S1R)-\d+\b")
LABEL_WORDS = re.compile(r"(?i)origin:|strategy:|generated by")
PLACEHOLDER_RX = re.compile(r"TODO|TBD|XXX|lorem|\{\{|<[a-z][a-z0-9 _-]{1,40}>")

CHECK_FINAL = r"^VERDICT: (CROWDED|ADJACENT|NOT LOCATED|NOT CHECKED); DIFFERENTIATOR: .+$"
REVIEW_FINAL = r"^VERDICT: (BACK IF .+|BACK|DON'T BACK); confidence (0(\.\d+)?|1(\.0+)?)$"
ARCH_HEADINGS = ["## 1 Paradigm", "## 2 Container view", "## 3 Stack", "## 4 Quality mechanisms", "## 5 Data",
                 "## 6 Deployment and operations", "## 7 Security and privacy", "## 8 Cost", "## 9 Trade-offs",
                 "## 10 Risks", "## 11 Rejected approaches", "## 12 Innovation tokens"]
CARD_LINES = ["Title:", "Problem:", "Mechanism:", "For whom:", "First version:", "Main risk:", "Prior art:"]
SECTION_HEADS = {n: h for n, h in stubs._PROPOSAL_HEADINGS.items()}


def schema(name):
    return os.path.join(SCHEMAS, name + ".schema.json")


def sec_files(nums):
    return ["sections/%02d.md" % n for n in nums]


def per_sections(nums, approach=False):
    out = {}
    for n in nums:
        h = "## 6. Approach" if (n == 6 and approach) else SECTION_HEADS[n]
        out["sections/%02d.md" % n] = {"headings": [h]}
    return out


PACKAGE_FACTS = {"containers": [{"id": "C-1", "name": "Web app", "tech": "TypeScript"},
                                {"id": "C-2", "name": "API", "tech": "Python"},
                                {"id": "C-3", "name": "Database", "tech": "PostgreSQL"}],
                 "qg_ids": ["QG1", "QG2", "QG3"], "ext_ids": ["EXT-1", "EXT-2"], "r_ids": ["R-001", "R-002"]}
PROPOSAL_FACTS = {"sections": [SECTION_HEADS[n] for n in range(1, 14)], "adr_numbers": [1, 2],
                  "r_ids": ["R-001", "R-002"], "source_ids": ["S-001"]}

# (template, kind, contract, stub facts) for every template in 6.12
CASES = [
    ("PING", "ping", {"type": "text", "regex": "PONG"}, None),
    ("FRAME-QUESTIONS", "frame", {"type": "json", "schema": schema("frame-questions")}, None),
    ("FRAME-FINAL", "frame", {"type": "files", "required": ["01_FRAME.md", "criteria.json"],
                              "allowed": ["01_FRAME.md", "criteria.json", "CONTEXT.proposed.md"],
                              "status_trailer": True}, None),
    ("FRAME-DRAFT", "frame", {"type": "files", "required": ["01_FRAME.md", "criteria.json"],
                              "allowed": ["01_FRAME.md", "criteria.json"], "status_trailer": True}, None),
    ("P-GROUND", "researcher", {"type": "sections", "headings": ["## A. FACTS", "## A2", "## B. LANDSCAPE",
                                                               "## C. SEARCH BOUNDARY"]}, None),
    ("S1F", "generator", {"type": "idea-blocks", "prefix": "S1", "min": 10}, {"axes": AXES}),
    ("S2-VS", "generator", {"type": "idea-blocks", "prefix": "S2", "min": 10}, {"axes": AXES}),
    ("S3-EDE", "generator", {"type": "idea-blocks", "prefix": "S3", "min": 30}, {"axes": AXES}),
    ("S4-TRANSFER", "generator", {"type": "idea-blocks", "prefix": "S4", "min": 10}, {"axes": AXES}),
    ("S5-OPS", "generator", {"type": "idea-blocks", "prefix": "S5", "min": 10}, None),
    ("S5-RESEARCH", "generator", {"type": "idea-blocks", "prefix": "S5", "min": 8}, {"axes": AXES}),
    ("GAP", "generator", {"type": "idea-blocks", "prefix": "G1", "min": 5}, {"axes": AXES}),
    ("REOPEN", "generator", {"type": "idea-blocks", "prefix": "R1", "min": 8}, {"axes": AXES}),
    ("LENS", "generator", {"type": "json", "schema": schema("lens")}, None),
    ("QUICK-GEN", "generator", {"type": "idea-blocks", "prefix": "Q", "min": 5}, {"axes": AXES}),
    ("CURATOR", "curator", {"type": "json", "schema": schema("merges")},
     {"aliases": ["S1-%02d" % i for i in range(1, 13)] + ["S3-%02d" % i for i in range(1, 13)] +
      ["HP-01", "H-01", "H-02"], "axes": AXES, "primary_aliases": ["HP-01"]}),
    ("QUICK-CURATE", "curator", {"type": "json", "schema": schema("quick-curated")}, None),
    ("SCREEN", "judge", {"type": "json", "schema": schema("screen"),
                         "cover": {"array": "scores", "key": "id", "ids": ["I-%03d" % i for i in range(1, 21)]}},
     None),
    ("CHECK", "checker", {"type": "sections", "headings": ["## 1", "## 2", "## 3", "## 4"],
                          "final_line": CHECK_FINAL}, {"idea_id": "I-004"}),
    ("EVOLVE", "generator", {"type": "idea-blocks", "prefix": "E", "min": 3}, None),
    ("EVOLVE-CONTRAST", "generator", {"type": "idea-blocks", "prefix": "E", "min": 2}, None),
    ("NORMALIZER", "normalizer", {"type": "cards", "ids": ["I-003", "I-010", "I-012"], "lines": CARD_LINES}, None),
    ("TOURNAMENT", "judge", {"type": "json", "schema": schema("verdicts"),
                             "cover": {"array": "verdicts", "key": "pair_id", "ids": ["P01", "P02", "P03"]}}, None),
    ("PRECOMMIT", "synthesis", {"type": "text", "min_chars": 200}, None),
    ("REVIEWER", "reviewer", {"type": "sections", "headings": ["## 1", "## 2", "## 3", "## 4", "## 5"],
                              "final_line": REVIEW_FINAL}, {"stance": "CRITIC", "idea_id": "I-003"}),
    ("REBUTTAL", "reviewer", {"type": "text", "min_chars": 80}, None),
    ("SYNTHESIS", "synthesis", {"type": "sections", "headings": ["## Verdicts", "## Summary"],
                                "final_line": r"^WHOLE-EFFORT: (CONTINUE|STOP)"}, None),
    ("PROBE", "writer", {"type": "sections", "headings": ["## Riskiest assumption", "## Probe", "## Kill criterion"],
                         "final_line": r"^RESULT: PENDING$"}, None),
    ("QUICK-PROBE", "writer", {"type": "json", "schema": schema("quick-probe")}, None),
    ("ARCH-DRIVERS", "arch-author", {"type": "json", "schema": schema("arch-drivers")}, None),
    ("ARCH-CANDIDATE", "arch-author", {"type": "sections", "headings": ARCH_HEADINGS,
                                       "json_tail": schema("arch-candidate")},
     {"qas_ids": ["QAS-01", "QAS-02"], "hc_ids": ["HC-1"]}),
    ("ARCH-JUDGE", "arch-judge", {"type": "json", "schema": schema("arch-judge"),
                                  "cover": {"array": "candidates", "key": "label", "ids": ["A", "B", "C"]}},
     {"labels": ["A", "B", "C"], "criteria": ["QG1", "QG2", "time_to_mvp", "team_fit"]}),
    ("ARCH-PREMORTEM", "reviewer", {"type": "sections", "headings": ["## Technical", "## Cost", "## Team",
                                                                     "## Vendor", "## Scale"]}, None),
    ("ARCH-PACKAGE-STRUCTURE", "writer",
     {"type": "files", "allowed": ["chosen/*.md", "chosen/api/*"],
      "required": ["chosen/containers.md", "chosen/runtime.md", "chosen/data-model.md", "chosen/api.md",
                   "chosen/api/openapi.yaml"],
      "per_file": {"chosen/containers.md": {"headings": ["## Containers", "## How each quality goal is met"],
                                            "mermaid": ["C4Container", "flowchart"]},
                   "chosen/runtime.md": {"mermaid": ["sequenceDiagram"]},
                   "chosen/data-model.md": {"headings": ["## Entities"], "mermaid": ["erDiagram"]}},
      "status_trailer": True}, PACKAGE_FACTS),
    ("ARCH-PACKAGE-CROSSCUT", "writer",
     {"type": "files", "allowed": ["chosen/*.md"],
      "required": ["chosen/deployment.md", "chosen/security-privacy.md", "chosen/cost-model.md",
                   "chosen/deferred.md"],
      "per_file": {"chosen/cost-model.md": {"headings": ["## Assumptions", "## Sensitivity"]}},
      "status_trailer": True}, PACKAGE_FACTS),
    ("ARCH-DECISIONS", "writer", {"type": "json", "schema": schema("arch-decisions")}, PACKAGE_FACTS),
    ("ARCH-PACKAGE-LITE", "writer",
     {"type": "files", "allowed": ["chosen/*.md", "decisions.json"],
      "required": ["chosen/containers.md", "chosen/data-model.md", "decisions.json"], "status_trailer": True},
     PACKAGE_FACTS),
    ("STACK-VERIFY", "researcher", {"type": "json", "schema": schema("stack-verify")}, PACKAGE_FACTS),
    ("ARCH-REVIEW", "reviewer", {"type": "json", "schema": schema("findings")}, {"lens": "L2"}),
    ("ARCH-FIX", "fixer", {"type": "files", "allowed": ["chosen/**", "deferred.md", "decisions.json",
                                                        "review/resolution.md"],
                           "required": ["review/resolution.md"], "status_trailer": True}, PACKAGE_FACTS),
    ("APPROACH", "writer", {"type": "files", "allowed": ["approach.md"], "required": ["approach.md"],
                            "status_trailer": True}, None),
    ("PROPOSAL-A", "writer", {"type": "files", "allowed": ["sections/*.md"], "required": sec_files([2, 3, 4, 5]),
                              "per_file": per_sections([2, 3, 4, 5]), "status_trailer": True}, PROPOSAL_FACTS),
    ("PROPOSAL-B", "writer", {"type": "files", "allowed": ["sections/*.md"], "required": sec_files([6, 7, 8, 9]),
                              "per_file": per_sections([6, 7, 8, 9]), "status_trailer": True}, PROPOSAL_FACTS),
    ("PROPOSAL-C", "writer", {"type": "files", "allowed": ["sections/*.md"],
                              "required": sec_files([10, 11, 12, 13]), "per_file": per_sections([10, 11, 12, 13]),
                              "status_trailer": True}, PROPOSAL_FACTS),
    ("EXEC-ONEPAGER", "writer", {"type": "files", "allowed": ["sections/01.md", "ONE-PAGER.md"],
                                 "required": ["sections/01.md", "ONE-PAGER.md"],
                                 "per_file": {"ONE-PAGER.md": {"headings": stubs._ONE_PAGER_HEADINGS,
                                                               "mermaid": ["flowchart"]}},
                                 "status_trailer": True}, PROPOSAL_FACTS),
    ("PRFAQ", "writer", {"type": "files", "allowed": ["PRFAQ.md"], "required": ["PRFAQ.md"]}, None),
    ("PROPOSAL-LITE", "writer", {"type": "files", "allowed": ["sections/*.md", "ONE-PAGER.md"],
                                 "required": sec_files([1, 2, 3, 6, 7, 11, 12, 13]) + ["ONE-PAGER.md"],
                                 "per_file": per_sections([1, 2, 3, 6, 7, 11, 12, 13], approach=True),
                                 "status_trailer": True}, None),
    ("PROPOSAL-RUBRIC", "rubric", {"type": "json", "schema": schema("rubric")}, None),
    ("PROPOSAL-REDTEAM", "redteam", {"type": "json", "schema": schema("redteam")}, None),
    ("PROPOSAL-FIX", "fixer", {"type": "files", "allowed": ["sections/*.md", "review/resolution.md"],
                               "required": ["sections/02.md", "review/resolution.md"], "status_trailer": True},
     PROPOSAL_FACTS),
]


def make_job(template, kind, contract, facts=None, jid=None, run=None):
    job = {"schema": 1, "run": run, "id": jid or ("t-" + template), "step": "x", "kind": kind,
           "template": template, "family": "claude", "tier": "default", "prompt_file": "prompts/x.prompt.md",
           "out": "out.md", "tools": "none", "cwd": "empty", "contract": contract, "privacy": {}}
    if facts is not None:
        job["stub"] = facts
    return job


def outside_fences(text):
    out, inside = [], False
    for line in text.split("\n"):
        if line.strip().startswith("```"):
            inside = not inside
            continue
        if not inside:
            out.append(line)
    return "\n".join(out)


class StubContractTests(unittest.TestCase):
    def test_every_template_kind_validates(self):
        with tempfile.TemporaryDirectory() as run:
            for template, kind, contract, facts in CASES:
                with self.subTest(template=template):
                    job = make_job(template, kind, contract, facts, run=run)
                    text = stubs.respond(job, "prompt text for %s" % template)
                    ok, errors, _parsed = validate.check_contract(text, contract, run)
                    self.assertTrue(ok, "%s: %s\n%s" % (template, errors, text[:1500]))
                    self.assertTrue(text.isascii() if hasattr(text, "isascii") else True, template)

    def test_every_template_validates_without_facts(self):
        with tempfile.TemporaryDirectory() as run:
            for template, kind, contract, _facts in CASES:
                with self.subTest(template=template):
                    text = stubs.respond(make_job(template, kind, contract, None, run=run), "")
                    ok, errors, _ = validate.check_contract(text, contract, run)
                    self.assertTrue(ok, "%s without facts: %s" % (template, errors))

    def test_every_contract_type_minimal(self):
        contracts = [{"type": "text"}, {"type": "idea-blocks", "prefix": "X", "min": 1}, {"type": "json"},
                     {"type": "sections", "headings": ["Intro"]}, {"type": "cards", "ids": ["I-001"],
                                                                     "lines": ["Title:"]},
                     {"type": "files", "allowed": ["**/*.md"], "status_trailer": True}]
        for c in contracts:
            with self.subTest(contract=c["type"]):
                text = stubs.respond({"id": "min-" + c["type"], "contract": c}, "")
                ok, errors, _ = validate.check_contract(text, c, None)
                self.assertTrue(ok, "%s: %s\n%s" % (c["type"], errors, text))

    def test_job_without_contract_is_text(self):
        text = stubs.respond({"id": "no-contract"}, "")
        ok, errors, _ = validate.check_contract(text, {"type": "text"}, None)
        self.assertTrue(ok, errors)

    def test_deterministic_by_job_id(self):
        with tempfile.TemporaryDirectory() as run:
            for template, kind, contract, facts in CASES:
                a = stubs.respond(make_job(template, kind, contract, facts, run=run), "p")
                b = stubs.respond(make_job(template, kind, contract, facts, run=run), "p")
                self.assertEqual(a, b, template)
        c1 = {"type": "idea-blocks", "prefix": "S3", "min": 3}
        x = stubs.respond(make_job("S3-EDE", "generator", c1, jid="4.2-S3"), "")
        y = stubs.respond(make_job("S3-EDE", "generator", c1, jid="4.2-S3~gpt-alt"), "")
        self.assertNotEqual(x, y)

    def test_sk_template_schemas_when_present(self):
        sdir = os.path.join(paths.SK, "templates", "schemas")
        paths.require(sdir, owner="B3")
        names = sorted(f for f in os.listdir(sdir) if f.endswith(".schema.json"))
        self.assertTrue(names)
        kinds = {"arch-candidate": "ARCH-CANDIDATE"}
        for f in names:
            stem = f[:-len(".schema.json")]
            tmpl = {v: k for k, v in stubs._TEMPLATE_SHAPES.items()}.get(stem, kinds.get(stem, stem.upper()))
            contract = {"type": "json", "schema": "SK:templates/schemas/" + f}
            with self.subTest(schema=f):
                text = stubs.respond(make_job(tmpl, "writer", contract, None), "")
                ok, errors, _ = validate.check_contract(text, contract, None)
                self.assertTrue(ok, "%s: %s" % (f, errors))


class StubSemanticsTests(unittest.TestCase):
    def curator(self, aliases, homogenized=False):
        c = {"type": "json", "schema": schema("merges")}
        job = make_job("CURATOR", "curator", c, {"aliases": aliases, "axes": AXES})
        old = os.environ.get("UB_STUB_HOMOGENIZED")
        try:
            if homogenized:
                os.environ["UB_STUB_HOMOGENIZED"] = "1"
            else:
                os.environ.pop("UB_STUB_HOMOGENIZED", None)
            return json.loads(stubs.respond(job, ""))
        finally:
            if old is None:
                os.environ.pop("UB_STUB_HOMOGENIZED", None)
            else:
                os.environ["UB_STUB_HOMOGENIZED"] = old

    def test_curator_shape(self):
        aliases = ["S%d-%02d" % (s, i) for s in range(1, 6) for i in range(1, 13)] + ["HP-01", "H-01", "H-02"]
        data = self.curator(aliases)
        ideas = data["ideas"]
        seen = [a for i in ideas for a in i["aliases"]]
        self.assertEqual(sorted(seen), sorted(aliases), "every alias maps to exactly one canonical idea")
        self.assertTrue(all(1 <= len(i["aliases"]) <= 3 for i in ideas))
        self.assertTrue(all(len(i["aliases"]) == 3 for i in ideas[:-1]))
        clusters = [i["cluster"] for i in ideas]
        self.assertTrue(6 <= len(set(clusters)) <= 12, set(clusters))
        largest = max(clusters.count(c) for c in set(clusters))
        self.assertLessEqual(largest / float(len(ideas)), 0.25)
        prim = [i for i in ideas if i["primary"]]
        self.assertEqual(len(prim), 1)
        self.assertIn("HP-01", prim[0]["aliases"])
        cells = set(tuple(i["cell"]) for i in ideas)
        self.assertGreater(len(cells), 3, "cells cycle over the axes")
        self.assertEqual(len(set(i["key"] for i in ideas)), len(ideas))
        for i in ideas:
            for field in ("title", "pitch", "mechanism", "cluster"):
                self.assertIsNone(ALIAS_RX.search(i[field]), i[field])
                self.assertIsNone(LABEL_WORDS.search(i[field]), i[field])

    def test_curator_homogenized(self):
        aliases = ["S%d-%02d" % (s, i) for s in range(1, 6) for i in range(1, 13)]
        data = self.curator(aliases, homogenized=True)
        clusters = [i["cluster"] for i in data["ideas"]]
        largest = max(clusters.count(c) for c in set(clusters))
        self.assertGreater(largest / float(len(clusters)), 0.25)

    def test_idea_cells_come_from_axes(self):
        text = stubs.respond(make_job("S3-EDE", "generator", {"type": "idea-blocks", "prefix": "S3", "min": 9},
                                      {"axes": AXES}), "")
        cells = re.findall(r"^- Cell: (.+)$", text, re.M)
        self.assertEqual(len(cells), 9)
        valid = set(" / ".join(c) for c in itertools.product(*AXES.values()))
        self.assertTrue(set(cells) <= valid, cells)
        self.assertGreater(len(set(cells)), 3)
        for line in re.findall(r"^### (.+)$", text, re.M):
            self.assertLessEqual(len(line.split()) - 1, 8, "titles have at most 8 words")

    def test_final_line_cycles(self):
        checks, reviews = set(), set()
        for n in range(40):
            iid = "I-%03d" % n
            t = stubs.respond(make_job("CHECK", "checker", {"type": "sections", "headings": ["## 1"],
                                                            "final_line": CHECK_FINAL},
                                       {"idea_id": iid}, jid="7.1-" + iid), "")
            checks.add(re.search(r"VERDICT: ([A-Z ]+);", t.strip().splitlines()[-1]).group(1))
            r = stubs.respond(make_job("REVIEWER", "reviewer", {"type": "sections", "headings": ["## 1"],
                                                                "final_line": REVIEW_FINAL},
                                       {"idea_id": iid}, jid="10.3-" + iid), "")
            last = r.strip().splitlines()[-1]
            reviews.add("DON'T BACK" if "DON'T" in last else ("BACK IF" if "BACK IF" in last else "BACK"))
        self.assertEqual(checks, {"NOT LOCATED", "ADJACENT", "CROWDED"})
        self.assertEqual(reviews, {"BACK", "BACK IF", "DON'T BACK"})
        syn = stubs.respond(make_job("SYNTHESIS", "synthesis", {"type": "sections", "headings": ["## S"],
                                                                "final_line": "^WHOLE-EFFORT: (CONTINUE|STOP)"}), "")
        self.assertTrue(syn.strip().splitlines()[-1].startswith("WHOLE-EFFORT: CONTINUE"))
        probe = stubs.respond(make_job("PROBE", "writer", {"type": "sections", "headings": ["## P"],
                                                           "final_line": "^RESULT: PENDING$"}), "")
        self.assertEqual(probe.strip().splitlines()[-1], "RESULT: PENDING")

    def test_stub_final_line_fact_wins(self):
        c = {"type": "text", "final_line": r"^DONE: .+$"}
        t = stubs.respond(make_job("X", "writer", c, {"final_line": "DONE: all good"}), "")
        self.assertEqual(t.strip().splitlines()[-1], "DONE: all good")

    def test_generic_regex_final_line(self):
        c = {"type": "text", "final_line": r"^SCORE: [1-5]/5 \((low|high)\)$", "regex": r"KEY-\d{3}"}
        t = stubs.respond(make_job("X", "writer", c), "")
        ok, errors, _ = validate.check_contract(t, c, None)
        self.assertTrue(ok, errors)

    def test_tournament_verdicts_are_order_consistent(self):
        cards = {"I-001": "Title: Alpha board\nProblem: one", "I-002": "Title: Beta queue\nProblem: two",
                 "I-003": "Title: Gamma loop\nProblem: three"}

        def prompt(order):
            labels = dict(zip(order, "ABC"))
            body = ["HEADER", "", "CARDS"]
            for k in order:
                body += ["", "[Card %s]" % labels[k]] + cards[k].split("\n")
            body += ["", "PAIRS (the first card named in a pair is FIRST, the second is SECOND)"]
            pairs = [("I-001", "I-002"), ("I-001", "I-003"), ("I-002", "I-003")]
            mapping = {}
            for n, (x, y) in enumerate(pairs, 1):
                pid = "P%02d" % n
                body.append("%s: Card %s vs Card %s" % (pid, labels[x], labels[y]))
                mapping[pid] = (x, y)
            return "\n".join(body), mapping

        c = {"type": "json", "schema": schema("verdicts"),
             "cover": {"array": "verdicts", "key": "pair_id", "ids": ["P01", "P02", "P03"]}}
        winners = []
        for order in (["I-001", "I-002", "I-003"], ["I-003", "I-001", "I-002"]):
            text, mapping = prompt(order)
            out = json.loads(stubs.respond(make_job("TOURNAMENT", "judge", c, jid="j-" + order[0]), text))
            won = {}
            for v in out["verdicts"]:
                x, y = mapping[v["pair_id"]]
                won[frozenset((x, y))] = x if v["winner"] == "FIRST" else y
            winners.append(won)
        self.assertEqual(winners[0], winners[1])
        rev_text, rev_map = prompt(["I-001", "I-002", "I-003"])
        rev_text = re.sub(r"Card ([A-C]) vs Card ([A-C])", r"Card \2 vs Card \1", rev_text)
        out = json.loads(stubs.respond(make_job("TOURNAMENT", "judge", c, jid="j-rev"), rev_text))
        for v in out["verdicts"]:
            x, y = rev_map[v["pair_id"]]
            winner = y if v["winner"] == "FIRST" else x
            self.assertEqual(winner, winners[0][frozenset((x, y))])

    def test_screen_scores_vary_by_idea_and_agree_across_judges(self):
        ids = ["I-%03d" % i for i in range(1, 16)]
        c = {"type": "json", "schema": schema("screen"), "cover": {"array": "scores", "key": "id", "ids": ids}}
        a = json.loads(stubs.respond(make_job("SCREEN", "judge", c, jid="6.2-claude"), ""))
        b = json.loads(stubs.respond(make_job("SCREEN", "judge", c, jid="6.2-gpt"), ""))
        self.assertEqual([s["id"] for s in a["scores"]], ids)
        totals = set(sum(s["c"].values()) for s in a["scores"])
        self.assertGreater(len(totals), 1, "scores differ between ideas")
        self.assertEqual(a["scores"], b["scores"])
        self.assertTrue(all(s["g1"] and s["g2"] and s["g3"] for s in a["scores"]))
        self.assertTrue(all(2 <= v <= 5 for s in a["scores"] for v in s["c"].values()))

    def test_arch_judge_never_vetoes(self):
        c = {"type": "json", "schema": schema("arch-judge"),
             "cover": {"array": "candidates", "key": "label", "ids": ["A", "B"]}}
        out = json.loads(stubs.respond(make_job("ARCH-JUDGE", "arch-judge", c, {"labels": ["A", "B"]}), ""))
        self.assertEqual([x["label"] for x in out["candidates"]], ["A", "B"])
        self.assertFalse(any(x["veto"] for x in out["candidates"]))
        self.assertTrue(all(1 <= s["score"] <= 5 for x in out["candidates"] for s in x["scores"]))

    def test_arch_drivers_rules(self):
        out = json.loads(stubs.respond(make_job("ARCH-DRIVERS", "arch-author",
                                                {"type": "json", "schema": schema("arch-drivers")}), ""))
        self.assertEqual(sum(q["weight"] for q in out["quality_goals"]), 70)
        self.assertTrue(3 <= len(out["quality_goals"]) <= 5)
        self.assertTrue(5 <= len(out["qas"]) <= 10)
        self.assertTrue(all(re.match(r"^QG[1-5]$", q["id"]) for q in out["quality_goals"]))
        self.assertTrue(all(re.match(r"^QAS-\d{2}$", q["id"]) for q in out["qas"]))
        self.assertTrue(all(re.match(r"^HC-\d+$", q["id"]) for q in out["hard_constraints"]))
        self.assertTrue(all(re.match(r"^EXT-\d+$", q["id"]) for q in out["context"]["external"]))
        self.assertTrue(all(re.match(r"^ACT-\d+$", q["id"]) for q in out["context"]["actors"]))
        self.assertTrue(all(re.match(r"^AS-\d+$", q["id"]) for q in out["planning_assumptions"]))

    def test_arch_decisions_cross_references(self):
        out = json.loads(stubs.respond(make_job("ARCH-DECISIONS", "writer",
                                                {"type": "json", "schema": schema("arch-decisions")},
                                                PACKAGE_FACTS), ""))
        rids = set(r["id"] for r in out["risks"])
        self.assertTrue(set(PACKAGE_FACTS["r_ids"]) <= rids)
        self.assertEqual(len(rids), len(out["risks"]), "R-ids are unique")
        for adr in out["adrs"]:
            self.assertGreaterEqual(len(adr["options"]), 2)
            for bad in adr["bad"]:
                self.assertTrue(set(bad["risk_ids"]) <= rids)
        self.assertTrue(all(re.match(r"^R-\d{3}$", r) for r in rids))
        self.assertTrue(all(re.match(r"^TD-\d{2}$", d["id"]) for d in out["debt"]))

    def test_cards_are_neutral(self):
        c = {"type": "cards", "ids": ["I-001", "I-002"], "lines": CARD_LINES}
        text = stubs.respond(make_job("NORMALIZER", "normalizer", c), "")
        body = "\n".join(l for l in text.splitlines() if not l.startswith("## "))
        self.assertIsNone(ALIAS_RX.search(body))
        self.assertIsNone(LABEL_WORDS.search(body))
        self.assertIn("Prior art: NOT LOCATED - differentiator:", text)


class StubLintShapeTests(unittest.TestCase):
    """Should-level (4.17): packages built from facts are coherent enough to pass lint-arch / lint-proposal."""

    def files_of(self, template, contract, facts):
        from ublib import filesproto
        text = stubs.respond(make_job(template, "writer", contract, facts), "")
        files, status, warnings = filesproto.parse_file_blocks(text)
        self.assertEqual(status.get("status"), "complete")
        return files

    def arch_files(self):
        cases = {c[0]: c for c in CASES}
        files = {}
        for name in ("ARCH-PACKAGE-STRUCTURE", "ARCH-PACKAGE-CROSSCUT"):
            _t, _k, contract, facts = cases[name]
            files.update(self.files_of(name, contract, facts))
        return files

    def test_no_placeholders_outside_fences(self):
        for rel, content in self.arch_files().items():
            self.assertIsNone(PLACEHOLDER_RX.search(outside_fences(content)), rel)

    def test_mermaid_lines_balance(self):
        for rel, content in self.arch_files().items():
            blocks = re.findall(r"```mermaid\n(.*?)```", content, re.S)
            for block in blocks:
                lines = [l for l in block.split("\n") if l.strip()]
                self.assertIn(lines[0].strip().split()[0], ("C4Context", "C4Container", "C4Component", "flowchart",
                                                            "graph", "sequenceDiagram", "erDiagram",
                                                            "stateDiagram-v2", "classDiagram"), rel)
                for line in lines:
                    self.assertNotIn("\t", line)
                    for o, c in ("()", "[]", "{}"):
                        self.assertEqual(line.count(o), line.count(c), "%s: %r" % (rel, line))
                    self.assertEqual(line.count('"') % 2, 0, "%s: %r" % (rel, line))
            c4 = [i for i, b in enumerate(blocks) if b.strip().startswith("C4")]
            for i in c4:
                self.assertTrue(any(b.strip().startswith(("flowchart", "graph")) for b in blocks[i + 1:]), rel)

    def test_traceability_and_word_counts(self):
        files = self.arch_files()
        cont, runtime = files["chosen/containers.md"], files["chosen/runtime.md"]
        for q in PACKAGE_FACTS["qg_ids"]:
            self.assertIn(q, cont)
        for e in PACKAGE_FACTS["ext_ids"]:
            self.assertIn(e, cont)
        for cid in set(re.findall(r"\bC-\d+\b", cont)):
            self.assertIn(cid, runtime)
        self.assertRegex(runtime, r"(?im)^## F-\d+ .*(failure|recovery)")
        for rel in ("chosen/deployment.md", "chosen/security-privacy.md", "chosen/cost-model.md"):
            self.assertGreaterEqual(len(files[rel].split()), 120, rel)
        self.assertIn("## Assumptions", files["chosen/cost-model.md"])
        self.assertIn("Sensitivity", files["chosen/cost-model.md"])

    def test_proposal_sections(self):
        cases = {c[0]: c for c in CASES}
        files = {}
        for name in ("PROPOSAL-A", "PROPOSAL-B", "PROPOSAL-C", "EXEC-ONEPAGER"):
            _t, _k, contract, facts = cases[name]
            files.update(self.files_of(name, contract, facts))
        for n in range(1, 14):
            rel = "sections/%02d.md" % n
            self.assertTrue(files[rel].startswith(SECTION_HEADS[n]), rel)
            self.assertNotIn("novel", files[rel].lower())
            self.assertIsNone(PLACEHOLDER_RX.search(outside_fences(files[rel])), rel)
        self.assertLessEqual(len(files["sections/01.md"].split()), 300)
        self.assertLessEqual(len(files["ONE-PAGER.md"].split()), 550)
        self.assertIn("Milestone 0", files["sections/08.md"])
        self.assertIn("kill criterion", files["sections/08.md"])
        items = [l for l in files["sections/13.md"].splitlines() if l.startswith("- ")]
        self.assertTrue(items)
        for item in items:
            self.assertIn("Owner:", item)
            self.assertIn("Decide by:", item)
        cited = set(re.findall(r"\[(S-\d{3})\]", "".join(files.values())))
        self.assertTrue(cited <= set(PROPOSAL_FACTS["source_ids"]))
        for n in (2, 4, 5, 10):
            for sentence in re.split(r"(?<=[.!?])\s+", files["sections/%02d.md" % n]):
                if re.search(r"[\d%$]", sentence) and not sentence.startswith("#"):
                    self.assertRegex(sentence, r"\[S-\d{3}\]|https?://|\[ASSUMPTION|\[ESTIMATE")


class StubEnvTests(unittest.TestCase):
    def setUp(self):
        self._saved = {k: os.environ.get(k) for k in ("UB_STUB_FAIL", "UB_STUB_DELAY_S")}

    def tearDown(self):
        for k, v in self._saved.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v

    def test_fail_regex(self):
        os.environ["UB_STUB_FAIL"] = r"^4\.2-S3$"
        with self.assertRaises(stubs.StubFailure):
            stubs.respond({"id": "4.2-S3", "contract": {"type": "text"}}, "")
        stubs.respond({"id": "4.2-S2", "contract": {"type": "text"}}, "")

    def test_delay(self):
        os.environ["UB_STUB_DELAY_S"] = "0.3"
        t0 = time.time()
        stubs.respond({"id": "d", "contract": {"type": "text"}}, "")
        self.assertGreaterEqual(time.time() - t0, 0.25)

    def test_regex_example_generator(self):
        for rx in (r"^RESULT: PENDING$", CHECK_FINAL, REVIEW_FINAL, r"\d{3}-[a-z]+", r"[^x]y{2,3}(z|w)?$",
                   r"^(?:A|B)\s+\w+\.$"):
            ex = stubs.regex_example(rx)
            self.assertIsNotNone(ex, rx)
            self.assertRegex(ex, rx)


if __name__ == "__main__":
    unittest.main()
