"""Deterministic stub outputs for every contract type (KIT_SPEC 4.17, 11.3). Test harness only: the release archive
has no tests/ folder, so this module never ships with the kit.

Public API (frozen, 4.17):
    respond(job: dict, prompt_text: str) -> str
    class StubFailure(Exception)

The `stub` backend (ublib/backends/stub.py) loads this file from its fixed place in a source checkout and calls
respond() for every job when UB_FAKE_FAMILIES=1; the fake CLIs call it for the `stub` scenario action, and the e2e
answerer calls it for HOST_BATCH jobs. Tests import it as `stubs` with tests/harness on sys.path; it needs the kit's
scripts folder on sys.path for `ublib`. The returned text is raw model-like output that satisfies job["contract"]
(FILE protocol + STATUS trailer for "files").

Determinism: every choice comes from random.Random(sha256(job id)) or from hashes of stable keys (idea IDs, card
text, labels), never from the clock. Facts come from job["stub"] (4.17 table); a job without facts still gets valid,
generic output. For architecture and proposal writers the stub may also read run files (drivers.json, criteria.json,
run.json, sources.json) under job["run"] as a fallback for missing facts; it never writes anything.

Environment (3.3, test seams only):
    UB_STUB_FAIL=<regex>     raise StubFailure when re.search(regex, job id) matches
    UB_STUB_DELAY_S=<float>  sleep before answering
    UB_STUB_HOMOGENIZED=1    the curator puts more than 25% of the ideas into one cluster

Generated prose is ASCII, contains no digits where the proposal lint would ask for citations, never uses the word
"novel", never contains alias-like IDs (S3-01, H-2, ...) or the words "origin:", "strategy:", "generated by" in text
that reaches judge prompts, and never contains lint placeholders (TODO, TBD, XXX, lorem, double braces, <word>).
"""

import hashlib
import itertools
import json
import os
import random
import re
import sys
import time

_SCRIPTS = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "skills",
                        "ultimate-brainstorm", "scripts")
if _SCRIPTS not in sys.path:
    sys.path.insert(0, _SCRIPTS)

from ublib import textio  # noqa: E402
from ublib import validate  # noqa: E402

__all__ = ["respond", "StubFailure"]

try:  # Python 3.11+
    from re import _parser as _sre_parse  # noqa: N813
    from re import _constants as _sre_c
except ImportError:  # Python 3.9 / 3.10
    import sre_parse as _sre_parse  # noqa: F401
    import sre_constants as _sre_c


class StubFailure(Exception):
    """Raised for job ids matching UB_STUB_FAIL (an injected model failure)."""


# ---------------------------------------------------------------- word banks (ASCII, no digits)

_SUBJECTS = ["The team", "Each nurse", "A small pilot group", "The first version", "The charge nurse",
             "The service", "Every shift lead", "The operations desk", "A ward coordinator", "The scheduling office"]
_VERBS = ["records", "reduces", "tests", "tracks", "limits", "shares", "confirms", "surfaces", "simplifies",
          "measures"]
_OBJECTS = ["handover errors", "open shift gaps", "manual phone calls", "weekly overtime", "response time",
            "setup effort", "approval delays", "last minute changes", "staffing blind spots", "duplicate requests"]
_TAILS = ["within the first month", "before any scaling decision", "with a weekly review", "under the stated constraints",
          "for the pilot ward only", "without new hardware", "during night shifts", "with a manual fallback",
          "using existing accounts", "while keeping an audit trail"]
_ADJ = ["Quiet", "Shared", "Rolling", "Pocket", "Open", "Paired", "Local", "Steady", "Nightly", "Visible", "Simple",
        "Trusted", "Relay", "Layered", "Mirror", "Buddy", "Standing", "Folded"]
_NOUNS = ["ledger", "board", "handoff", "roster", "queue", "market", "pledge", "badge", "window", "compass", "loop",
          "signal", "bridge", "lane", "bench", "harbor", "beacon", "circle"]
_TAGS = ["kestrel", "juniper", "cobalt", "saffron", "willow", "granite", "harbor", "ember", "lumen", "tundra",
         "maple", "orchid", "quartz", "sierra", "marlin", "aspen", "birch", "comet", "delta", "falcon", "garnet",
         "heron", "indigo", "jasper"]
_GREEK = ["alpha", "beta", "gamma", "delta", "epsilon", "zeta", "eta", "theta", "iota", "kappa", "lambda", "mu"]

_CODE_MARKER = "ub-stub-code-marker"  # appears only inside a fenced block of the researcher's FACTS (privacy tests)

_DEFAULT_AXES = {"Moment": ["planning", "handover", "night shift"], "Channel": ["mobile", "desk", "paper"]}
_FIXED_ARCH_CRITERIA = ["time_to_mvp", "team_fit", "run_cost", "reversibility", "operational_simplicity"]
_PROPOSAL_HEADINGS = {
    1: "## 1. Executive Summary", 2: "## 2. Problem and Evidence", 3: "## 3. Solution", 4: "## 4. Users and Market",
    5: "## 5. Differentiation vs Prior Art", 6: "## 6. Architecture Summary", 7: "## 7. Scope and MVP",
    8: "## 8. Roadmap and Milestones", 9: "## 9. Team and Effort", 10: "## 10. Budget and Cost",
    11: "## 11. Risks and Mitigations", 12: "## 12. Success Metrics and Validation Plan", 13: "## 13. Open Questions"}
_ONE_PAGER_HEADINGS = ["## Problem", "## Solution", "## Why now", "## Who", "## Differentiation",
                       "## Architecture at a glance", "## MVP", "## Roadmap", "## Budget", "## Top risks", "## Metrics",
                       "## The ask"]

_TEMPLATE_SHAPES = {
    "CURATOR": "merges", "QUICK-CURATE": "quick-curated", "ARCH-DRIVERS": "arch-drivers",
    "ARCH-CANDIDATE": "arch-candidate", "ARCH-JUDGE": "arch-judge", "ARCH-DECISIONS": "arch-decisions",
    "STACK-VERIFY": "stack-verify", "ARCH-REVIEW": "findings", "PROPOSAL-RUBRIC": "rubric",
    "PROPOSAL-REDTEAM": "redteam", "QUICK-PROBE": "quick-probe", "FRAME-QUESTIONS": "frame-questions",
    "LENS": "lens"}
_KNOWN_SHAPES = set(_TEMPLATE_SHAPES.values()) | {"verdicts", "screen"}


# ---------------------------------------------------------------- context

def _h(*parts):
    """Stable non-negative integer hash of the parts."""
    return int(hashlib.sha256("\x1f".join(str(p) for p in parts).encode("utf-8")).hexdigest()[:12], 16)


class _Ctx(object):
    def __init__(self, job, prompt_text):
        self.job = job if isinstance(job, dict) else {}
        self.prompt = prompt_text or ""
        self.id = str(self.job.get("id") or "stub")
        self.rng = random.Random(int(hashlib.sha256(self.id.encode("utf-8")).hexdigest(), 16))
        facts = self.job.get("stub")
        self.facts = facts if isinstance(facts, dict) else {}
        self.template = str(self.job.get("template") or "").strip().upper()
        if self.template.endswith(".MD"):
            self.template = self.template[:-3]
        self.kind = str(self.job.get("kind") or "").strip().lower()
        run = self.job.get("run")
        self.run_dir = run if isinstance(run, str) and run else None
        split = self.job.get("split")
        self.split = split if isinstance(split, dict) else {}
        self._run_json = None
        self._counter = 0

    # --- prose
    def sentence(self, salt=""):
        self._counter += 1
        k = _h(self.id, salt, self._counter)
        return "%s %s %s %s." % (_SUBJECTS[k % len(_SUBJECTS)], _VERBS[(k // 7) % len(_VERBS)],
                                 _OBJECTS[(k // 53) % len(_OBJECTS)], _TAILS[(k // 401) % len(_TAILS)])

    def sentences(self, n, salt=""):
        return " ".join(self.sentence(salt) for _ in range(max(1, n)))

    def title(self, salt=""):
        k = _h(self.id, "title", salt)
        return "%s %s %s" % (_ADJ[k % len(_ADJ)], _NOUNS[(k // 19) % len(_NOUNS)], _TAGS[(k // 347) % len(_TAGS)])

    def cycle(self, n, key=None):
        return _h(key if key is not None else self.id, "cycle") % n

    # --- run files (read-only fallbacks)
    def run_file(self, *rel):
        if not self.run_dir:
            return None
        return os.path.join(self.run_dir, *rel)

    def run_json_file(self, *rel):
        path = self.run_file(*rel)
        if not path or not os.path.isfile(path):
            return None
        try:
            return textio.read_json(path)
        except (OSError, ValueError):
            return None

    def run_meta(self):
        if self._run_json is None:
            self._run_json = self.run_json_file("run.json") or {}
        return self._run_json

    def fact(self, name, default=None):
        value = self.facts.get(name)
        return default if value in (None, "", [], {}) else value


def _slug(text):
    return re.sub(r"[^a-z0-9]+", "-", str(text).lower()).strip("-") or "item"


# ---------------------------------------------------------------- regex example generator

def _cat_char(cat):
    name = str(cat)
    if "NOT_DIGIT" in name:
        return "a"
    if "DIGIT" in name:
        return "1"
    if "NOT_SPACE" in name:
        return "a"
    if "SPACE" in name:
        return " "
    if "NOT_WORD" in name:
        return " "
    if "WORD" in name:
        return "a"
    return "a"


def _in_char(items):
    if items and items[0][0] == _sre_c.NEGATE:
        body = items[1:]
        for cand in "ax1 Z_-.":
            if not _in_set(cand, body):
                return cand
        return "~"
    for op, av in items:
        if op == _sre_c.LITERAL:
            return chr(av)
        if op == _sre_c.RANGE:
            return chr(av[0])
        if op == _sre_c.CATEGORY:
            return _cat_char(av)
    return "a"


def _in_set(ch, items):
    for op, av in items:
        if op == _sre_c.LITERAL and ord(ch) == av:
            return True
        if op == _sre_c.RANGE and av[0] <= ord(ch) <= av[1]:
            return True
        if op == _sre_c.CATEGORY:
            probe = {"1": "DIGIT", " ": "SPACE"}.get(ch, "WORD" if (ch.isalnum() or ch == "_") else "")
            name = str(av)
            if probe and probe in name and "NOT_" not in name:
                return True
    return False


_REPEATS = tuple(getattr(_sre_c, n) for n in ("MAX_REPEAT", "MIN_REPEAT", "POSSESSIVE_REPEAT") if hasattr(_sre_c, n))


def _emit(items, out):
    for op, av in items:
        if op == _sre_c.LITERAL:
            out.append(chr(av))
        elif op == _sre_c.NOT_LITERAL:
            out.append("x" if av != ord("x") else "y")
        elif op == _sre_c.ANY:
            out.append("x")
        elif op == _sre_c.IN:
            out.append(_in_char(av))
        elif op == _sre_c.BRANCH:
            _emit(av[1][0], out)
        elif op == _sre_c.SUBPATTERN:
            _emit(av[-1], out)
        elif op in _REPEATS:
            lo, _hi, sub = av
            sub = list(sub)
            if lo >= 1 and len(sub) == 1 and sub[0][0] == _sre_c.ANY:
                out.append("stub text")
                continue
            for _ in range(lo):
                _emit(sub, out)
        elif op == _sre_c.CATEGORY:
            out.append(_cat_char(av))
        # AT (anchors), ASSERT, ASSERT_NOT, GROUPREF and others emit nothing


def regex_example(pattern):
    """A string that re.search(pattern, ...) matches, or None when the generator cannot build one."""
    try:
        parsed = _sre_parse.parse(pattern)
        out = []
        _emit(list(parsed), out)
        text = "".join(out)
        if re.search(pattern, text):
            return text
    except Exception:  # noqa: BLE001 - any parser surprise means "no example"
        return None
    return None


# ---------------------------------------------------------------- final lines

def _final_line(ctx, rx):
    """The final line for a contract regex: stub.final_line, then the known verdict cycles, then a generated match."""
    cands = []
    if ctx.fact("final_line"):
        cands.append(str(ctx.facts["final_line"]))
    text = rx or ""
    if "WHOLE-EFFORT" in text:
        cands.append("WHOLE-EFFORT: CONTINUE - the stub synthesis found no stop condition")
    if "RESULT" in text:
        cands.append("RESULT: PENDING")
    if "VERDICT" in text and ("CROWDED" in text or "LOCATED" in text):
        key = ctx.fact("idea_id", ctx.id)
        verdict = ["NOT LOCATED", "ADJACENT", "CROWDED"][ctx.cycle(3, key)]
        cands.append("VERDICT: %s; DIFFERENTIATOR: a weekly pilot with a manual fallback" % verdict)
    if "VERDICT" in text and "BACK" in text:
        key = ctx.fact("idea_id", ctx.id)
        cands.append(["VERDICT: BACK", "VERDICT: BACK IF the pilot ward keeps using it",
                      "VERDICT: DON'T BACK"][ctx.cycle(3, str(key) + ctx.id)])
    if text:
        example = regex_example(text)
        if example:
            cands.append(example)
    if not text:
        return cands[0] if cands else None
    for cand in cands:
        try:
            if re.search(text, cand):
                return cand
        except re.error:
            return cands[0] if cands else None
    return cands[0] if cands else "stub"


# ---------------------------------------------------------------- JSON generation

def _types(schema):
    t = schema.get("type")
    if isinstance(t, list):
        return [x for x in t if x != "null"] or ["null"]
    if isinstance(t, str):
        return [t]
    if "properties" in schema:
        return ["object"]
    if "items" in schema:
        return ["array"]
    return []


_FALSE_NAMES = re.compile(r"veto|kill|reject|fail|block|stop|skip|provisional|error|excluded|homogen", re.I)


def _gen(schema, ctx, name="", item_key=None, path=""):
    """Generic instance from a schema (4.5 json stub rules)."""
    if not isinstance(schema, dict):
        return "stub"
    if isinstance(schema.get("enum"), list) and schema["enum"]:
        return schema["enum"][0]
    if "const" in schema:
        return schema["const"]
    types = _types(schema)
    t = types[0] if types else "string"
    if t == "object":
        props = schema.get("properties") or {}
        return {p: _gen(sub, ctx, p, item_key, path + "." + p) for p, sub in props.items()}
    if t == "array":
        items = schema.get("items") if isinstance(schema.get("items"), dict) else {"type": "string"}
        n = max(int(schema.get("minItems") or 0), 1)
        if isinstance(schema.get("maxItems"), int):
            n = min(n, schema["maxItems"])
        return [_gen(items, ctx, name, item_key, path + "[]") for _ in range(n)]
    if t == "integer":
        lo, hi = schema.get("minimum"), schema.get("maximum")
        if isinstance(lo, (int, float)) and isinstance(hi, (int, float)):
            return int((lo + hi) // 2)
        if item_key is not None:
            return 2 + _h(item_key, path) % 3
        if isinstance(lo, (int, float)):
            return int(lo)
        return 3
    if t == "number":
        lo, hi = schema.get("minimum"), schema.get("maximum")
        if isinstance(lo, (int, float)) and isinstance(hi, (int, float)):
            return (lo + hi) / 2.0
        if re.search(r"prob|conf|share|pct|ratio", name, re.I):
            return 0.5
        return 3
    if t == "boolean":
        return not bool(_FALSE_NAMES.search(name or ""))
    if t == "null":
        return None
    text = "stub"
    min_len = schema.get("minLength")
    if isinstance(min_len, int) and len(text) < min_len:
        text = (text + " text") * (min_len // 4 + 1)
    max_len = schema.get("maxLength")
    if isinstance(max_len, int):
        text = text[:max_len]
    return text


def _type_ok(value, t):
    if t == "object":
        return isinstance(value, dict)
    if t == "array":
        return isinstance(value, list)
    if t == "string":
        return isinstance(value, str)
    if t == "boolean":
        return isinstance(value, bool)
    if t == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if t == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if t == "null":
        return value is None
    return True


def _conform(schema, value, ctx, name="", item_key=None, path=""):
    """Fit a semantic value to a schema: keep what fits, generate what is missing, drop what is not allowed."""
    if not isinstance(schema, dict) or not schema:
        return value
    if isinstance(schema.get("enum"), list) and schema["enum"]:
        return value if value in schema["enum"] else schema["enum"][0]
    types = _types(schema)
    if types and not any(_type_ok(value, t) for t in types):
        if "null" in (schema.get("type") if isinstance(schema.get("type"), list) else []) and value is None:
            return None
        return _gen(schema, ctx, name, item_key, path)
    if isinstance(value, dict) and (not types or "object" in types):
        props = schema.get("properties")
        if not isinstance(props, dict):
            return value
        out = {}
        for p, sub in props.items():
            if p in value:
                out[p] = _conform(sub, value[p], ctx, p, item_key, path + "." + p)
            else:
                out[p] = _gen(sub, ctx, p, item_key, path + "." + p)
        if schema.get("additionalProperties") is not False:
            for k, v in value.items():
                if k not in out:
                    out[k] = v
        return out
    if isinstance(value, list) and (not types or "array" in types):
        items = schema.get("items") if isinstance(schema.get("items"), dict) else None
        out = [_conform(items, v, ctx, name, item_key, path + "[]") if items else v for v in value]
        min_items = schema.get("minItems")
        while isinstance(min_items, int) and len(out) < min_items:
            out.append(_gen(items or {"type": "string"}, ctx, name, item_key, path + "[]"))
        if isinstance(schema.get("maxItems"), int):
            out = out[:schema["maxItems"]]
        return out
    if isinstance(value, str):
        if isinstance(schema.get("maxLength"), int):
            value = value[:schema["maxLength"]]
        if isinstance(schema.get("minLength"), int) and len(value) < schema["minLength"]:
            value = value + " " + "x" * schema["minLength"]
    return value


def _get_path(obj, dotted):
    cur = obj
    for part in [p for p in str(dotted or "").split(".") if p]:
        if isinstance(cur, dict):
            cur = cur.get(part)
        else:
            return None
    return cur


def _sub_schema(schema, dotted):
    cur = schema
    for part in [p for p in str(dotted or "").split(".") if p]:
        if not isinstance(cur, dict):
            return None
        cur = (cur.get("properties") or {}).get(part)
    return cur if isinstance(cur, dict) else None


def _apply_cover(value, cover, schema, ctx):
    if not isinstance(cover, dict):
        return value
    arr_name, key = cover.get("array"), cover.get("key", "id")
    ids = [str(i) for i in (cover.get("ids") or [])]
    if not ids:
        return value
    arr_schema = _sub_schema(schema, arr_name) if schema else None
    item_schema = arr_schema.get("items") if isinstance(arr_schema, dict) and isinstance(arr_schema.get("items"),
                                                                                           dict) else None
    current = _get_path(value, arr_name) if arr_name else value
    current = current if isinstance(current, list) else []
    by_key = {}
    for item in current:
        if isinstance(item, dict) and key in item:
            by_key.setdefault(str(item[key]), item)
    new = []
    for cid in ids:
        item = by_key.get(cid)
        if item is None:
            item = _gen(item_schema, ctx, "", cid) if item_schema else {}
            if not isinstance(item, dict):
                item = {}
        item = dict(item)
        item[key] = cid
        new.append(item)
    # items whose key is not in the cover are dropped: the cover lists every expected ID
    if not arr_name:
        return new
    parts = [p for p in str(arr_name).split(".") if p]
    if not isinstance(value, dict):
        value = {}
    cur = value
    for part in parts[:-1]:
        if not isinstance(cur.get(part), dict):
            cur[part] = {}
        cur = cur[part]
    cur[parts[-1]] = new
    return value


# ---------------------------------------------------------------- semantic builders (json shapes)

def _qg_ids(ctx):
    ids = ctx.fact("qg_ids")
    if ids:
        return [str(i) for i in ids]
    drivers = ctx.run_json_file("10_ARCHITECTURE", "drivers.json") or {}
    found = [str(q.get("id")) for q in drivers.get("quality_goals") or [] if isinstance(q, dict) and q.get("id")]
    return found or ["QG1", "QG2", "QG3", "QG4"]


def _qas_ids(ctx):
    ids = ctx.fact("qas_ids")
    if ids:
        return [str(i) for i in ids]
    drivers = ctx.run_json_file("10_ARCHITECTURE", "drivers.json") or {}
    found = [str(q.get("id")) for q in drivers.get("qas") or [] if isinstance(q, dict) and q.get("id")]
    return found or ["QAS-%02d" % i for i in range(1, 7)]


def _ext_ids(ctx):
    ids = ctx.fact("ext_ids")
    if ids:
        return [str(i) for i in ids]
    drivers = ctx.run_json_file("10_ARCHITECTURE", "drivers.json") or {}
    ext = (drivers.get("context") or {}).get("external") if isinstance(drivers.get("context"), dict) else None
    found = [str(e.get("id")) for e in ext or [] if isinstance(e, dict) and e.get("id")]
    return found or ["EXT-1", "EXT-2"]


def _hc_ids(ctx):
    ids = ctx.fact("hc_ids")
    return [str(i) for i in ids] if ids else ["HC-1", "HC-2"]


def _containers(ctx):
    """[(id, name, tech)] from stub.containers (list of dicts or ids), else defaults."""
    raw = ctx.fact("containers")
    out = []
    names = ["Web app", "API service", "Scheduler worker", "Database", "Notification relay", "Admin console"]
    techs = ["TypeScript SPA", "Python service", "Python worker", "PostgreSQL", "Managed queue", "TypeScript SPA"]
    if isinstance(raw, list) and raw:
        for n, c in enumerate(raw):
            if isinstance(c, dict):
                cid = str(c.get("id") or "C-%d" % (n + 1))
                out.append((cid, str(c.get("name") or names[n % len(names)]),
                            str(c.get("tech") or techs[n % len(techs)])))
            else:
                out.append((str(c), names[n % len(names)], techs[n % len(techs)]))
        return out
    return [("C-%d" % (i + 1), names[i], techs[i]) for i in range(4)]


def _criteria_names(ctx):
    data = ctx.run_json_file("criteria.json")
    if isinstance(data, dict) and data:
        return [str(k) for k in data]
    crit = ctx.fact("criteria")
    if isinstance(crit, list) and crit:
        return [str(c) for c in crit]
    return ["Value", "Feasibility", "Distinctiveness"]


def _merges(ctx):
    aliases = [str(a) for a in (ctx.fact("aliases") or [])]
    if not aliases:
        aliases = ["S%d-%02d" % (s, i) for s in range(1, 6) for i in range(1, 7)]
    axes = ctx.fact("axes") or _DEFAULT_AXES
    axes = {str(k): [str(v) for v in vals] for k, vals in axes.items() if isinstance(vals, list) and vals}
    if not axes:
        axes = dict(_DEFAULT_AXES)
    primary_aliases = set(str(a) for a in (ctx.fact("primary_aliases") or [])) | \
        set(a for a in aliases if a.upper().startswith("HP-"))
    chunks = [aliases[i:i + 3] for i in range(0, len(aliases), 3)]
    n = len(chunks)
    k = max(1, min(12, n, max(6, int(round(n / 4.0)))))
    homogenized = os.environ.get("UB_STUB_HOMOGENIZED", "") not in ("", "0")
    big = int(n * 0.4) + 1 if homogenized else 0
    cells = list(itertools.product(*axes.values()))
    off = ctx.cycle(max(1, len(cells)))
    ideas = []
    for i, chunk in enumerate(chunks):
        cluster = _GREEK[0] if i < big else _GREEK[(i if not homogenized else i + 1) % k]
        title = ctx.title("idea-%d" % i)
        ideas.append({
            "key": "mech-%s-%02d" % (_slug(title), i + 1),
            "title": title,
            "pitch": ctx.sentence("pitch-%d" % i),
            "mechanism": ctx.sentence("mech-%d" % i) + " " + ctx.sentence("mech2-%d" % i),
            "aliases": chunk,
            "cluster": "Cluster " + cluster,
            "cell": list(cells[(off + i) % len(cells)]) if cells else [],
            "siblings": [],
            "baseline": i == 0,
            "primary": any(a in primary_aliases for a in chunk)})
    return {"axes": [{"name": name, "values": vals} for name, vals in axes.items()],
            "ideas": ideas,
            "notes": {"rerun": [], "leak_check": [], "merge_log": ["stub curator: three aliases per canonical idea"]}}


def _quick_aliases(ctx, n):
    """Source IDs for n quick ideas, one to three each (as _merges merges the CURATOR's): the job's stub facts (the
    QA-, QB- and H- IDs of the pool and seeds) grouped by prefix and taken three at a time from each group in turn, so
    ideas come from both generators and from the human seeds; a pool too small for n ideas is reused one ID at a
    time. Without facts: QA-01, QA-02, ... (bs.py quick-pick derives each idea's origin from these)."""
    flat = [str(a) for a in (ctx.fact("aliases") or [])]
    if not flat:
        return [["QA-%02d" % (i + 1)] for i in range(n)]
    groups = {}
    for a in flat:
        groups.setdefault(re.sub(r"-\d+$", "", a), []).append(a)
    queues = list(groups.values())
    out, turn = [], 0
    while len(out) < n and any(queues):
        queue = queues[turn % len(queues)]
        turn += 1
        if queue:
            out.append(queue[:3])
            del queue[:3]
    while len(out) < n:
        out.append([flat[len(out) % len(flat)]])
    return out


def _quick_curated(ctx):
    crits = _criteria_names(ctx)
    aliases = _quick_aliases(ctx, 6)
    ideas = []
    for i in range(6):
        qid = "Q-%02d" % (i + 1)
        ideas.append({
            "id": qid, "title": ctx.title(qid), "pitch": ctx.sentence(qid), "mechanism": ctx.sentence(qid + "m"),
            "cluster": "Cluster " + _GREEK[i % 5], "aliases": aliases[i],
            "gates": {"g1": True, "g2": True, "g3": True},
            "scores": [{"criterion": c, "score": 2 + _h(qid, c) % 4} for c in crits],
            "fails_if": ctx.sentence(qid + "f"), "problem": ctx.sentence(qid + "p"),
            "for_whom": "Night shift nurses on the pilot ward", "first_version": ctx.sentence(qid + "v")})
    return {"ideas": ideas}


def _arch_drivers(ctx):
    names = ["Reliability", "Time to market", "Privacy", "Operability"]
    weights = [25, 20, 15, 10]
    qgs = [{"id": "QG%d" % (i + 1), "name": names[i], "weight": weights[i], "why": ctx.sentence("qg%d" % i),
            "source": "STATED" if i < 2 else "ASSUMPTION"} for i in range(4)]
    qas = []
    for i in range(6):
        qas.append({"id": "QAS-%02d" % (i + 1), "qg": "QG%d" % (i % 4 + 1), "source": "A night shift nurse",
                    "stimulus": ctx.sentence("st%d" % i), "artifact": "The swap request flow",
                    "environment": "Normal operation", "response": ctx.sentence("rs%d" % i),
                    "measure": "Completed within the agreed response window",
                    "importance": "H" if i < 3 else "M", "difficulty": "M"})
    return {
        "product_goal": ctx.sentence("goal"),
        "quality_goals": qgs,
        "hard_constraints": [{"id": "HC-1", "text": "Runs on hardware the wards already have.", "source": "FRAME"},
                             {"id": "HC-2", "text": "Keeps staff data inside the approved region.",
                              "source": "FRAME"}],
        "soft_constraints": ["Prefer managed services.", "Prefer one deployable unit for the pilot."],
        "not_in_scope": ["Payroll integration.", "Rostering optimization."],
        "qas": qas,
        "context": {"system": {"name": "Shift swap service", "description": ctx.sentence("sys")},
                    "actors": [{"id": "ACT-1", "name": "Nurse", "description": "Requests and accepts swaps."},
                               {"id": "ACT-2", "name": "Charge nurse", "description": "Approves swaps."}],
                    "external": [{"id": "EXT-1", "name": "Hospital identity provider",
                                  "description": "Staff sign in.", "relationship": "authenticates users"},
                                 {"id": "EXT-2", "name": "Messaging gateway",
                                  "description": "Sends notifications.", "relationship": "delivers alerts"}]},
        "planning_assumptions": [{"id": "AS-1", "item": "Team size", "value": "two developers", "source": "ASSUMPTION"},
                                 {"id": "AS-2", "item": "Budget", "value": "moderate", "source": "ASSUMPTION"}],
        "open_questions": [{"q": "Which ward runs the pilot first?", "default": "The ward with the most swaps."}]}


def _arch_candidate(ctx):
    conts = _containers(ctx)
    exts = _ext_ids(ctx)
    return {
        "paradigm": ["Modular monolith", "Event driven services", "Local first client"][ctx.cycle(3)],
        "summary": ctx.sentences(2, "summary"),
        "containers": [{"id": cid, "name": name, "tech": tech, "responsibility": ctx.sentence(cid),
                        "data_owned": "Swap requests" if n == 0 else "Operational records",
                        "interface": "HTTPS JSON"} for n, (cid, name, tech) in enumerate(conts)],
        "external": [{"id": e, "name": "External system %s" % e.split("-")[-1]} for e in exts],
        "qas_mechanisms": [{"qas": q, "mechanism": ctx.sentence(q), "residual_risk": "Low"} for q in _qas_ids(ctx)],
        "stack": [{"layer": "runtime", "component": name, "choice": tech, "version": "1.0.0"}
                  for (_cid, name, tech) in conts],
        "data": {"entities": ["Nurse", "Shift", "Swap request"], "storage": "Managed relational database"},
        "deployment": ctx.sentence("deploy"),
        "security_threats": [{"threat": "Account takeover", "mitigation": "Single sign on with the hospital IdP"},
                             {"threat": "Data leak", "mitigation": "Encryption at rest and least privilege"},
                             {"threat": "Request forgery", "mitigation": "Signed approvals"}],
        "cost_monthly_usd": {"mvp_low": 100, "mvp_high": 300, "x10_low": 400, "x10_high": 900},
        "build_person_weeks": {"low": 6, "high": 10},
        "tradeoffs": [ctx.sentence("trade")],
        "rejected": [{"approach": "Custom mobile app", "why": ctx.sentence("rej1")},
                     {"approach": "Spreadsheet workflow", "why": ctx.sentence("rej2")}],
        "risks": ["Fails if charge nurses skip approvals.", "Fails if the IdP blocks service accounts."],
        "innovation_tokens": ["Push notifications on shared devices"]}


def _arch_judge(ctx, cover_ids):
    labels = [str(x) for x in (ctx.fact("labels") or cover_ids or ["A", "B"])]
    criteria = [str(c) for c in (ctx.fact("criteria") or (_qg_ids(ctx) + _FIXED_ARCH_CRITERIA))]
    cands = []
    for lab in labels:
        cands.append({
            "label": lab, "veto": False, "veto_reason": "",
            "scores": [{"criterion": c, "score": 2 + _h("arch", lab, c) % 4, "reason": ctx.sentence(lab + c)}
                       for c in criteria],
            "sensitivity_points": [ctx.sentence(lab + "sens")], "tradeoff_points": [ctx.sentence(lab + "trade")],
            "risks": [ctx.sentence(lab + "risk")], "non_risks": [ctx.sentence(lab + "non")]})
    steal = [{"from": labels[-1], "element": "Signed approval records", "why": ctx.sentence("steal")}] if labels else []
    return {"candidates": cands, "steal": steal}


def _risk_ids(ctx, n=5):
    ids = [str(r) for r in (ctx.fact("r_ids") or [])]
    k = 1
    while len(ids) < n:
        rid = "R-%03d" % k
        if rid not in ids:
            ids.append(rid)
        k += 1
    return ids


def _arch_decisions(ctx):
    qgs = _qg_ids(ctx)
    rids = _risk_ids(ctx)
    titles = ["Use a managed relational database", "Deploy as one modular service",
              "Authenticate through the hospital identity provider"]
    adrs = []
    for i, title in enumerate(titles):
        adrs.append({
            "title": title, "context": ctx.sentences(2, "ctx%d" % i), "drivers": qgs[:2],
            "options": [{"name": "Option %s" % n, "pros": [ctx.sentence("pro%d%s" % (i, n))],
                         "cons": [ctx.sentence("con%d%s" % (i, n))]} for n in ("one", "two")],
            "chosen": "Option one", "justification": ctx.sentence("just%d" % i),
            "good": [ctx.sentence("good%d" % i)],
            "bad": [{"text": ctx.sentence("bad%d" % i), "risk_ids": [rids[i % len(rids)]]}],
            "confirmation": "Reviewed in the architecture check before the pilot starts.",
            "more_info": "See the trade-off matrix."})
    risks = [{"id": rid, "text": ctx.sentence(rid), "likelihood": "HML"[n % 3], "impact": "MHL"[n % 3],
              "mitigation": ctx.sentence(rid + "m"), "owner": "Tech lead", "early_warning": ctx.sentence(rid + "w"),
              "source": "premortem" if n % 2 == 0 else "candidate"} for n, rid in enumerate(rids)]
    debt = [{"id": "TD-%02d" % (i + 1), "text": ctx.sentence("td%d" % i), "why": ctx.sentence("tdw%d" % i),
             "payoff_trigger": "More than one hospital uses the service."} for i in range(2)]
    return {"adrs": adrs, "risks": risks, "debt": debt}


def _stack_verify(ctx):
    rows = []
    for _cid, name, tech in _containers(ctx):
        rows.append({"layer": "runtime", "component": name, "choice": tech, "version": "1.0.0", "release_date": "",
                     "source_url": "", "status": "UNVERIFIED", "license": "MIT", "eol_note": "",
                     "alternatives": "", "innovation_token": False})
    return {"rows": rows}


def _findings(ctx):
    lens = str(ctx.fact("lens", "L1"))
    return {"findings": [{"id": "F-01", "lens": lens, "severity": "P3", "file": "chosen/containers.md",
                          "issue": ctx.sentence("issue"), "fix": ctx.sentence("fix"),
                          "evidence": ctx.sentence("evidence")}]}


def _rubric(ctx):
    keys = ["decision_readiness", "substance_over_theater", "strategic_coherence", "doneness_clarity",
            "scope_honesty", "downstream_usability", "shape_fit"]
    return {"scores": {k: 4 for k in keys}, "evidence": {k: ctx.sentence(k) for k in keys}, "must_fix": [],
            "top_fixes": [ctx.sentence("fix")], "overall_comment": ctx.sentence("overall")}


def _redteam(ctx):
    items = []
    for i in range(3):
        items.append({"claim": ctx.sentence("claim%d" % i), "steelman": ctx.sentence("steel%d" % i),
                      "fails_if": ctx.sentence("fails%d" % i), "impact": "HML"[i], "likelihood": "MHL"[i],
                      "cheapness": "HHM"[i], "cheapest_test": ctx.sentence("test%d" % i),
                      "kill_criterion": ctx.sentence("kill%d" % i)})
    return {"items": items}


def _parse_tournament_prompt(prompt):
    """({label: card text}, {pair_id: (first_label, second_label)}) from a bs.py tournament prompt."""
    cards, pairs, cur, buf = {}, {}, None, []
    for line in prompt.replace("\r\n", "\n").split("\n"):
        m = re.match(r"^\[Card ([A-Z]{1,2})\]\s*$", line.strip())
        if m:
            if cur is not None:
                cards[cur] = "\n".join(buf).strip()
            cur, buf = m.group(1), []
            continue
        pm = re.match(r"^\s*(P\d+)\s*:\s*Card\s+([A-Z]{1,2})\s+vs\.?\s+Card\s+([A-Z]{1,2})\b", line)
        if pm:
            pairs[pm.group(1)] = (pm.group(2), pm.group(3))
            if cur is not None:
                cards[cur] = "\n".join(buf).strip()
                cur = None
            continue
        if cur is not None:
            if line.strip().upper().startswith("PAIRS"):
                cards[cur] = "\n".join(buf).strip()
                cur = None
            else:
                buf.append(line)
    if cur is not None:
        cards[cur] = "\n".join(buf).strip()
    return cards, pairs


def _verdicts(ctx, cover_ids):
    cards, pairs = _parse_tournament_prompt(ctx.prompt)
    ids = list(cover_ids or sorted(pairs) or ["P01"])
    out = []
    for pid in ids:
        winner = "FIRST"
        if pid in pairs:
            a, b = pairs[pid]
            ha = hashlib.sha256(cards.get(a, a).encode("utf-8")).hexdigest()
            hb = hashlib.sha256(cards.get(b, b).encode("utf-8")).hexdigest()
            winner = "FIRST" if ha <= hb else "SECOND"  # decided by content, so both orders agree
        out.append({"pair_id": pid, "winner": winner})
    return {"verdicts": out}


def _shape_of(ctx, contract, schema):
    if ctx.template in _TEMPLATE_SHAPES:
        return _TEMPLATE_SHAPES[ctx.template]
    sid = str((schema or {}).get("$id") or "").strip().lower()
    if sid.endswith(".schema.json"):
        sid = sid[:-len(".schema.json")]
    if sid in _KNOWN_SHAPES:
        return sid
    ref = contract.get("schema")
    if isinstance(ref, str):
        stem = os.path.basename(ref.replace("\\", "/")).lower()
        for suffix in (".schema.json", ".json"):
            if stem.endswith(suffix):
                stem = stem[:-len(suffix)]
                break
        if stem in _KNOWN_SHAPES:
            return stem
    cover = contract.get("cover") if isinstance(contract.get("cover"), dict) else {}
    arr = str(cover.get("array") or "")
    props = (schema or {}).get("properties") or {}
    if arr == "verdicts" or "verdicts" in props:
        return "verdicts"
    if arr == "scores" or ("scores" in props and ctx.kind == "judge"):
        return "screen"
    if ctx.kind == "curator":
        return "merges"
    return None


def _semantic_json(ctx, contract, schema):
    shape = _shape_of(ctx, contract, schema)
    cover = contract.get("cover") if isinstance(contract.get("cover"), dict) else {}
    cover_ids = [str(i) for i in (cover.get("ids") or [])]
    if shape == "merges":
        return _merges(ctx)
    if shape == "quick-curated":
        return _quick_curated(ctx)
    if shape == "arch-drivers":
        return _arch_drivers(ctx)
    if shape == "arch-candidate":
        return _arch_candidate(ctx)
    if shape == "arch-judge":
        return _arch_judge(ctx, cover_ids)
    if shape == "arch-decisions":
        return _arch_decisions(ctx)
    if shape == "stack-verify":
        return _stack_verify(ctx)
    if shape == "findings":
        return _findings(ctx)
    if shape == "rubric":
        return _rubric(ctx)
    if shape == "redteam":
        return _redteam(ctx)
    if shape == "verdicts":
        return _verdicts(ctx, cover_ids)
    if shape == "frame-questions" and not schema:
        return {"questions": [{"id": "q1", "q": "Who has this problem most often?", "default": None}]}
    return None


def _json_value(ctx, contract, schema_ref):
    schema = None
    if schema_ref is not None and schema_ref is not True:
        try:
            schema = validate.load_schema(schema_ref, ctx.run_dir)
        except (ValueError, OSError):
            schema = None
    semantic = _semantic_json(ctx, contract, schema)
    if schema is not None:
        value = _conform(schema, semantic, ctx) if semantic is not None else _gen(schema, ctx)
    else:
        value = semantic if semantic is not None else {"result": "stub"}
    return _apply_cover(value, contract.get("cover"), schema, ctx), schema


# ---------------------------------------------------------------- contract generators

def _gen_text(ctx, c):
    parts = []
    rx = c.get("regex")
    if rx:
        hit = regex_example(rx)
        if "PONG" in str(rx):
            hit = "PONG"
        if hit:
            parts.append(hit)
    body = ctx.sentences(3, "text")
    parts.append(body)
    min_chars = c.get("min_chars", 20)
    text = "\n\n".join(parts)
    while isinstance(min_chars, int) and len(text) < min_chars:
        text += " " + ctx.sentence("pad")
    final = _final_line(ctx, c.get("final_line")) if c.get("final_line") or ctx.fact("final_line") else None
    if final:
        text += "\n\n" + final
    return text + "\n"


def _idea_block(ctx, prefix, i, cell):
    iid = "%s-%02d" % (prefix, i)
    return "\n".join([
        "### %s %s" % (iid, ctx.title(iid)),
        "- Pitch: %s" % ctx.sentence(iid + "p"),
        "- Mechanism: %s %s" % (ctx.sentence(iid + "m"), ctx.sentence(iid + "m2")),
        "- For whom / when: Night shift nurses during handover",
        "- Basis: reasoned: %s" % ctx.sentence(iid + "b"),
        "- p: 0.2",
        "- Cell: %s" % (" / ".join(cell) if cell else "general"),
        "- Fails if: %s" % ctx.sentence(iid + "f")])


def _gen_idea_blocks(ctx, c):
    prefix = str(c.get("prefix") or "S1").strip()
    need = c.get("min", 1)
    need = need if isinstance(need, int) and need > 0 else 1
    axes = ctx.fact("axes") or {}
    axes = {str(k): [str(v) for v in vals] for k, vals in axes.items() if isinstance(vals, list) and vals} \
        if isinstance(axes, dict) else {}
    cells = list(itertools.product(*axes.values())) if axes else []
    homogenized = os.environ.get("UB_STUB_HOMOGENIZED", "") not in ("", "0")
    off = ctx.cycle(max(1, len(cells)))
    blocks = ["Warm-up (not counted): three obvious answers were set aside.", ""]
    for i in range(1, need + 1):
        cell = list(cells[0 if homogenized else (off + i) % len(cells)]) if cells else []
        blocks.append(_idea_block(ctx, prefix, i, cell))
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"


def _card_value(ctx, cid, prefix):
    p = prefix.strip().lower()
    if p.startswith("title"):
        return ctx.title(cid)
    if p.startswith("prior art"):
        return "NOT LOCATED - differentiator: a weekly pilot with a manual fallback"
    if p.startswith("for whom"):
        return "Night shift nurses on the pilot ward"
    return ctx.sentence(cid + p)


def _gen_cards(ctx, c):
    ids = [str(i) for i in (c.get("ids") or [])] or ["I-001", "I-002"]
    prefixes = [str(p) for p in (c.get("lines") or ["Title:", "Problem:", "Mechanism:"])]
    out = []
    for cid in ids:
        out.append("## %s" % cid)
        for p in prefixes:
            sep = "" if p.endswith(" ") else " "
            out.append("%s%s%s" % (p, sep, _card_value(ctx, cid, p)))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _gen_json(ctx, c):
    value, _schema = _json_value(ctx, c, c.get("schema"))
    return json.dumps(value, indent=1, ensure_ascii=True) + "\n"


def _heading_line(h):
    h = str(h).strip()
    return h if h.startswith("#") else "## " + h


def _section_body(ctx, heading, n):
    text = ctx.sentences(2, "sec%d" % n)
    low = heading.lower()
    if ctx.template == "P-GROUND" and "facts" in low:
        text += ("\n\n- FACT (stub): shift swaps are arranged by phone today.\n\n"
                 "```python\n# %s: repository code excerpt\n```" % _CODE_MARKER)
    if "container view" in low:
        text += "\n\n```mermaid\nflowchart LR\n  web[\"Web app\"] --> api[\"API service\"]\n  api --> db[\"Database\"]\n```"
    return text


def _gen_sections(ctx, c):
    out = []
    for n, h in enumerate(c.get("headings") or []):
        line = _heading_line(h)
        out.append(line)
        out.append("")
        out.append(_section_body(ctx, line, n))
        out.append("")
    if not out:
        out = [ctx.sentences(3, "sections"), ""]
    tail = c.get("json_tail")
    if tail:
        ref = tail if isinstance(tail, (dict, str)) else None
        tail_contract = {"schema": ref} if ref is not None else {}
        value, _s = _json_value(ctx, tail_contract, ref)
        if ctx.template == "ARCH-CANDIDATE" and not isinstance(value, dict):
            value = _arch_candidate(ctx)
        out.append("```json")
        out.append(json.dumps(value, indent=1, ensure_ascii=True))
        out.append("```")
        out.append("")
    if c.get("final_line") or ctx.fact("final_line"):
        final = _final_line(ctx, c.get("final_line"))
        if final:
            out.append(final)
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------- files (FILE protocol)

def _words_to(text, target, ctx, salt):
    """Append sentences until the text has at least `target` words."""
    while len(text.split()) < target:
        text += " " + ctx.sentence(salt)
    return text


def _mermaid(kind, conts, exts=()):
    lines = ["```mermaid"]
    if kind == "C4Container":
        lines.append("C4Container")
        lines.append("  title Containers of the shift swap service")
        lines.append("  Person(nurse, \"Nurse\", \"Requests swaps\")")
        for cid, name, tech in conts:
            lines.append("  Container(%s, \"%s\", \"%s\", \"%s\")" % (_slug(cid).replace("-", ""), name, tech, cid))
        for e in exts:
            lines.append("  System_Ext(%s, \"%s\", \"external system\")" % (_slug(e).replace("-", ""), e))
    elif kind == "flowchart":
        lines.append("flowchart LR")
        prev = "nurse"
        lines.append("  nurse[\"Nurse\"]")
        for cid, name, _tech in conts:
            node = _slug(cid).replace("-", "")
            lines.append("  %s[\"%s %s\"]" % (node, cid, name))
            lines.append("  %s --> %s" % (prev, node))
            prev = node
        for e in exts:
            node = _slug(e).replace("-", "")
            lines.append("  %s[\"%s\"]" % (node, e))
            lines.append("  %s --> %s" % (prev, node))
    elif kind == "sequenceDiagram":
        lines.append("sequenceDiagram")
        names = [_slug(c[0]).replace("-", "") for c in conts] or ["api"]
        lines.append("  participant nurse as Nurse")
        for node in names[:3]:
            lines.append("  participant %s" % node)
        lines.append("  nurse->>%s: request" % names[0])
        if len(names) > 1:
            lines.append("  %s->>%s: store" % (names[0], names[1]))
            lines.append("  %s-->>%s: stored" % (names[1], names[0]))
        lines.append("  %s-->>nurse: confirmed" % names[0])
    elif kind == "erDiagram":
        lines.append("erDiagram")
        lines.append("  NURSE ||--|| SWAP_REQUEST : creates")
        lines.append("  SHIFT |o--|| SWAP_REQUEST : covers")
    else:
        lines.append(kind)
        lines.append("  a --> b")
    lines.append("```")
    return "\n".join(lines)


def _table(header, rows):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    for r in rows:
        out.append("| " + " | ".join(str(x) for x in r) + " |")
    return "\n".join(out)


def _containers_md(ctx):
    conts, exts, qgs = _containers(ctx), _ext_ids(ctx), _qg_ids(ctx)
    qas = _qas_ids(ctx)
    parts = ["# Containers", "", "## Containers", "", _mermaid("C4Container", conts, exts), "",
             _mermaid("flowchart", conts, exts), "",
             _table(["id", "name", "technology", "responsibility", "data owned", "interface"],
                    [(cid, name, tech, "Handles its part of the swap flow", "Operational records", "HTTPS JSON")
                     for cid, name, tech in conts]), "",
             "External systems used: " + ", ".join(exts) + ".", "",
             "## How each quality goal is met", "",
             _table(["QG", "mechanism", "containers", "QAS", "expected response"],
                    [(q, "Named mechanism for this goal", conts[n % len(conts)][0], qas[n % len(qas)],
                      "Meets the scenario measure") for n, q in enumerate(qgs)])]
    return "\n".join(parts) + "\n"


def _runtime_md(ctx):
    conts = _containers(ctx)
    ids = ", ".join(c[0] for c in conts)
    return "\n".join([
        "# Runtime", "", "## F-1 Request a swap", "", ctx.sentence("f1") + " Containers involved: " + ids + ".", "",
        _mermaid("sequenceDiagram", conts), "",
        "## F-2 Failure and recovery: notification relay down", "",
        ctx.sentence("f2") + " The request stays queued and is retried; the nurse sees a pending state.", "",
        _mermaid("sequenceDiagram", conts[:2]), ""])


def _data_model_md(ctx):
    conts = _containers(ctx)
    owner = conts[0][0]
    return "\n".join([
        "# Data model", "", _mermaid("erDiagram", conts), "", "## Entities", "",
        _table(["entity", "fields", "owner container", "retention", "PII"],
               [("Nurse", "id, name, ward", owner, "while employed", "yes"),
                ("Shift", "id, ward, start, end", owner, "two years", "no"),
                ("Swap request", "id, from, to, state", owner, "two years", "no")]), ""])


def _long_md(ctx, title, headings, salt, words=150, extra=""):
    parts = ["# " + title, ""]
    for n, h in enumerate(headings):
        parts.append(h)
        parts.append("")
        parts.append(ctx.sentences(2, "%s%d" % (salt, n)))
        parts.append("")
    if extra:
        parts.append(extra)
        parts.append("")
    text = "\n".join(parts)
    # count words the way lints.word_count does (tokens with a word character; table pipes and heading marks
    # are not words), with a small margin, so stub packages pass the 120-word rule (A7)
    count = len([w for w in text.split() if re.search(r"\w", w)])
    if count < words:
        text += "\n" + _words_to("", words - count, ctx, salt).strip() + "\n"
    return text.rstrip() + "\n"


def _cost_md(ctx):
    extra = "\n".join([
        "## Assumptions", "",
        _table(["id", "assumption", "value", "source"],
               [("CA-1", "Active users in the pilot", "one ward", "[ASSUMPTION: pilot size]"),
                ("CA-2", "Hosting tier", "smallest managed tier", "[ASSUMPTION: vendor pricing]")]), "",
        "## Monthly run cost", "",
        _table(["item", "MVP", "10x", "100x"], [("Hosting", "low", "medium", "high")]), "",
        "## Per active user", "", ctx.sentence("pau"), "",
        "## LLM and API costs", "", "No model calls in the product path.", "",
        "## Build cost", "", "A small team over a few weeks [ESTIMATE: few weeks; stub basis].", "",
        "## Sensitivity", "", "Plus or minus half on hosting changes the total only modestly."])
    return _long_md(ctx, "Cost model", [], "cost", 150, extra)


def _deferred_md(ctx):
    return "\n".join(["# Deferred decisions", "",
                      _table(["decision", "why deferred", "trigger", "decide by"],
                             [("Multi hospital tenancy", "Not needed for the pilot", "A second hospital signs",
                               "Milestone 2")]), ""])


def _decisions_json(ctx):
    return json.dumps(_arch_decisions(ctx), indent=1, ensure_ascii=True) + "\n"


def _openapi_yaml(ctx):
    return "\n".join(["openapi: 3.0.3", "info:", "  title: Shift swap API", "  version: 1.0.0", "paths:",
                      "  /swaps:", "    post:", "      summary: Request a swap", "      responses:",
                      "        '201':", "          description: Created", ""])


def _frame_md(ctx):
    crits = ["Value", "Feasibility", "Fit", "Distinctiveness", "Evidence"]
    heads = ["## Job statement", "## Problem", "## Audience / boundary", "## Success looks like",
             "## Hard constraints", "## Soft constraints", "## Non-goals", "## Decision ledger", "## Premises",
             "## Kill condition for the whole effort"]
    parts = ["# FRAME: stub frame", ""]
    for n, h in enumerate(heads):
        parts += [h, "", "ASSUMED: " + ctx.sentence("frame%d" % n), ""]
    parts += ["## Criteria", ""] + ["- %s: anchors 1 weak, 3 fair, 5 strong" % c for c in crits] + [""]
    parts += ["## Kill rules", "", "K1-K6 as in the skill.", "", "## Axes", ""]
    for name, vals in _DEFAULT_AXES.items():
        parts.append("- %s: %s" % (name, ", ".join(vals)))
    parts += ["", "## Strategy plan", "", "S1-S5 as seated by the engine.", "",
              "## Mode, privacy, budget", "", "As recorded in run.json.", ""]
    return "\n".join(parts)


def _proposal_heading(ctx, num):
    for h in ctx.fact("sections") or []:
        m = re.match(r"^\s*#*\s*(\d+)\.", str(h))
        if m and int(m.group(1)) == num:
            return _heading_line(h)
    if num == 6 and (ctx.run_meta().get("build_type") == "approach"):
        return "## 6. Approach"
    return _PROPOSAL_HEADINGS.get(num, "## %d. Section" % num)


def _proposal_section(ctx, num, heading):
    parts = [heading, ""]
    srcs = [str(s) for s in (ctx.fact("source_ids") or [])]
    adrs = [str(a) for a in (ctx.fact("adr_numbers") or [])]
    rids = [str(r) for r in (ctx.fact("r_ids") or [])]
    if num == 1:
        parts.append(ctx.sentences(4, "exec"))
    elif num == 2:
        parts.append(ctx.sentences(2, "prob") + (" Evidence is recorded in the context file [%s]." % srcs[0]
                                                 if srcs else ""))
    elif num == 6:
        parts.append(ctx.sentences(2, "arch"))
        if adrs:
            parts.append("")
            parts.append("Top decisions: " + ", ".join("ADR-%04d" % int(a) if str(a).isdigit() else str(a)
                                                       for a in adrs[:3]) + ".")
    elif num == 8:
        parts.append("Milestone 0: run the pre-registered probe first; its kill criterion decides whether the "
                     "later milestones start. " + ctx.sentence("road"))
        parts.append("")
        parts.append("Milestone 1: ship the pilot to one ward. Exit criterion: the pilot ward uses it weekly.")
    elif num == 11:
        parts.append(ctx.sentences(2, "risk") + (" Top risks: " + ", ".join(rids[:3]) + "." if rids else ""))
    elif num == 13:
        parts.append("- Which ward runs the pilot first? Owner: Product lead. Decide by: Milestone 0.")
        parts.append("- Which messaging gateway is approved? Owner: Tech lead. Decide by: Milestone 1.")
    else:
        parts.append(ctx.sentences(3, "s%d" % num))
    return "\n".join(parts).rstrip() + "\n"


def _one_pager(ctx):
    parts = ["# One-pager", ""]
    for h in _ONE_PAGER_HEADINGS:
        parts += [h, ""]
        if h == "## Architecture at a glance":
            parts += [_mermaid("flowchart", _containers(ctx)[:3]), ""]
        elif h == "## Top risks":
            parts += ["- Adoption stalls. Test: a two week pilot.", "- Approvals lag. Test: shadow the charge nurse.",
                      "- Data access blocked. Test: ask the IdP team first.", ""]
        else:
            parts += [ctx.sentence("one" + h), ""]
    return "\n".join(parts).rstrip() + "\n"


def _file_content(ctx, rel):
    low = rel.lower()
    base = low.rsplit("/", 1)[-1]
    if base == "criteria.json":
        return json.dumps({"Value": 30, "Feasibility": 25, "Fit": 20, "Distinctiveness": 15, "Evidence": 10},
                          indent=1) + "\n"
    if base == "01_frame.md":
        return _frame_md(ctx)
    if base == "context.proposed.md":
        return "# Proposed terms\n\n**Swap request** [NEW]\nA request to trade one shift.\n_Avoid_: trade ticket\n"
    if low.endswith("chosen/containers.md") or base == "containers.md":
        return _containers_md(ctx)
    if base == "runtime.md":
        return _runtime_md(ctx)
    if base == "data-model.md":
        return _data_model_md(ctx)
    if base == "api.md":
        return _long_md(ctx, "API", ["## Endpoints", "## Errors", "## Versioning"], "api", 60)
    if base in ("openapi.yaml", "openapi.yml"):
        return _openapi_yaml(ctx)
    if base == "cli.md":
        return _long_md(ctx, "CLI", ["## Commands", "## Exit codes"], "cli", 60)
    if base == "deployment.md":
        return _long_md(ctx, "Deployment", ["## Environments", "## Hosting", "## CI/CD", "## Infrastructure as code",
                                            "## Observability", "## Backup and DR"], "deploy", 150,
                        "Recovery targets: RTO four hours, RPO one hour.")
    if base == "security-privacy.md":
        return _long_md(ctx, "Security and privacy", ["## Data classification", "## Authentication and authorization",
                                                      "## STRIDE-lite", "## PII handling", "## Compliance scope"],
                        "sec", 150)
    if base == "cost-model.md":
        return _cost_md(ctx)
    if base == "deferred.md":
        return _deferred_md(ctx)
    if base == "decisions.json":
        return _decisions_json(ctx)
    if base == "resolution.md":
        return "# Resolution\n\n" + _table(["finding", "status", "reason"],
                                           [("F-01", "DEFERRED", "Low severity; tracked for the next pass")]) + "\n"
    if base == "approach.md":
        return _long_md(ctx, "Approach", ["## Hypotheses and rival explanations", "## Design", "## Measures",
                                          "## Channels and assets", "## Timeline", "## Risks"], "appr", 150)
    if base == "one-pager.md":
        return _one_pager(ctx)
    if base == "prfaq.md":
        return _long_md(ctx, "PR/FAQ", ["## Press release", "## FAQ"], "prfaq", 120)
    m = re.match(r"^(\d{1,2})\.md$", base)
    if m and "sections" in low:
        num = int(m.group(1))
        return _proposal_section(ctx, num, _proposal_heading(ctx, num))
    if low.endswith(".json"):
        return json.dumps({"stub": True}, indent=1) + "\n"
    if low.endswith((".yaml", ".yml")):
        return "stub: true\n"
    if low.endswith(".mmd"):
        return "flowchart LR\n  a --> b\n"
    return _long_md(ctx, base.rsplit(".", 1)[0], ["## Summary"], "gen" + base, 40)


def _ensure_rules(content, rules):
    if not isinstance(rules, dict):
        return content
    for h in rules.get("headings") or []:
        line = _heading_line(h)
        if not re.search(r"(?im)^" + re.escape(line.strip()), content):
            content = content.rstrip() + "\n\n" + line + "\n\nAdded to satisfy the required outline.\n"
    for kind in rules.get("mermaid") or []:
        if not re.search(r"```mermaid\s*\n\s*" + re.escape(str(kind)) + r"\b", content):
            content = content.rstrip() + "\n\n```mermaid\n%s\n  a --> b\n```\n" % kind \
                if str(kind) in ("flowchart", "graph") else \
                content.rstrip() + "\n\n```mermaid\n%s\n```\n" % kind
    return content


def _glob_name(pattern):
    name = str(pattern).replace("**/", "").replace("**", "stub")
    name = name.replace("*", "stub").replace("?", "x")
    if not re.search(r"\.(md|ya?ml|json|mmd)$", name):
        name = name.rstrip("/") + "/stub.md"
    return name.lstrip("/")


def _gen_files(ctx, c):
    required = [str(r) for r in (c.get("required") or [])]
    allowed = [str(a) for a in (c.get("allowed") or [])]
    per_file = c.get("per_file") if isinstance(c.get("per_file"), dict) else {}
    names = list(required)
    if not names:
        literal = [a for a in allowed if not re.search(r"[*?\[]", a)]
        names = literal[:1] or ([_glob_name(allowed[0])] if allowed else ["stub.md"])
    out = []
    for rel in names:
        content = _ensure_rules(_file_content(ctx, rel), per_file.get(rel))
        out.append("=== FILE: %s ===" % rel)
        out.append(content.rstrip("\n"))
        out.append("=== END FILE ===")
    status = {"status": "complete", "assumptions": ["Stub output: every fact is an assumption."],
              "open_questions": [], "reason": ""}
    out.append("=== STATUS ===")
    out.append(json.dumps(status, ensure_ascii=True))
    out.append("=== END STATUS ===")
    return "\n".join(out) + "\n"


_GENERATORS = {"text": _gen_text, "idea-blocks": _gen_idea_blocks, "json": _gen_json, "sections": _gen_sections,
               "cards": _gen_cards, "files": _gen_files}


def _maybe_fail(job_id):
    rx = os.environ.get("UB_STUB_FAIL", "")
    if rx:
        try:
            hit = re.search(rx, job_id)
        except re.error:
            hit = rx == job_id
        if hit:
            raise StubFailure("UB_STUB_FAIL matched job %s" % job_id)


def _maybe_delay():
    raw = os.environ.get("UB_STUB_DELAY_S", "")
    try:
        delay = float(raw) if raw else 0.0
    except ValueError:
        delay = 0.0
    if delay > 0:
        time.sleep(min(delay, 3600.0))


def respond(job, prompt_text):
    """Return raw model-like output text that satisfies job["contract"] (and FILE protocol + STATUS for "files").

    Deterministic: seeded by job["id"]. Reads optional job["stub"] facts. Honors UB_STUB_FAIL (raise StubFailure for
    matching job ids), UB_STUB_DELAY_S (sleep), UB_STUB_HOMOGENIZED (curator puts > 25% of ideas in one cluster)."""
    ctx = _Ctx(job, prompt_text)
    _maybe_fail(ctx.id)
    _maybe_delay()
    contract = ctx.job.get("contract") if isinstance(ctx.job.get("contract"), dict) else {"type": "text"}
    gen = _GENERATORS.get(str(contract.get("type") or "text"), _gen_text)
    return gen(ctx, contract)
