<!-- ub-template: INDEX-HTML v1 kind=doc -->
<!DOCTYPE html>
<html lang="{{LANG}}">
<head>
<meta charset="utf-8">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src {{MERMAID_CDN}} 'sha256-LbTTbeJ1nOEHczz05HqnUWIxopbk8WqbJpctqBGMgkc='; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'">
<meta name="referrer" content="no-referrer">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="generator" content="ultimate-brainstorm">
<title>{{TITLE}}</title>
<style>
:root {
  --bg: #ffffff; --fg: #1d1f23; --muted: #5b6270; --line: #d9dde3; --card: #f6f7f9;
  --accent: #2458c6; --badge-bg: #fff3cd; --badge-fg: #6a4b00; --code: #f0f2f5;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #15171a; --fg: #e6e8eb; --muted: #a2a9b4; --line: #30343a; --card: #1e2125;
    --accent: #7ea6ff; --badge-bg: #3d3314; --badge-fg: #f3d98b; --code: #23272c;
  }
}
* { box-sizing: border-box; }
html { -webkit-text-size-adjust: 100%; }
body {
  margin: 0; background: var(--bg); color: var(--fg); line-height: 1.55; font-size: 16px;
  font-family: system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
}
a { color: var(--accent); }
.wrap { display: grid; grid-template-columns: 1fr; gap: 28px; padding: 24px; max-width: 80rem; margin: 0 auto; }
@media (min-width: 960px) { .wrap { grid-template-columns: 16rem minmax(0, 1fr); } }
nav.toc { font-size: 0.9rem; }
nav.toc a { display: block; padding: 2px 0; color: var(--muted); text-decoration: none; }
nav.toc a:hover { color: var(--accent); }
nav.toc ul { list-style: none; padding-left: 0; margin: 8px 0; }
@media (min-width: 960px) {
  nav.toc { position: sticky; top: 16px; align-self: start; max-height: calc(100vh - 32px); overflow: auto; }
}
main { min-width: 0; }
.cover { padding: 8px 0 20px; border-bottom: 1px solid var(--line); }
.cover h1 { margin: 0 0 8px; font-size: 2rem; line-height: 1.2; }
.cover .pitch { margin: 0 0 12px; font-size: 1.15rem; color: var(--muted); max-width: 60rem; }
.cover .date { color: var(--muted); font-size: 0.9rem; margin-left: 8px; }
.badge {
  display: inline-block; padding: 2px 10px; border-radius: 999px; font-weight: 600; font-size: 0.85rem;
  background: var(--badge-bg); color: var(--badge-fg); letter-spacing: 0.02em;
}
.card { background: var(--card); border: 1px solid var(--line); border-radius: 10px; padding: 16px 20px;
  margin: 16px 0 24px; }
.card.adr { margin: 12px 0; }
h2 { margin-top: 2.2rem; padding-top: 0.4rem; border-top: 1px solid var(--line); }
h3 { margin-top: 1.6rem; }
table { border-collapse: collapse; width: 100%; margin: 12px 0; display: block; overflow-x: auto; font-size: 0.92rem; }
th, td { border: 1px solid var(--line); padding: 6px 8px; text-align: left; vertical-align: top; }
th { background: var(--card); }
pre, code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 0.88rem; }
pre { background: var(--code); padding: 12px; border-radius: 8px; overflow-x: auto; }
pre.mermaid { background: var(--card); text-align: center; }
blockquote { margin: 12px 0; padding: 4px 16px; border-left: 4px solid var(--line); color: var(--muted); }
.footer { color: var(--muted); font-size: 0.85rem; padding: 24px; text-align: center; border-top: 1px solid var(--line); }
@media print {
  nav.toc { display: none; }
  .wrap { display: block; padding: 0; }
  #sections > h2, #architecture > h2, #appendices > h2 { break-before: page; page-break-before: always; }
  h2 { border-top: none; }
  a { color: inherit; text-decoration: none; }
  pre, table, .card { break-inside: avoid; }
}
</style>
</head>
<body>
<div class="wrap">
<nav class="toc" id="toc" aria-label="Contents"><strong>Contents</strong>
{{TOC}}
</nav>
<main>
<section class="cover" id="cover">
<h1>{{TITLE}}</h1>
<p class="pitch">{{PITCH}}</p>
<p><span class="badge" id="status-badge">{{BADGE}}</span> <span class="date">{{DATE}}</span></p>
</section>
<section class="card" id="one-pager">
{{ONE_PAGER}}
</section>
{{BODY}}
</main>
</div>
<footer class="footer">Generated by ultimate-brainstorm. Diagrams load one pinned script from cdn.jsdelivr.net,
checked against its hash; offline or blocked, their source text stays visible.</footer>
<script src="{{MERMAID_CDN}}" integrity="sha384-EOXBFmc3gx5mb+vn0vPvvGqACToJD24hhacX5Yx+8NUUQrHIle/Qi5Bg9o3zKwW2" crossorigin="anonymous"></script>
<script>
try {
  if (window.mermaid) {
    var dark = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
    window.mermaid.initialize({ startOnLoad: false, securityLevel: "strict", theme: dark ? "dark" : "default" });
    window.mermaid.run({ querySelector: "pre.mermaid" }).catch(function () {});
  }
} catch (e) { /* offline, blocked or not the pinned file: the diagram source stays visible */ }
</script>
</body>
</html>
