#!/bin/sh
# ultimate-brainstorm launcher: {{NAME}}
# Generated by install/install.py from profiles/launcher.sh.tpl (kit {{VERSION}}). Do not edit; re-run the installer.
# It runs: python <UB_HOME>/kit/profiles/launch.py {{LAUNCH_ARGS}} -- <your arguments>
# No secret is stored here; API keys are read from your environment at launch time.
if [ -z "${UB_HOME:-}" ]; then
  UB_HOME='{{UB_HOME_SH}}'
fi
export UB_HOME
exec '{{PY_SH}}' "$UB_HOME/kit/profiles/launch.py" {{LAUNCH_ARGS}} -- "$@"
