@echo off
rem ultimate-brainstorm launcher: {{NAME}}
rem Generated by install/install.py from profiles/launcher.cmd.tpl (kit {{VERSION}}). Do not edit; re-run the installer.
rem It runs: python <UB_HOME>\kit\profiles\launch.py {{LAUNCH_ARGS}} -- <your arguments>
rem No secret is stored here; API keys are read from your environment at launch time.
setlocal
if not defined UB_HOME set "UB_HOME={{UB_HOME_WIN}}"
"{{PY_WIN}}" "%UB_HOME%\kit\profiles\launch.py" {{LAUNCH_ARGS}} -- %*
exit /b %ERRORLEVEL%
