@echo off
rem ultimate-brainstorm launcher: {{NAME}}
rem Generated by install/install.py from profiles/launcher.cmd.tpl (kit {{VERSION}}). Do not edit; re-run the installer.
rem It runs: python <UB_HOME>\kit\profiles\launch.py {{LAUNCH_ARGS}} -- <your arguments>
rem No secret is stored here; API keys are read from your environment at launch time.
setlocal
rem cmd.exe reads each line in the console code page. When a path below holds a non-ASCII character, the lines
rem are read as UTF-8 (code page 65001), and the code page is restored before the launcher exits.
set "_ubcp="
if "{{UTF8}}"=="1" for /f "tokens=2 delims=:." %%c in ('chcp') do set "_ubcp=%%c"
if "{{UTF8}}"=="1" chcp 65001 >nul
if not defined UB_HOME set "UB_HOME={{UB_HOME_WIN}}"
"{{PY_WIN}}" "%UB_HOME%\kit\profiles\launch.py" {{LAUNCH_ARGS}} -- %*
set "_ubrc=%ERRORLEVEL%"
if defined _ubcp chcp %_ubcp% >nul
exit /b %_ubrc%
