"""Privacy and evidence guards (KIT_SPEC 6.7, 6.8).

- vendor gating: which families a run may use, and the job.privacy stamp the adapter re-checks (5.6);
- code stripping: FACTS for other vendors keep file paths but drop file contents and fenced code; A2 terms keep only
  those marked "proposed";
- seed-leak check: a generator/frame/ground prompt may not contain a 20+ character line from the seed sections Ideas,
  Primary idea or Obvious (the curator is the only job allowed to see seeds);
- pool-leak check: a generator prompt may not contain a 20+ character idea title from any pool file;
- origin-label check: judge prompts may not contain alias IDs or origin words.
"""

import glob
import os
import re

from .. import textio
from . import VENDORS, base_family, vendor_of

SEED_SECTIONS = ("Ideas", "Primary idea", "Obvious")
MIN_LEAK_CHARS = 20
ALIAS_RE = re.compile(r"\b(S\d+|G\d+|R\d+|L\d+|H|HP|H2|IMP|S1R)-\d+\b")
ORIGIN_WORDS_RE = re.compile(r"(origin:|strategy:|generated by)", re.I)
_FENCE_RE = re.compile(r"^[ \t]*(`{3,}|~{3,})[^\n]*\n.*?^[ \t]*\1[ \t]*$", re.M | re.S)


class PolicyBlock(Exception):
    """A dispatch refused by an evidence or privacy rule (becomes a BLOCKED card naming the rule)."""

    def __init__(self, rule, message, job_id=None):
        Exception.__init__(self, message)
        self.rule = rule
        self.job_id = job_id


# ---------------------------------------------------------------- vendors

def allowed_vendors(host_family, families, vendors_ok):
    """privacy.allowed_vendors: every available family's vendor, or only the host vendor when vendors = no."""
    if not vendors_ok:
        return [VENDORS.get(host_family, host_family)]
    return sorted({VENDORS.get(f, f) for f in families} | {VENDORS.get(host_family, host_family)})


def job_privacy(state, family, tools, cwd):
    """The job.privacy stamp (4.4): vendor_ok, web_ok, code_ok."""
    priv = state.get("privacy") or {}
    host_vendor = vendor_of((state.get("host") or {}).get("family"))
    vend = vendor_of(family)
    allowed = priv.get("allowed_vendors") or []
    vendor_ok = (not allowed) or vend in allowed
    web_ok = ("web" not in (tools or "none")) or bool(priv.get("web", True))
    code_ok = cwd != "repo" or vend == host_vendor or bool(priv.get("code", False))
    return {"vendor_ok": bool(vendor_ok), "web_ok": bool(web_ok), "code_ok": bool(code_ok)}


def needs_code_strip(state, family):
    """True when prompts for this family must drop code (privacy code = no and a different vendor than the host)."""
    priv = state.get("privacy") or {}
    if priv.get("code", False):
        return False
    return vendor_of(family) != vendor_of((state.get("host") or {}).get("family"))


# ---------------------------------------------------------------- code stripping (6.8)

def strip_code(text):
    """Drop fenced code blocks and indented code lines; keep everything else (including file paths)."""
    if not text:
        return text
    out = _FENCE_RE.sub("[code omitted: privacy code = no]", textio.normalize_newlines(text))
    lines = []
    in_indented = False
    for ln in out.split("\n"):
        if (ln.startswith("    ") or ln.startswith("\t")) and ln.strip() and not ln.lstrip().startswith(("-", "*")):
            if not in_indented:
                lines.append("    [code omitted: privacy code = no]")
            in_indented = True
            continue
        in_indented = False
        lines.append(ln)
    return "\n".join(lines)


def filter_a2_terms(a2_text):
    """Keep the A2 intro line(s) and only the terms marked 'proposed'."""
    if not a2_text:
        return a2_text
    out = []
    for ln in a2_text.split("\n"):
        s = ln.strip()
        is_term = s.startswith("**") or s.startswith("- **") or s.startswith("* **")
        if is_term and "proposed" not in s.lower():
            continue
        out.append(ln)
    return "\n".join(out)


def filter_facts(facts_text, state, family):
    """FACTS text as a given family may see it."""
    if not needs_code_strip(state, family):
        return facts_text
    text = strip_code(facts_text)
    m = re.search(r"^##\s*A2\b.*?(?=^##\s|\Z)", text, re.M | re.S)
    if m:
        text = text[:m.start()] + filter_a2_terms(m.group(0)) + text[m.end():]
    return text


# ---------------------------------------------------------------- seed leak (6.7 rule 1)

def _section(text, heading):
    m = re.search(r"^##\s*" + re.escape(heading) + r"[^\n]*\n(.*?)(?=^##\s|\Z)", text, re.M | re.S | re.I)
    return m.group(1) if m else ""


def seed_lines(run_dir):
    """Lines of 20+ characters from the seed sections Ideas, Primary idea, Obvious of every seeds file."""
    lines = []
    for path in sorted(glob.glob(os.path.join(run_dir, "00_HUMAN_SEEDS*.md")) +
                       glob.glob(os.path.join(run_dir, "00b_HUMAN_ROUND2.md"))):
        try:
            text = textio.read_text(path)
        except OSError:
            continue
        for sec in SEED_SECTIONS:
            for ln in _section(text, sec).split("\n"):
                s = _norm(re.sub(r"^\s*(?:[-*]|\d+[.)])\s*", "", ln))
                if len(s) >= MIN_LEAK_CHARS:
                    lines.append(s)
    return lines


def _norm(s):
    return " ".join(str(s).split()).strip()


def check_seed_leak(prompt_text, run_dir, job_id=None, allow=()):
    """allow: texts the prompt may legitimately carry (the run topic; the proposal-mode idea)."""
    norm = _norm(prompt_text).lower()
    allowed = [_norm(a).lower() for a in allow if a]
    for s in seed_lines(run_dir):
        low = s.lower()
        if any(low in a for a in allowed):
            continue
        if low in norm:
            raise PolicyBlock("seed_leak_check",
                              "Human-first rule: the prompt for %s contains a line from your seeds (%r...). Seeds "
                              "may only reach the curator." % (job_id or "a job", s[:40]), job_id)


# ---------------------------------------------------------------- pool leak (6.7 rule 3)

_TITLE_RE = re.compile(r"^#{2,4}\s*[A-Z][A-Za-z0-9]*-\d+[:.)]?\s+(.+?)\s*$", re.M)


def pool_titles(run_dir):
    titles = []
    for path in glob.glob(os.path.join(run_dir, "pool", "*.md")):
        try:
            text = textio.read_text(path)
        except OSError:
            continue
        for m in _TITLE_RE.finditer(text):
            t = _norm(m.group(1))
            if len(t) >= MIN_LEAK_CHARS:
                titles.append(t)
    return titles


def check_pool_leak(prompt_text, run_dir, job_id=None, exclude_files=()):
    norm = _norm(prompt_text).lower()
    for t in pool_titles(run_dir):
        if t.lower() in norm:
            raise PolicyBlock("pool_leak_check",
                              "Isolation rule: the generator prompt for %s contains an idea title from pool/ (%r...)."
                              % (job_id or "a job", t[:40]), job_id)


# ---------------------------------------------------------------- origin labels (6.7 rule 6)

def check_origin_labels(prompt_text, job_id=None):
    m = ALIAS_RE.search(prompt_text or "")
    if m:
        raise PolicyBlock("origin_label_check",
                          "Debiasing rule: the judge prompt for %s contains the alias ID %s, which reveals an idea's "
                          "origin." % (job_id or "a job", m.group(0)), job_id)
    m = ORIGIN_WORDS_RE.search(prompt_text or "")
    if m:
        raise PolicyBlock("origin_label_check",
                          "Debiasing rule: the judge prompt for %s contains %r, which reveals an idea's origin."
                          % (job_id or "a job", m.group(0)), job_id)


def run_checks(prompt_text, checks, run_dir, job_id=None, allow=()):
    """Apply the named checks ('seed_leak', 'pool_leak', 'origin_label') to a prompt."""
    for name in checks or ():
        if name in ("seed_leak", "seed_leak_check"):
            check_seed_leak(prompt_text, run_dir, job_id, allow=allow)
        elif name in ("pool_leak", "pool_leak_check"):
            check_pool_leak(prompt_text, run_dir, job_id)
        elif name in ("origin_label", "origin_label_check"):
            check_origin_labels(prompt_text, job_id)


def family_vendor(label):
    return VENDORS.get(base_family(label), base_family(label))
