"""Phase L, LD-privacy (KIT_SPEC 6.7 rule 6 and 6.8).

The origin-label check refuses only the kit's own label syntax: a label word with ':' or '=' ('Origin: gpt', also with
markdown emphasis or code marks), '(written by human)', or a bare 'generated by' / 'written by' before a family label
or vendor. An origin name or an alias prefix counts only as the whole value, and only the prefixes of this run's alias
IDs, which keep only the kit's alias shapes (so COVID-19 or GPT-4 in an imported heading is no alias ID). Ordinary
prose ('Storage strategy: S3 buckets', 'written by human volunteers', 'the origin S3 bucket') never blocks a judge step.

The A2 filter drops the wrapped lines of a dropped term (a column-0 line right under it) and the body under a heading
that names CONTEXT.md, and a bold-led item or table row nested under a kept [proposed] term needs its own mark.
"""

import json
import os
import sys
import unittest
from unittest import mock

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "fixtures", "engine"))
import engine_testlib as tl  # noqa: E402

import stubs  # noqa: E402  (tests/harness, put on sys.path by engine_testlib)
from ublib.engine import builders, registry  # noqa: E402
from ublib.engine import privacy as pv  # noqa: E402

ALIASES = ["S2-01", "G1-02", "H-01", "L1-03"]  # prefixes S2, G1, H, L1
ORDINARY = (
    # hunt: origin-label check blocks judge steps on ordinary words (a label word before an alias prefix or an
    # origin name that starts a longer value)
    "Storage strategy: S3 buckets with lifecycle rules.", "Caching strategy: L2 cache in front of Postgres.",
    "Backup strategy: R2 with nightly snapshots.", "GC strategy: G1 with a 200 ms pause goal.",
    "Printer family: HP LaserJet on each ward.", "Test database family: H2 in memory.",
    "Moderation strategy: human review of flagged swaps.", "Escalation strategy: human agents take over at night.",
    "Data origin: unknown for 12% of rows.", "Rotas written by human coordinators today.",
    "Pricing strategy: evolved from the pilot.", "Country of origin: import records from customs.",
    "Growth strategy: import substitution.", "CloudFront in front of the origin: S3 bucket per region.",
    # review: 'written by human', 'origin import' (no ':' or '=' after the label word)
    "handwritten letters written by human volunteers", "rules-of-origin import declarations",
    "news summaries written by human editors", "country of origin (import or local)",
    "essays written by human authors", "Records how a pricing strategy evolved.", "Data origin unknown.",
    "a family import business", "family unknown", "the country of origin\nImport duties apply",
    "CloudFront in front of the origin S3 bucket", "an origin R2 bucket", "a strategy L4 load balancers cannot express",
    # a prefix that belongs to no idea of this run reveals nothing
    "Backup strategy: R2.",
)
LABELS = (
    "Origin: human.", "Origin: human", "(origin: human-mixed)", "Origin: ai-mixed;", "origin=import", "Family: gpt",
    "strategy: S2", "Strategy = G1", "Strategy: H.", "(written by human)", "(generated by gpt)",
    "written by anthropic", "generated by Claude", "written by kimi-alt",
    # the line 03_POOL.md writes, and the tournament result's '(origin: X)'
    "- I-004 Night board - p Mechanism: m Key: k. Origin: human-mixed. Cell: a / b. Aliases: x.",
    "1. I-002  7.5  (origin: gpt)",
    # NEW-K-JE-1: markdown emphasis or code spans around the label or the value
    "**Origin:** gpt", "Origin: `gpt`", "**Strategy:** S2", "Origin: **human**", "Generated by: `claude`",
    "*origin*: _human_.", "- **Origin**: `human-mixed`", "(**origin:** evolved)",
)


class OriginLabelShapeTests(unittest.TestCase):
    def test_ordinary_prose_passes(self):
        for text in ORDINARY:
            pv.check_origin_labels(text, "6.2-claude", aliases=ALIASES, labels=["claude", "gpt"])

    def test_labels_are_refused_also_with_markdown(self):
        for text in LABELS:
            with self.assertRaises(pv.PolicyBlock, msg=text) as cm:
                pv.check_origin_labels(text, "6.2-claude", aliases=ALIASES, labels=["claude", "gpt"])
            self.assertEqual(cm.exception.rule, "origin_label_check")

    def test_only_this_runs_prefixes_are_label_values(self):
        pv.check_origin_labels("Backup strategy: R2.", "x", aliases=["S2-01"])
        with self.assertRaises(pv.PolicyBlock):
            pv.check_origin_labels("Backup strategy: R2.", "x")  # no run: the kit's alias shapes
        with self.assertRaises(pv.PolicyBlock):
            pv.check_origin_labels("strategy: HAlice", "x", aliases=["HAlice-01"])

    def test_the_topic_is_taken_out_across_a_line_break(self):
        topic = "essays generated by Claude"
        pv.check_origin_labels("BRIEF: essays generated\nby Claude", "x", aliases=[], allow=[topic])


class RunAliasTests(tl.EngineTestCase):
    def test_imported_headings_are_no_alias_ids_but_team_seed_aliases_are(self):
        ctx = self.make_ctx(families=("claude", "gpt"))
        ctx.write("pool/S2_contrarian.md", "### S2-01 Night swap board\n- Pitch: p\n")
        ctx.write("pool/IMPORT_workshop.md", "# Workshop\n\n## COVID-19 exposure alerts for wards\ntext\n\n"
                                             "## GPT-4 shift summaries\ntext\n\n### K-12 rota lessons\n- Pitch: p\n"
                                             "- Mechanism: m\n- Fails if: f\n")
        ctx.write("00_HUMAN_SEEDS_Alice.md", "# Seeds\n## Ideas\n- a swap board\n")
        ctx.write("merges.json", json.dumps({"ideas": [{"key": "k", "aliases": ["HAlice-01", "S2-01", "GPT-4"]}]}))
        ids = builders.run_aliases(ctx)
        self.assertEqual([a for a in ("COVID-19", "GPT-4", "K-12") if a in ids], [])
        self.assertIn("HAlice-01", ids)
        self.assertIn("S2-01", ids)
        self.assertIn("IMP-01", ids)


IMPORT = "# Ideas from our workshop\n\n## GPT-4 shift summaries\nA nightly summary of open swaps from the swap board.\n"


def curator_keeps(title):
    orig = stubs.respond

    def respond(job, prompt):
        text = orig(job, prompt)
        if job.get("template") in ("CURATOR", "QUICK-CURATE"):
            data = json.loads(text)
            data["ideas"][0]["title"] = title  # the curator keeps the imported idea's name
            text = json.dumps(data, indent=1)
        return text
    return respond


def curated_with(field, text):
    orig = stubs._quick_curated

    def fn(ctx):
        out = orig(ctx)
        out["ideas"][0][field] = text
        return out
    return fn


class JudgeRunTests(tl.EngineTestCase):
    """Full-auto runs on two families, driven with the stubs."""

    def run_import(self, mode):
        ctx = tl.full_auto_ctx(self, mode=mode, families=("claude", "gpt"), run_name="2026-09-27-" + mode)
        ctx.write("pool/IMPORT_workshop.md", IMPORT)  # what `ub import workshop.md` writes before curation
        with mock.patch.object(stubs, "respond", curator_keeps("GPT-4 shift summaries")):
            return tl.drive(ctx)

    def test_an_imported_heading_term_reaches_done(self):
        for mode in ("standard", "quick"):
            card = self.run_import(mode)
            self.assertEqual(card["type"], "DONE", "%s: %s" % (mode, json.dumps(card)[:600]))

    def run_quick(self, n, text):
        ctx = tl.full_auto_ctx(self, mode="quick", families=("claude", "gpt"), run_name="2026-09-27-q%d" % n)
        with mock.patch.object(stubs, "_quick_curated", curated_with("mechanism", text)):
            return tl.drive(ctx)

    def test_ordinary_curated_text_reaches_done(self):
        for n, text in enumerate(("Escalation strategy: human coordinators take over at night.",
                                  "Handwritten letters written by human volunteers, scanned each week.")):
            card = self.run_quick(n, text)
            self.assertEqual(card["type"], "DONE", "%s: %s" % (text, json.dumps(card)[:600]))

    def test_a_markdown_origin_label_blocks_the_quick_screen(self):
        for n, text in enumerate(("**Origin:** gpt. A shared swap board.", "Generated by: `claude`. A swap board.")):
            card = self.run_quick(n, text)
            self.assertEqual(card["type"], "BLOCKED", text)
            self.assertIn("(in quick/curated.json)", card.get("say") or "", text)

    def test_ordinary_architecture_wording_reaches_done(self):
        orig = stubs._arch_candidate

        def candidate(ctx):
            out = orig(ctx)
            out.update(summary="Storage strategy: S3 buckets with lifecycle rules.",
                       deployment="CloudFront in front of the origin S3 bucket.")
            return out
        os.makedirs(os.path.join(self.project, ".git"), exist_ok=True)
        ctx = tl.full_auto_ctx(self, mode="standard", variant="software", run_name="2026-09-27-sw")
        with mock.patch.object(stubs, "_arch_candidate", candidate):
            card = tl.drive(ctx)
        self.assertEqual(card["type"], "DONE", json.dumps(card)[:600])


INTRO = ("## A2. DOMAIN TERMS (today's system)\n"
         "These words describe the system as it is today, so ideas can be stated unambiguously.\n")


class A2FilterTests(unittest.TestCase):
    def test_a_wrapped_definition_goes_with_its_term(self):
        a2 = (INTRO + "- **Float pool** [CONTEXT.md]: nurses without a home ward, paid from the central\n"
                      "budget line OPS-449 and rostered by the site team.\n"
                      "- **Swap** [proposed]: an exchange of two shifts that\nboth nurses confirm.\n")
        out = pv.filter_a2_terms(a2)
        self.assertNotIn("OPS-449", out)
        self.assertNotIn("Float pool", out)
        self.assertIn("- **Swap** [proposed]: an exchange of two shifts that\nboth nurses confirm.", out)
        self.assertIn("These words describe the system as it is today", out)

    def test_the_body_under_a_heading_term_goes_with_it(self):
        a2 = (INTRO + "\n### Rota (CONTEXT.md)\nThe weekly plan SECRET3b.\n\n### Handover [proposed]\n"
                      "A shared note KEEP3b.\n")
        out = pv.filter_a2_terms(a2)
        self.assertNotIn("SECRET3b", out)
        self.assertIn("A shared note KEEP3b.", out)

    def test_the_a2_heading_itself_never_takes_the_intro(self):
        out = pv.filter_a2_terms("## A2. DOMAIN TERMS (from the FRAME and CONTEXT.md)\nThese words describe it.\n"
                                 "- **Swap** [proposed]: x\n")
        self.assertEqual(out, "These words describe it.\n- **Swap** [proposed]: x\n")

    def test_a_nested_term_needs_its_own_mark(self):
        a2 = (INTRO + "- **Shift swap** [proposed]: two nurses trade shifts\n"
                      "  - **RotaSlot**: the internal slot record the scheduler locks (src/sched/rota.py)\n"
                      "  - **WardLock** [docs/glossary.md]: advisory lock held by the nightly rota job\n"
                      "  | Pager | the on-call pager |\n"
                      "  - **Swap window** [proposed]: the hours a swap may cover\n"
                      "  - source: s.md\n"
                      "  - also called: trade\n")
        out = pv.filter_a2_terms(a2)
        for word in ("RotaSlot", "rota.py", "WardLock", "Pager"):
            self.assertNotIn(word, out)
        self.assertIn("- **Shift swap** [proposed]: two nurses trade shifts\n"
                      "  - **Swap window** [proposed]: the hours a swap may cover\n"
                      "  - source: s.md\n  - also called: trade\n", out)


class A2FactsTests(tl.EngineTestCase):
    def test_facts_for_another_vendor_hold_no_wrapped_context_md_text(self):
        os.makedirs(os.path.join(self.project, ".git"), exist_ok=True)
        ctx = self.make_ctx(variant="software", families=("claude", "gpt"))
        ctx.write("01_FRAME.md", "# FRAME: x\n## Job statement\nWhen x.\n## Problem\nHow might we y?\n")
        ctx.write("02_CONTEXT.md", "## A. FACTS\n- F1 FACT (src/swap.py:42): swaps are approved by hand\n\n" + INTRO +
                  "- **Float pool** [CONTEXT.md]: nurses without a home ward, paid from the central\n"
                  "budget line OPS-449 and rostered by the site team.\n"
                  "- **Swap** [proposed]: an exchange of two shifts\n"
                  "  - **RotaSlot**: the slot record (src/sched/rota.py)\n"
                  "\n## B. LANDSCAPE\n- l\n## C. SEARCH BOUNDARY\n- s\n")
        text = registry.facts_text(ctx, "gpt")
        for word in ("OPS-449", "Float pool", "RotaSlot"):
            self.assertNotIn(word, text)
        self.assertIn("- **Swap** [proposed]: an exchange of two shifts", text)
        self.assertIn("OPS-449", registry.facts_text(ctx, "claude"))


if __name__ == "__main__":
    unittest.main()
