# -*- coding: utf-8 -*-
"""The gate-reply corpora L and M of the 2.1.0 read-back review (KIT_SPEC 4.12), table-driven like
test_x_xa_gate_corpus_w.

Every row is one reply at one gate, its corpus intent and how the engine takes it: `act` (a documented form,
applied at once), `rb` (read back: nothing is applied until the user confirms, and the reading shown must match the
intent) or `ask` (asked again: never a wrong action). An intent alternative `readback [<reading>]` matches only a
read-back. L holds regional and second-language English (`no need <X>`, `prepone`, `do the needful`), privacy requests
in German, Russian, Hindi and Arabic, double negations, email closings and courtesy; M holds markdown checkboxes,
labelled free text (`changes:`, `rescue <ID>:`, `topic:`), G14 publish lists with the ADRs, G11 letters in their
written forms and G9 results with the observed numbers. The rows go through the same entry points and fixtures as the
W corpus test (gates.prepare_answer -> gates.read_back -> apply; the v1-run offer through pipeline.answer_gate). A row
the Q, S, U or W corpus test already holds is left to it.

RESIDUAL pins the readings shown for three read-back rows that differ from the corpus intent: G2c 'I am not agree with
the ASSUMED items' (read back as that correction), G4 'rescue=I-012' (the rescue, with the default reason) and G9
'passed I think' (PASSED, with the hedge in the reply the user confirms). Each shows the action before anything
happens.
"""

import os
import sys
import time
import unittest
from unittest import mock

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "fixtures", "engine"))
import engine_testlib as tl  # noqa: E402
import test_r_ra_gate_corpus_q as q  # noqa: E402
import test_t_ta_gate_corpus_s as s  # noqa: E402
import test_x_xa_gate_corpus_w as w  # noqa: E402

from ublib.engine import gates  # noqa: E402

_key = s._key

ROWS = {
    'G0k': [
        ('Go.', 'start seeds=0 mode=standard autopilot=guided private=False web=on vendors=on', 'act'),
        ('ok go', 'start seeds=0 mode=standard autopilot=guided private=False web=on vendors=on', 'act'),
        ('go please', 'start seeds=0 mode=standard autopilot=guided private=False web=on vendors=on', 'act'),
        ('quick\ngo', 'start seeds=0 mode=quick web=on vendors=on', 'act'),
        ('deep\nfull-auto\ngo', 'start seeds=0 mode=deep autopilot=full-auto', 'act'),
        ('Go ahead', 'start seeds=0 mode=standard autopilot=guided private=False web=on vendors=on', 'act'),
        ('- nurses swap shift with QR code on the ward\n- head nurse approve with one click\ngo',
         'start seeds=2 web=on vendors=on', 'rb'),
        ('My ideas is:\n- shift market inside hospital intranet\n- bonus points for who take the night shift',
         'start seeds=2', 'rb'),
        ('Dear team,\n\nI hope this finds you well. Please find my ideas below:\n- shift marketplace in the '
         'hospital intranet\n- extra pay for weekend swaps\n\nLooking forward to the results.\nBest regards,'
         '\nAhmed',
         'start seeds=2', 'rb'),
        ('go, but only one idea from me: nurses rate each other after the swap', 'start seeds=1 | ask', 'ask'),
        ('go\n- nurses swap shifts by SMS\n- night shift lottery', 'start seeds=2', 'rb'),
        ('go but please no send my ideas to the other companies, only Claude',
         'ask | start seeds=0 vendors=off', 'ask'),
        ('yalla go, but web search no need', 'ask | start seeds=0 web=off', 'ask'),
        ('Is confidential project of my hospital. go',
         'ask | start seeds=0 private=True | start seeds=0 vendors=off', 'ask'),
        ('no no wait, I must first ask my boss', 'ask', 'ask'),
        ('not now, tomorrow maybe', 'ask', 'ask'),
        ("I don't not want the web search", 'ask | start seeds=0 web=on', 'ask'),
        ('vendors: no (NDA with the hospital)\ngo', 'start seeds=0 vendors=off', 'rb'),
        ('Please to make it private and after go', 'ask | start seeds=0 private=True', 'ask'),
        ('nahi, abhi start mat karo', 'ask', 'ask'),
        ('no start, I want change the topic first', 'ask', 'ask'),
        ('\u041d\u0435 \u043d\u0430\u0434\u043e \u0432\u0435\u0431 \u043f\u043e\u0438\u0441\u043a. go',
         'ask | start seeds=0 web=off', 'ask'),
        ('\u4e0d\u8981\u7528\u7f51\u7edc\u641c\u7d22, go', 'ask | start seeds=0 web=off', 'ask'),
        ("ohne Websuche bitte, los geht's", 'ask | start seeds=0 web=off', 'ask'),
        ('vendor no, web no, yalla', 'ask | start seeds=0 web=off vendors=off', 'ask'),
        ('Please not to share with OpenAI, they are competitor of our hospital vendor',
         'ask | start seeds=0 vendors=off', 'ask'),
        ("Please don't make it private, is fine to share. go", 'ask | start seeds=0 private=False vendors=on', 'ask'),
        ('My idea: one-tap swap for nurses. Also I want web: no.', 'ask | start seeds=1 web=off', 'ask'),
        ('stop, the topic is wrong. It must be about the night shift only.', 'ask', 'ask'),
        ('Revert back with the cost first, then we go', 'ask', 'ask'),
        ('hold on, keep it local, nothing leave my laptop', 'ask', 'ask'),
        ('vendors off pls, web ok, go', 'ask | start seeds=0 vendors=off web=on', 'ask'),
        ('Only Claude please. No GPT, no Kimi.', 'ask | start seeds=0 vendors=off', 'ask'),
        ('Kindly proceed with the deep mode at your earliest convenience.', 'start seeds=0 mode=deep', 'ask'),
        ('Kindly do the needful and start the brainstorm in standard mode.', 'start seeds=0 mode=standard', 'ask'),
        ('Standard is okay. Guided is okay. Web yes. Vendors yes. Go.',
         'start seeds=0 mode=standard autopilot=guided web=on vendors=on', 'ask'),
        ('s\xed, adelante', 'start seeds=0 | ask', 'ask'),
        ('ok bas, go with quick', 'start seeds=0 mode=quick', 'ask'),
        ('deep mode make please, full auto', 'start seeds=0 mode=deep autopilot=full-auto | ask', 'rb'),
        ('I am agree with the plan. Go.',
         'start seeds=0 mode=standard autopilot=guided private=False web=on vendors=on', 'ask'),
        ('go go go \U0001f680', 'start seeds=0 mode=standard autopilot=guided private=False web=on vendors=on', 'rb'),
        ('vendors: yes\nweb: yes\nstart', 'start seeds=0 web=on vendors=on', 'rb'),
        ('code: yes\ngo', 'start seeds=0 web=on vendors=on', 'act'),
        ('Hello,\n\nThank you for the plan. We are agree with standard mode and guided.\nPlease go.\n\nWith '
         'best regards,\nDr. Svetlana Ivanova\nHead Nurse, Ward 7',
         'start seeds=0 mode=standard autopilot=guided', 'ask'),
        ('private mode, khalas', 'start seeds=0 private=True | ask', 'rb'),
        ('Go', 'start seeds=0 mode=standard private=False', 'act'),
        ('go.', 'start seeds=0 mode=standard private=False', 'act'),
        ('GO!', 'start seeds=0 mode=standard private=False', 'act'),
        ('go ahead', 'start seeds=0 mode=standard private=False', 'act'),
        ('deep, hands-on, go', 'start mode=deep autopilot=hands-on seeds=0', 'act'),
        ('mode: deep', 'start mode=deep seeds=0', 'act'),
        ('go, private', 'start private=True seeds=0', 'act'),
        ('Primary: nurses swap shifts by SMS', 'start mode=standard private=False', 'act'),
        ('- nurses swap shifts by SMS\n- a shared swap calendar\ngo', 'start seeds=2 mode=standard', 'rb'),
        ('mode=deep', 'start mode=deep seeds=0', 'rb'),
        ('{"mode": "quick", "private": true}', 'start mode=quick private=True seeds=0', 'ask'),
        ('mode: quick\nautopilot: hands-on', 'start mode=quick autopilot=hands-on seeds=0', 'rb'),
        ('- [x] private\n- [ ] deep', 'start private=True mode=standard seeds=0 | ask', 'rb'),
        ('Reply `go` to start', 'start seeds=0 mode=standard private=False | ask', 'ask'),
        ('go # standard is fine', 'start seeds=0 mode=standard private=False', 'rb'),
        ('go --private', 'start private=True seeds=0', 'act'),
        ('go --deep', 'start mode=deep seeds=0', 'act'),
        ('vendors=false', 'start vendors=off seeds=0', 'ask'),
        ('privacy: {web: no, vendors: no}', 'start web=off vendors=off seeds=0', 'ask'),
        ('go\n# keep it cheap', 'start seeds=0 mode=standard', 'rb'),
        ('go, but keep it private', 'start private=True seeds=0', 'ask'),
        ("go but don't use the web", 'start web=off seeds=0', 'ask'),
        ('go, no other vendors please', 'start vendors=off seeds=0', 'ask'),
        ("don't send my ideas to other vendors", 'start vendors=off seeds=0 | ask', 'ask'),
        ('wait, not yet', 'ask', 'ask'),
        ('go? what does it cost', 'ask', 'ask'),
        ('go later', 'ask', 'ask'),
        ("don't go yet, I want to add ideas", 'ask', 'ask'),
        ('private? what does that change', 'ask', 'ask'),
        ('go, but no web search and no GPT', 'start web=off vendors=off seeds=0 | ask', 'ask'),
        ('go # but not private', 'start private=False seeds=0', 'ask'),
        ('not private, go', 'start private=False seeds=0', 'ask'),
        ('go (web ok, but no other vendors)', 'start web=on vendors=off seeds=0', 'ask'),
        ('deep? or standard', 'ask', 'ask'),
        ('go deep, not quick', 'start mode=deep seeds=0', 'ask'),
        ('go, publish all, ce', 'start seeds=0 | ask', 'ask'),
        ('> I read your reply as: start the run in standard mode.\nyes, but deep',
         'start mode=deep seeds=0 | ask', 'ask'),
    ],
    'G0v1': [
        ('Go.', 'extend', 'act'),
        ('yes go', 'extend', 'act'),
        ('Proceed.', 'extend', 'act'),
        ('no need extend, stop here', 'stop', 'rb'),
        ("don't go, stop", 'stop', 'rb'),
        ('no, not go', 'stop | ask', 'rb'),
        ('go? no.', 'stop | ask', 'rb'),
        ('Maybe go, how much it cost?', 'ask', 'ask'),
        ('wait, stop, let me think', 'ask', 'ask'),
        ('Kindly do not extend the run; we are satisfied with the v1 results.', 'stop | ask', 'rb'),
        ("I don't not want to extend", 'ask | readback extend', 'ask'),
        ('extend please, but only the architecture, no proposal', 'ask', 'ask'),
        ('go but without the proposal', 'ask', 'ask'),
        ('not stop. go.', 'extend', 'rb'),
        ('go is not needed', 'stop | ask', 'rb'),
        ('neither go nor stop, just keep it paused', 'ask', 'ask'),
        ('go ahead, but cost how much?', 'ask', 'ask'),
        ('I am not agree to extend', 'stop | ask', 'rb'),
        ('No thanks', 'stop | ask', 'rb'),
        ('stop the extension idea, go back to v1 only', 'stop | ask', 'ask'),
        ('si, go', 'extend', 'act'),
        ('nein, stop', 'stop', 'rb'),
        ('ok bas stop', 'stop', 'ask'),
        ("Let's table it for now", 'ask', 'ask'),
        ('I will revert back after the meeting', 'ask', 'ask'),
        ('go, \u6211\u540c\u610f', 'extend', 'rb'),
        ('\u0414\u0430, go', 'extend', 'rb'),
        ('Hi team,\n\nThanks for the v1 run. Please go ahead and extend it.\n\nRegards,\nPriya', 'extend', 'rb'),
        ('Dear Sir/Madam,\nI would like to request that the run not be extended. Kindly stop it.\nThanks and'
         ' regards,\nRajesh',
         'stop', 'rb'),
        ('Do the needful and extend', 'extend', 'ask'),
        ('yes extend with architecture and proposal', 'extend', 'rb'),
        ('Please to extend the run.', 'extend', 'rb'),
        ('go (we have budget)', 'extend', 'rb'),
        ('stop (budget is finished)', 'stop', 'rb'),
        ('Ok stop it', 'stop', 'rb'),
        ('Why not', 'ask | extend', 'ask'),
        ("stop and don't go further", 'stop', 'ask'),
        ('prepone it, go now', 'extend | ask', 'rb'),
        ('stop.', 'stop', 'act'),
        ('--extend', 'extend', 'act'),
        ('{"extend": true}', 'extend', 'rb'),
        ('{"confirm": false}', 'stop | ask', 'rb'),
        ('go # add the arch + proposal', 'extend', 'rb'),
        ('**stop**', 'stop', 'act'),
        ('- [x] extend', 'extend', 'rb'),
        ('Reply `go` to extend this v1 run', 'extend | ask', 'rb'),
        ("stop # it's fine as is", 'stop', 'rb'),
        ('go --arch --proposal', 'extend', 'rb'),
        ('go go go', 'extend', 'act'),
        ('yep, extend with architecture + proposal', 'extend', 'rb'),
        ('go? how much will it cost', 'ask', 'ask'),
        ('stop, actually go', 'ask | extend', 'ask'),
        ("go (if it's cheap)", 'ask', 'ask'),
        ("I'd rather stop here", 'stop', 'rb'),
        ('extend? no.', 'stop', 'rb'),
        ("stop -- don't extend", 'stop', 'rb'),
        ('hmm, not sure', 'ask', 'ask'),
        ('go, approve', 'extend | ask', 'act'),
        ('> I read your reply as: stop this run.\nno - extend it', 'extend | ask', 'rb'),
    ],
    'G1': [
        ('done, please continue', 'done', 'rb'),
        ('done!', 'done', 'act'),
        ("I'm done", 'done', 'rb'),
        ('skip? no, I am still writing', 'ask', 'ask'),
        ('no skip, I write now', 'ask', 'ask'),
        ("don't skip, I am writing", 'ask', 'ask'),
        ('I will be done in 5 minute', 'ask', 'ask'),
        ('done with 3 ideas, but maybe I add one more later', 'done | ask', 'ask'),
        ('Should I skip?', 'ask', 'ask'),
        ('done - no wait, one more', 'ask', 'ask'),
        ('nahi, skip mat karo', 'ask', 'ask'),
        ('not done, skip', 'skip | ask', 'rb'),
        ('I will revert back with the ideas tomorrow', 'ask', 'ask'),
        ('khalas, done', 'done', 'act'),
        ('ho gaya', 'done | ask', 'ask'),
        ('fertig', 'done | ask', 'ask'),
        ('termin\xe9', 'done | ask', 'ask'),
        ('\u0433\u043e\u0442\u043e\u0432\u043e', 'done | ask', 'ask'),
        ('\u5199\u5b8c\u4e86', 'done | ask', 'ask'),
        ('I have wrote the ideas in the file', 'done', 'rb'),
        ('no ideas from me, skip it', 'skip', 'rb'),
        ("I don't have ideas, sorry", 'skip | ask', 'ask'),
        ("I don't not want to skip", 'ask', 'ask'),
        ('Kindly note that I have completed the seeds file.', 'done', 'ask'),
        ('Please treat this step as skipped.', 'skip', 'ask'),
        ('table it', 'ask', 'ask'),
        ("done, the ideas are in the file. btw skip the fax one, it's a joke", 'done | ask', 'ask'),
        ('Hi, I added my 4 ideas in the seeds file like you said. Done from my side.\nThanks,\nWei', 'done', 'rb'),
        ('skip, I prefer to see AI ideas first', 'skip', 'rb'),
        ('si, done', 'done', 'rb'),
        ('all ideas written', 'done', 'rb'),
        ('we skip this', 'skip', 'rb'),
        ('skip.', 'skip', 'act'),
        ('done, thanks', 'done', 'act'),
        ("i'm done", 'done', 'rb'),
        ('Skip it.', 'skip', 'rb'),
        ('Done - ideas are in the file', 'done', 'rb'),
        ('done=true', 'done', 'rb'),
        ('{"skip": true}', 'skip', 'rb'),
        ('- [x] done', 'done', 'rb'),
        ('**skip**', 'skip', 'act'),
        ('done # wrote 3 ideas', 'done', 'rb'),
        ('skip # no ideas today', 'skip', 'rb'),
        ('reply `done` (or `skip`)', 'ask', 'ask'),
        ('done; skip', 'ask', 'ask'),
        ('--skip', 'skip', 'act'),
        ('done && next', 'done', 'ask'),
        ('done? do I need to save first', 'ask', 'ask'),
        ('skip, actually done', 'ask | done', 'ask'),
        ('done, no wait', 'ask', 'ask'),
        ("skip for now, I'll add ideas at round 2", 'skip', 'rb'),
        ('no ideas, skip', 'skip', 'rb'),
        ("don't skip", 'ask', 'ask'),
        ("I haven't written anything. skip.", 'skip', 'rb'),
        ('done (I think)', 'ask | done', 'rb'),
        ('wait, still writing', 'ask', 'ask'),
        ('done, ok', 'done', 'rb'),
        ('done, go', 'done | ask', 'rb'),
    ],
    'G10': [
        ('OK.', 'confirm', 'act'),
        ('confirm', 'confirm', 'act'),
        ('ok thanks', 'confirm', 'act'),
        ('yes correct', 'confirm', 'act'),
        ('Looks good', 'confirm', 'act'),
        ('I agree', 'confirm', 'act'),
        ('the latency driver is wrong, it must be 2 seconds not 200 ms', 'correct | correct(no-redo)', 'rb'),
        ('Please add offline mode as a driver', 'correct | correct(no-redo)', 'rb'),
        ('ok but the uptime should be 99.5%', 'correct | correct(no-redo)', 'rb'),
        ('Correct, except the users are 300 not 3000', 'correct | correct(no-redo)', 'rb'),
        ('ok? no, the security driver is missing', 'correct | correct(no-redo)', 'rb'),
        ('not ok', 'ask', 'ask'),
        ('yes but I will check with the architect tomorrow', 'ask', 'ask'),
        ('ok, I will revert back with corrections', 'ask', 'ask'),
        ('Confirm. But remove the ASSUMPTION about cloud, we are on-prem', 'correct | correct(no-redo)', 'rb'),
        ('what is an ASSUMPTION tag?', 'ask', 'ask'),
        ("I don't not agree", 'ask | confirm', 'ask'),
        ('fix the weights? no, leave them', 'confirm | ask', 'ask'),
        ('No changes, all good', 'confirm', 'rb'),
        ('Nothing to correct', 'confirm', 'rb'),
        ('No notes from my side, kindly proceed', 'confirm', 'rb'),
        ('Dear team,\nThe drivers are fine except the budget driver: it should be 40k per year, not 20k.\nKi'
         'nd regards,\nMaria',
         'correct | correct(no-redo)', 'rb'),
        ('ok bas, move forward', 'confirm', 'ask'),
        ('S\xed, correcto', 'confirm | ask', 'ask'),
        ('stimmt so', 'confirm | ask', 'ask'),
        ('\u0412\u0441\u0451 \u0432\u0435\u0440\u043d\u043e', 'confirm | ask', 'ask'),
        ('theek hai', 'confirm | ask', 'act'),
        ('tayeb, ok', 'confirm', 'act'),
        ('Please do the needful and drop the ASSUMPTION about 24/7 support', 'correct | correct(no-redo)', 'rb'),
        ('ok, go ahead', 'confirm', 'act'),
        ('prepone the go-live driver to Q1, rest ok', 'correct | correct(no-redo)', 'rb'),
        ('Table the ASSUMPTION ones, confirm the rest', 'ask', 'ask'),
        ('\u5bf9\u7684', 'confirm | ask', 'ask'),
        ('ok.', 'confirm', 'act'),
        ('go ahead', 'confirm', 'act'),
        ('yes, confirmed', 'confirm', 'act'),
        ('Correction: peak load is 2,000 users, not 200.', 'correct', 'rb'),
        ('The latency budget is 500 ms, not 100 ms.', 'correct', 'rb'),
        ('ok!', 'confirm', 'act'),
        ('--confirm', 'confirm', 'act'),
        ('{"corrections": "peak load 2000"}', 'correct', 'rb'),
        ('confirm: true', 'confirm', 'rb'),
        ('- [x] ok', 'confirm', 'rb'),
        ('`ok`', 'confirm', 'act'),
        ('**OK**', 'confirm', 'act'),
        ('ok # drivers look right', 'confirm', 'rb'),
        ('LGTM', 'confirm', 'act'),
        ('s/200 users/2000 users/', 'correct', 'rb'),
        ('- ASSUMPTION: 200 users -> actually 2000', 'correct', 'rb'),
        ('corrections: peak is 2000 users', 'correct', 'rb'),
        ('ok (no corrections)', 'confirm', 'rb'),
        ('nothing to correct', 'confirm', 'rb'),
        ('fine, leave the ASSUMPTIONs tagged', 'confirm', 'ask'),
        ('ok, but peak load is 2000', 'correct | ask', 'rb'),
        ('ok, corrections to follow', 'ask', 'ask'),
        ('ok?', 'ask', 'ask'),
        ('wait, checking the drivers', 'ask', 'ask'),
        ('mostly ok; the ASSUMPTION on HIPAA is wrong, we are not in the US', 'correct | ask', 'ask'),
        ("don't confirm yet", 'ask', 'ask'),
        ('ok I guess', 'ask | confirm', 'ask'),
        ('yes except the latency number', 'ask | correct', 'rb'),
        ('no, latency is wrong', 'ask | correct', 'rb'),
        ("ok # but I'm unsure about the HIPAA item", 'ask | confirm', 'ask'),
        ('ok, but can you double-check the load number?', 'ask', 'ask'),
        ('ok, approve', 'confirm | ask', 'act'),
        ('ok, go', 'confirm', 'act'),
    ],
    'G11': [
        ('take C', 'C suggestion=False', 'rb'),
        ('A? no. C', 'C', 'rb'),
        ('avoid A, take the next best', 'ask | B', 'ask'),
        ('B maybe', 'ask', 'ask'),
        ('B or C, you choose', 'ask', 'ask'),
        ('B, actually C', 'ask', 'ask'),
        ('A is too risky for us', 'ask', 'ask'),
        ('not the suggestion, the other one', 'ask', 'ask'),
        ('A? No wait, yes A', 'ask | A', 'ask'),
        ('no A, no B, so C', 'C', 'ask'),
        ("I don't not like A", 'ask | readback A', 'ask'),
        ('Why not A', 'ask | A', 'ask'),
        ('I am agree with the suggestion', 'A suggestion=True', 'ask'),
        ('Kindly proceed with option B at your earliest convenience.', 'B', 'ask'),
        ('we go with C because is cheaper for our small team', 'C', 'rb'),
        ('C, although A is also nice', 'C', 'rb'),
        ('si B', 'B', 'rb'),
        ('B bitte', 'B', 'ask'),
        ('yalla C', 'C', 'rb'),
        ('ok bas A', 'A', 'ask'),
        ('khalas A', 'A | ask', 'rb'),
        ('prefer B over A', 'B', 'ask'),
        ('B is better, A is too complex', 'B', 'ask'),
        ('A with steal from C: the SMS gateway', 'A', 'ask'),
        ('Dear team,\nAfter long discussion with our CTO, option B is our choice.\nKind regards,\nKenji', 'B', 'rb'),
        ('take B, reason: it is offline first', 'B', 'rb'),
        ('option c', 'C', 'rb'),
        ('B se chalo', 'B | ask', 'ask'),
        ('Vamos con B', 'B | ask', 'ask'),
        ('Je choisis C', 'C | ask', 'ask'),
        ('\u0412\u044b\u0431\u0438\u0440\u0430\u044e B', 'B | ask', 'ask'),
        ('\u9009B', 'B | ask', 'ask'),
        ('B.', 'B', 'act'),
        ('ok, thanks', 'A suggestion=True', 'act'),
        ('C + steal B: audit log', 'C', 'act'),
        ('go ahead', 'A suggestion=True', 'act'),
        ('choice=B', 'B', 'rb'),
        ('{"accept_recommendation": true}', 'A suggestion=True', 'rb'),
        ('- [x] B', 'B', 'rb'),
        ('- [ ] A\n- [x] C', 'C', 'rb'),
        ('`C`', 'C', 'act'),
        ('B # simpler ops', 'B', 'rb'),
        ('B (the event-sourced one)', 'B', 'rb'),
        ('Reply `ok` for the suggestion', 'A suggestion=True | ask', 'ask'),
        ('B + steal A: offline cache, C: audit log', 'B', 'act'),
        ('option B', 'B', 'rb'),
        ('B, steal=A:offline cache', 'B', 'rb'),
        ('B? or C', 'ask', 'ask'),
        ('ok, but B', 'B | ask', 'ask'),
        ('B, not C', 'B', 'rb'),
        ("don't take the suggestion, C", 'C', 'rb'),
        ('A, but not the offline cache part', 'A | ask', 'rb'),
        ('not B', 'ask', 'ask'),
        ('B # not A, A is too complex', 'B', 'rb'),
        ('ok? which model wrote A', 'ask', 'ask'),
        ('B + steal A: offline cache (not the sync)', 'B', 'act'),
        ("C, don't steal anything", 'C', 'rb'),
        ('idk, B', 'ask | readback B', 'ask'),
        ('B, approve', 'B | ask', 'rb'),
        ('> I read your reply as: architecture B.\nno, C', 'C | ask', 'rb'),
    ],
    'G12': [
        ('ok thanks', 'ok acc=all rej=-', 'act'),
        ('accept 1, reject 2 3', 'ok acc=0001 rej=0002,0003', 'act'),
        ('reject 3 because SMS is too expensive', 'ok rej=0003', 'rb'),
        ('reject 3: the Twilio cost is not acceptable', 'ok rej=0003', 'rb'),
        ("don't reject 3, accept all", 'ok acc=all rej=-', 'ask'),
        ('reject 3? no, accept all', 'ok acc=all rej=-', 'ask'),
        ('accept all but not ADR 3', 'ok rej=0003', 'rb'),
        ('no need reject anything', 'ok rej=-', 'ask'),
        ('reject 3 maybe', 'ask', 'ask'),
        ('accept all, table 3 for next meeting', 'ask | ok acc=0001,0002 rej=-', 'ask'),
        ("I don't not accept 3", 'ask', 'ask'),
        ('accept 1 and 3, not 2', 'ok acc=0001,0003', 'rb'),
        ('reject ADR-0003 please', 'ok rej=0003', 'rb'),
        ('I am agree with 1 and 2, not agree with 3', 'ok rej=0003 | ask', 'ask'),
        ('ok, reject the SMS one', 'ask | ok rej=0003', 'ask'),
        ('accept monolith and postgres, reject SMS', 'ask | ok rej=0003', 'ask'),
        ('Kindly accept ADRs 1 and 2; ADR 3 is to be rejected.', 'ok acc=0001,0002 rej=0003', 'ask'),
        ('Dear team,\nPlease find my decision: accept all ADRs.\nRegards,\nCarlos', 'ok acc=all rej=-', 'rb'),
        ('reject 3, rest ok', 'ok rej=0003', 'rb'),
        ('3 no, others yes', 'ok rej=0003 | ask', 'ask'),
        ('si, accept all', 'ok acc=all rej=-', 'act'),
        ('khalas accept all', 'ok acc=all rej=-', 'act'),
        ('nein, reject 2', 'ok rej=0002', 'rb'),
        ('accept all ADRs, but ADR 3 I reject', 'ok rej=0003', 'rb'),
        ('yalla accept all', 'ok acc=all rej=-', 'act'),
        ('Hello,\nADR 1 ok, ADR 2 ok, ADR 3 reject please (SMS too costly for us).\nThanks,\nOleg',
         'ok rej=0003', 'ask'),
        ('accept everything except ADR 2', 'ok rej=0002', 'rb'),
        ('ok, reject 2', 'ok rej=0002', 'act'),
        ('ok, reject 1', 'ok rej=0001', 'act'),
        ('--accept 1 2 --reject 3', 'ok acc=0001,0002 rej=0003', 'act'),
        ('{"accept": ["all"]}', 'ok acc=all rej=-', 'rb'),
        ('{"accept": [1, 2], "reject": [3]}', 'ok acc=0001,0002 rej=0003', 'rb'),
        ('accept: [1, 2]\nreject: [3]', 'ok acc=0001,0002 rej=0003', 'rb'),
        ('- [x] 0001\n- [x] 0002\n- [ ] 0003', 'ok acc=0001,0002 | ask', 'ask'),
        ('reject ADR-0003', 'ok rej=0003', 'rb'),
        ('ok, reject #3', 'ok rej=0003', 'rb'),
        ('**ok**, reject 3', 'ok rej=0003', 'act'),
        ('ok, reject `3`', 'ok rej=0003', 'act'),
        ('ok, reject 3 # SMS vendor lock-in', 'ok rej=0003', 'rb'),
        ('ok, reject 3 (Use SMS)', 'ok rej=0003', 'rb'),
        ("reject 'Use SMS'", 'ok rej=0003 | ask', 'ask'),
        ('accept 1-2, reject 3', 'ok acc=0001,0002 rej=0003', 'rb'),
        ('ok, reject 3? not sure', 'ask', 'ask'),
        ("ok, but don't reject 3", 'ok acc=all rej=-', 'ask'),
        ('ok, reject 3, actually accept it', 'ask | ok acc=all rej=-', 'ask'),
        ('accept 1 2, not 3', 'ok acc=0001,0002', 'rb'),
        ('reject 3 because we use push, not SMS', 'ok rej=0003', 'ask'),
        ('ok, but reject 3 if ADR 2 is accepted', 'ask', 'ask'),
        ('yes, reject 3', 'ok rej=0003', 'act'),
        ('accept everything except 3', 'ok rej=0003', 'rb'),
        ('no, reject all', 'ok rej=0001,0002,0003', 'ask'),
        ('ok, reject 3 - wait, 2', 'ask | ok rej=0002', 'ask'),
        ('ok, reject 3, approve', 'ok rej=0003 | ask', 'rb'),
        ('> I read your reply as: accept all ADRs.\nno, reject 3', 'ok rej=0003 | ask', 'rb'),
    ],
    'G13': [
        ('approve thanks', 'approve', 'act'),
        ('changes: add a pilot budget of 20k', 'changes', 'rb'),
        ('changes: the proposal must mention the union', 'changes', 'rb'),
        ("don't approve, switch to B", 'switch to=B', 'rb'),
        ('approve? no, changes: add a risk section', 'changes', 'rb'),
        ('not approve yet', 'ask', 'ask'),
        ('switch B? no, approve', 'approve', 'rb'),
        ('switch to B maybe', 'ask', 'ask'),
        ('runner-up? no. approve A', 'approve', 'rb'),
        ('no need switch, approve', 'approve', 'rb'),
        ('approve but please change the budget to 30k', 'changes | ask', 'ask'),
        ('table the approval, I need to check with finance', 'ask', 'ask'),
        ('revert back after the finance check', 'ask', 'ask'),
        ("approve, but I don't not want a change in the budget", 'ask | approve', 'ask'),
        ('nein, switch to C', 'switch to=C', 'rb'),
        ('Kindly effect the following changes: the timeline must be preponed by one month', 'changes', 'rb'),
        ('I am agree, approve', 'approve', 'ask'),
        ('ok bas approve', 'approve', 'ask'),
        ('si approve', 'approve', 'act'),
        ('yalla runner-up', 'runner-up', 'act'),
        ('go with the runner-up idea', 'runner-up', 'rb'),
        ('approve A not B', 'approve', 'ask'),
        ('Dear team,\nI reviewed the proposal. Please approve it as it is.\nRegards,\nFatima', 'approve', 'rb'),
        ('Dear team,\nThe proposal looks nice but the budget section is wrong, it should be 40k per year. Ki'
         'ndly change.\nThanks',
         'changes', 'rb'),
        ('Genehmigt', 'approve | ask', 'ask'),
        ('Aprobado', 'approve | ask', 'ask'),
        ('\u043e\u0434\u043e\u0431\u0440\u044f\u044e', 'approve | ask', 'ask'),
        ('\u6279\u51c6', 'approve | ask', 'ask'),
        ("it's fine, approve, no changes", 'approve', 'rb'),
        ('switch C', 'switch to=C', 'act'),
        ('approve, thanks', 'approve', 'act'),
        ('changes: add a cost table to the one-pager', 'changes', 'rb'),
        ('--approve', 'approve', 'act'),
        ('{"action": "switch", "switch_to": "B"}', 'switch to=B', 'rb'),
        ('action: changes\nchanges: shorten section 4', 'changes', 'rb'),
        ('switch_to: C', 'switch to=C', 'rb'),
        ('- [x] approve', 'approve', 'rb'),
        ('approve # ship it', 'approve', 'rb'),
        ('switch [B]', 'switch to=B', 'rb'),
        ('changes:shorten section 4', 'changes', 'rb'),
        ('Reply `approve`', 'approve | ask', 'ask'),
        ('approve? what does the one-pager say', 'ask', 'ask'),
        ('switch B? what does it cost', 'ask | switch to=B', 'ask'),
        ('approve, but change section 4 to be shorter', 'changes | ask', 'ask'),
        ('switch to B, actually no, approve', 'ask | approve', 'ask'),
        ('maybe runner-up', 'ask | readback runner-up', 'ask'),
        ('approve # though section 4 is long', 'approve', 'rb'),
        ('approve if the cost is under 10k', 'ask', 'ask'),
        ('idk, approve', 'ask | readback approve', 'ask'),
        ('approve, publish all, ce', 'approve | ask', 'ask'),
        ('> I read your reply as: switch to architecture B.\nno, C', 'switch to=C | ask', 'rb'),
    ],
    'G14': [
        ('no, ce', 'ok pub=none ho=ce', 'act'),
        ('publish architecture, proposal, ce',
         'ok pub=architecture,proposal ho=ce | ok pub=proposal,architecture ho=ce | ok pub=architecture,prop'
         'osal,adr ho=ce | ok pub=architecture,adr,proposal ho=ce | ok pub=proposal,architecture,adr ho=ce |'
         ' ok pub=proposal,adr,architecture ho=ce | ok pub=adr,architecture,proposal ho=ce | ok pub=adr,prop'
         'osal,architecture ho=ce', 'act'),
        ('no publish, only ce', 'ok pub=none ho=ce', 'rb'),
        ("don't publish the proposal, publish the architecture, ce",
         'ok pub=architecture ho=ce | ok pub=architecture,adr ho=ce | ok pub=adr,architecture ho=ce', 'ask'),
        ('publish? not yet. ce', 'ok pub=none ho=ce | ask', 'rb'),
        ('publish all except proposal, none',
         'ok pub=architecture,adr ho=none | ok pub=adr,architecture ho=none', 'rb'),
        ("I'll publish it myself, handoff none", 'ok pub=none ho=none', 'rb'),
        ('publish nothing, speckit', 'ok pub=none ho=speckit', 'rb'),
        ('publish all but keep the proposal private, ce',
         'ok pub=architecture,adr ho=ce | ok pub=adr,architecture ho=ce', 'rb'),
        ('no need publish, none', 'ok pub=none ho=none', 'rb'),
        ('nein not publish, none', 'ok pub=none ho=none', 'rb'),
        ('publish maybe, ce', 'ask', 'ask'),
        ('publish all if CI passes, ce', 'ask', 'ask'),
        ('not un-publish', 'ask', 'ask'),
        ("I don't not want to publish", 'ask', 'ask'),
        ('table the publishing, ce for now', 'ask | ok pub=none ho=ce', 'ask'),
        ('revert back on publishing, handoff none', 'ask | ok pub=none ho=none', 'ask'),
        ('publish all \u2014 no wait, only the architecture. ce', 'ask', 'ask'),
        ('I would like to request that the proposal not be published. Architecture ok. Handoff: none.',
         'ok pub=architecture ho=none | ok pub=architecture,adr ho=none | ok pub=adr,architecture ho=none', 'ask'),
        ('We have decided not to publish at this stage; ce handoff please.', 'ok pub=none ho=ce', 'ask'),
        ('make it publish, ce', 'ok pub=all ho=ce', 'ask'),
        ('si publish all, ce', 'ok pub=all ho=ce', 'rb'),
        ('publish architecture only, not the proposal, not the ADR, speckit',
         'ok pub=architecture ho=speckit | ask', 'ask'),
        ('Kindly publish the architecture and the proposal; no handoff is required.',
         'ok pub=architecture,proposal ho=none | ok pub=proposal,architecture ho=none | ok pub=architecture,'
         'proposal,adr ho=none | ok pub=architecture,adr,proposal ho=none | ok pub=proposal,architecture,adr'
         ' ho=none | ok pub=proposal,adr,architecture ho=none | ok pub=adr,architecture,proposal ho=none | o'
         'k pub=adr,proposal,architecture ho=none', 'ask'),
        ('Hello team,\nPlease publish everything and prepare the Spec Kit handoff.\nThank you and have a nic'
         'e weekend,\nLi Wei',
         'ok pub=all ho=speckit', 'ask'),
        ('publish all, ce? no, speckit', 'ok pub=all ho=speckit | ask', 'rb'),
        ('publish all, handoff ce or speckit, you decide', 'ask', 'ask'),
        ('yalla publish all, none', 'ok pub=all ho=none', 'act'),
        ('khalas no publish, none', 'ok pub=none ho=none', 'rb'),
        ('publish all, spec kit', 'ok pub=all ho=speckit', 'rb'),
        ('publish kar do sab, none', 'ok pub=all ho=none | ask', 'ask'),
        ('no publicar, ce', 'ask | ok pub=none ho=ce', 'rb'),
        ('\u043d\u0435 \u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u0442\u044c, none',
         'ask | ok pub=none ho=none', 'rb'),
        ('\u4e0d\u8981\u53d1\u5e03, none', 'ask | ok pub=none ho=none', 'rb'),
        ('no handoff, publish all', 'ok pub=all ho=none', 'rb'),
        ('publish: yes. handoff: ce', 'ok pub=all ho=ce', 'rb'),
        ('publish: no. handoff: none', 'ok pub=none ho=none', 'rb'),
        ('prepone the publishing, do it now: all, ce', 'ok pub=all ho=ce | ask', 'ask'),
        ('Publish.', 'ok pub=all', 'act'),
        ('publish architecture, proposal', 'ok pub=architecture,proposal | ok pub=proposal,architecture', 'act'),
        ('publish=all,ce', 'ok pub=all ho=ce', 'rb'),
        ('--publish all --handoff ce', 'ok pub=all ho=ce', 'act'),
        ('publish -a', 'ok pub=all | ask', 'rb'),
        ('{"publish": true}', 'ok pub=all', 'rb'),
        ('{"publish": false, "handoff": "none"}', 'ok items=- ho=none', 'rb'),
        ('publish: true\nhandoff: speckit', 'ok pub=all ho=speckit', 'rb'),
        ('- [x] publish\n- [x] ce', 'ok pub=all ho=ce', 'rb'),
        ('- [x] publish architecture\n- [ ] publish proposal', 'ok pub=architecture', 'rb'),
        ('**publish**, ce', 'ok pub=all ho=ce', 'act'),
        ('`publish architecture`, `ce`', 'ok pub=architecture ho=ce', 'act'),
        ('publish all, ce # go', 'ok pub=all ho=ce', 'rb'),
        ('Reply `publish architecture`', 'ok pub=architecture | ask', 'rb'),
        ('publish adrs', 'ok pub=adr', 'act'),
        ('publish architecture + proposal, speckit',
         'ok pub=architecture,proposal ho=speckit | ok pub=proposal,architecture ho=speckit', 'act'),
        ('handoff: ce, publish: no', 'ok items=- ho=ce', 'rb'),
        ('publish all; handoff=none', 'ok pub=all ho=none', 'rb'),
        ('publish? where does it go', 'ask', 'ask'),
        ("no publish, I'll copy it myself, speckit", 'ok items=- ho=speckit', 'rb'),
        ('publish, actually no', 'ask | ok items=-', 'rb'),
        ('publish all, ce (not speckit)', 'ok pub=all ho=ce', 'rb'),
        ('publish nothing, handoff none', 'ok items=- ho=none', 'rb'),
        ('no, but send the handoff to ce', 'ok items=- ho=ce', 'rb'),
        ('publish all, ce, and also speckit', 'ask', 'ask'),
        ('approve, publish all, ce', 'ok pub=all ho=ce | ask', 'rb'),
        ('> I read your reply as: publish everything.\nno, only the architecture', 'ok pub=architecture | ask', 'ask'),
    ],
    'G2c': [
        ('OK.', 'confirm', 'act'),
        ('yes', 'confirm', 'act'),
        ('Looks good', 'confirm', 'act'),
        ('all correct', 'confirm', 'act'),
        ('Please change: the target is 3 hospitals, not 1', 'correct', 'rb'),
        ('ok but the budget is 50k not 20k', 'correct', 'rb'),
        ('Correct, except the ward count should be 12', 'correct', 'rb'),
        ('ok? no, the users are wrong, they are midwives', 'correct', 'rb'),
        ('not ok', 'ask', 'ask'),
        ('I am not agree with the ASSUMED items', 'ask', 'rb'),
        ('yes but let me check with my team tomorrow', 'ask', 'ask'),
        ('ok, I will revert back with corrections', 'ask', 'ask'),
        ('Confirm. But the ASSUMED budget is too high, reduce to 10k', 'correct', 'rb'),
        ('why do you assume only one hospital?', 'ask', 'ask'),
        ('prepone the pilot to March, rest ok', 'correct', 'rb'),
        ('Table the ASSUMED ones, confirm the STATED ones', 'ask', 'ask'),
        ("I don't not agree", 'ask | confirm', 'ask'),
        ('Fine, no change', 'confirm', 'rb'),
        ('No changes, all good', 'confirm', 'rb'),
        ('Nothing to correct', 'confirm', 'rb'),
        ('No notes from my side, kindly proceed', 'confirm', 'rb'),
        ('Mostly correct. The shift length is 12 hours, not 8.', 'correct', 'rb'),
        ('Dear team,\nI have reviewed the framing. Everything is in order except that the pilot ward is Ward'
         ' 5, not Ward 7.\nKind regards,\nMaria',
         'correct', 'rb'),
        ('ok bas, move forward', 'confirm', 'ask'),
        ('S\xed, correcto', 'confirm | ask', 'ask'),
        ("Oui c'est correct", 'confirm | ask', 'ask'),
        ('stimmt so', 'confirm | ask', 'ask'),
        ('\u0412\u0441\u0451 \u0432\u0435\u0440\u043d\u043e', 'confirm | ask', 'ask'),
        ('\u5bf9\u7684', 'confirm | ask', 'ask'),
        ('theek hai', 'confirm | ask', 'act'),
        ('tayeb, ok', 'confirm', 'act'),
        ('Please do the needful and remove the assumption about night shifts', 'correct', 'ask'),
        ('nothing is not correct', 'ask | confirm', 'rb'),
        ('ok, go ahead', 'confirm', 'act'),
        ('ok.', 'confirm', 'act'),
        ('ok, thanks', 'confirm', 'act'),
        ('yes, confirmed', 'confirm', 'act'),
        ('go ahead', 'confirm', 'act'),
        ('ok!', 'confirm', 'act'),
        ('The problem is shift swaps between hospitals, not within one.', 'correct', 'rb'),
        ('Correction: the users are charge nurses, not staff nurses.', 'correct', 'rb'),
        ('{"corrections": "users are charge nurses"}', 'correct', 'rb'),
        ('- [x] ok', 'confirm', 'rb'),
        ('ok (lgtm)', 'confirm', 'rb'),
        ('LGTM', 'confirm', 'act'),
        ('s/staff nurses/charge nurses/', 'correct', 'ask'),
        ('- ASSUMED budget is zero -> wrong, budget is 5k', 'correct', 'rb'),
        ('Reply `ok` to confirm', 'confirm | ask', 'ask'),
        ('corrections: users are charge nurses', 'correct', 'rb'),
        ('nothing to correct', 'confirm', 'rb'),
        ('all good, ship it', 'confirm', 'rb'),
        ('ok, but the budget is 5k not 0', 'correct | ask', 'rb'),
        ('mostly ok, one thing: drop the SMS assumption', 'correct | ask', 'rb'),
        ('ok I guess', 'ask | confirm', 'ask'),
        ('wait, let me reread', 'ask', 'ask'),
        ('no, the problem is wrong', 'ask | correct', 'ask'),
        ("don't confirm yet", 'ask', 'ask'),
        ('yes except the ASSUMED budget', 'ask | correct', 'rb'),
        ('ok # though ASSUMED item 2 is shaky', 'confirm | ask', 'rb'),
        ('ok, approve', 'confirm | ask', 'act'),
        ('> I read your reply as: correct the frame.\nno, just ok', 'confirm | ask', 'ask'),
    ],
    'G2f': [
        ('restore please', 'restore', 'act'),
        ('keep thanks', 'keep', 'act'),
        ('please restore', 'restore', 'act'),
        ('ok keep', 'keep', 'rb'),
        ('restore CONTEXT.md', 'restore', 'act'),
        ('no restore, keep', 'keep', 'rb'),
        ('not keep, restore', 'restore', 'rb'),
        ('restore, but keep the new glossary part', 'ask', 'ask'),
        ('no keep', 'ask', 'ask'),
        ("not restore, not keep, I'll fix by myself", 'ask', 'ask'),
        ("I don't not want restore", 'ask', 'ask'),
        ('Please do not make any restoration.', 'keep | ask', 'ask'),
        ('keep, no need restore', 'keep', 'rb'),
        ("keep the changes, it's fine", 'keep', 'rb'),
        ('put it back like before please', 'restore', 'rb'),
        ('revert back', 'ask | restore', 'rb'),
        ('I will revert back to you', 'ask', 'ask'),
        ('rakh do', 'keep | ask', 'ask'),
        ('behalten', 'keep | ask', 'ask'),
        ('garde-le', 'keep | ask', 'ask'),
        ('\u0432\u043e\u0441\u0441\u0442\u0430\u043d\u043e\u0432\u0438', 'restore | ask', 'ask'),
        ('\u6062\u590d', 'restore | ask', 'ask'),
        ('khalas keep', 'keep', 'act'),
        ('si restore', 'restore', 'rb'),
        ('Kindly restore the CONTEXT.md file to its original state.', 'restore', 'rb'),
        ('We would prefer that the modifications be retained.', 'keep | ask', 'ask'),
        ('keep my original', 'ask | restore', 'ask'),
        ('Hello, please restore the file as it was before framing. Our architect will be upset otherwise.\nT'
         'hanks,\nOmar',
         'restore', 'ask'),
        ('keep, thanks', 'keep', 'act'),
        ('keep CONTEXT.md', 'keep', 'act'),
        ('keep.', 'keep', 'act'),
        ('git checkout CONTEXT.md', 'restore | ask', 'ask'),
        ('- [x] restore', 'restore', 'rb'),
        ('keep # I like the new version', 'keep', 'rb'),
        ("restore # framing shouldn't touch my repo", 'restore', 'rb'),
        ('action: keep', 'keep', 'ask'),
        ('Reply `restore` to put CONTEXT.md back', 'restore | ask', 'ask'),
        ('roll back CONTEXT.md', 'restore', 'rb'),
        ('restore? what changed', 'ask', 'ask'),
        ("keep for now, I'll restore later", 'keep', 'rb'),
        ('restore, actually keep', 'ask | keep', 'ask'),
        ('not sure, restore?', 'ask', 'ask'),
        ("keep it, don't restore", 'keep', 'rb'),
        ("restore, don't keep the framing edits", 'restore', 'rb'),
        ('keep, but show me the diff', 'ask | keep', 'rb'),
        ("restore it # the kit wasn't supposed to change it", 'restore', 'rb'),
        ("please don't touch it", 'keep | ask', 'ask'),
        ('keep, ok', 'keep', 'rb'),
        ('restore, then go', 'restore | ask', 'rb'),
    ],
    'G4': [
        ('OK.', 'ok rescue=- confirm=-', 'act'),
        ('yes', 'ok rescue=- confirm=-', 'act'),
        ('rescue I-012: it is cheap to test', 'ok rescue=I-012 confirm=-', 'act'),
        ('rescue I-005: the union likes it', 'ok rescue=I-005 confirm=-', 'act'),
        ('rescue I-012: cheap\nrescue I-020: unique', 'ok rescue=I-012,I-020 confirm=-', 'act'),
        ('rescue I-012: small clinics need it', 'ok rescue=I-012 confirm=-', 'act'),
        ('rescue I-012 because the night nurses love it', 'ok rescue=I-012 confirm=-', 'rb'),
        ('no rescue', 'ok rescue=- confirm=-', 'rb'),
        ('no need rescue I-012', 'ok rescue=- confirm=-', 'rb'),
        ('rescue I-012? no', 'ok rescue=- confirm=- | ask', 'rb'),
        ('rescue I-012 (not sure)', 'ask', 'ask'),
        ('not I-012, rescue I-013: it is better', 'ok rescue=I-013 confirm=-', 'ask'),
        ('rescue I-012 not I-013', 'ok rescue=I-012 confirm=-', 'rb'),
        ("no no, don't rescue I-012, it was my mistake", 'ok rescue=- confirm=- | ask', 'rb'),
        ("ok, but rescue I-012: it's the only offline one", 'ok rescue=I-012 confirm=-', 'rb'),
        ('rescue I-099: good one', 'ask', 'ask'),
        ("I don't want to rescue anything, accept", 'ok rescue=- confirm=-', 'rb'),
        ('table the rescue for now, accept the shortlist', 'ok rescue=- confirm=- | ask', 'ask'),
        ('please to rescue I-012: it is the only idea for small clinics', 'ok rescue=I-012 confirm=-', 'rb'),
        ('I want save I-012, the reason is the cost is low', 'ok rescue=I-012 confirm=-', 'rb'),
        ('rescue I-012: not expensive, not complicated', 'ok rescue=I-012 confirm=-', 'act'),
        ('rescue I-012, I think', 'ask | readback ok rescue=I-012', 'rb'),
        ('I-012 rescue kar do, reason: patients like it', 'ask | ok rescue=I-012', 'ask'),
        ('ok bas, rescue I-007: small clinics need', 'ok rescue=I-007 confirm=-', 'rb'),
        ('rescata I-012 por favor: es barato', 'ask | ok rescue=I-012', 'ask'),
        ('Kindly rescue idea I-012 as it aligns with our strategic priorities.', 'ok rescue=I-012 confirm=-', 'rb'),
        ('Dear team,\nPlease rescue I-012 (the ward managers requested it). The rest is fine.\nRegards,\nNad'
         'ia',
         'ok rescue=I-012 confirm=-', 'rb'),
        ('I-012 is good, rescue it', 'ok rescue=I-012 confirm=-', 'rb'),
        ('rescue nothing', 'ok rescue=- confirm=-', 'rb'),
        ('rescue I-012: the reason is we cannot not have an offline option', 'ok rescue=I-012 confirm=-', 'act'),
        ('si ok', 'ok rescue=- confirm=-', 'act'),
        ('rescue I-12: it is cheap', 'ask | ok rescue=I-012', 'ask'),
        ('revert back on the rescue later', 'ask', 'ask'),
        ('ok.', 'ok rescue=- confirm=-', 'act'),
        ('ok, thanks', 'ok rescue=- confirm=-', 'act'),
        ('rescue i-012: cheap to test', 'ok rescue=I-012 confirm=-', 'act'),
        ('Rescue I-005: it deletes a step', 'ok rescue=I-005 confirm=-', 'act'),
        ('confirm I-004, rescue I-012: cheap', 'ok rescue=I-012 confirm=I-004', 'rb'),
        ('rescue=I-012', 'ask', 'rb'),
        ('rescue I012: cheap', 'ok rescue=I-012 confirm=-', 'ask'),
        ('rescue [I-012]: cheap', 'ok rescue=I-012 confirm=-', 'rb'),
        ('rescue `I-012`: cheap', 'ok rescue=I-012 confirm=-', 'rb'),
        ("--rescue I-012 --reason 'cheap to test'", 'ok rescue=I-012 confirm=-', 'rb'),
        ('rescue:\n  - id: I-012\n    reason: cheap', 'ok rescue=I-012 confirm=-', 'ask'),
        ('- [x] rescue I-012: cheap', 'ok rescue=I-012 confirm=-', 'rb'),
        ('rescue I-012 because it is cheap', 'ok rescue=I-012 confirm=-', 'rb'),
        ('rescue I-012 (cheap to test)', 'ok rescue=I-012 confirm=-', 'rb'),
        ('rescue I-012: cheap # my favourite', 'ok rescue=I-012 confirm=-', 'rb'),
        ('ok # shortlist looks right', 'ok rescue=- confirm=-', 'rb'),
        ('Reply `ok` to accept the shortlist as it is.', 'ok rescue=- confirm=- | ask', 'ask'),
        ('rescue I-012: cheap, rescue I-020: novel, rescue I-025: fun', 'ask', 'ask'),
        ('rescue I-099: cheap', 'ask', 'ask'),
        ('confirm=I-004', 'ok rescue=- confirm=I-004', 'rb'),
        ('clear I-004 # judge was wrong', 'ok rescue=- confirm=-', 'rb'),
        ('rescue I-012? is it worth it', 'ask', 'ask'),
        ('ok, but rescue I-012: cheap', 'ok rescue=I-012 confirm=- | ask', 'rb'),
        ('rescue I-012: cheap. Actually no, ok as is', 'ask | ok rescue=- confirm=-', 'rb'),
        ('not I-012, rescue I-020: novel', 'ok rescue=I-020 confirm=-', 'ask'),
        ('idk, rescue I-012: cheap', 'ask | readback ok rescue=I-012 confirm=-', 'ask'),
        ('no rescue for I-012', 'ok rescue=- confirm=-', 'ask'),
        ("confirm I-004? it's the SMS one", 'ask', 'ask'),
        ('confirm I-004 (dup of I-012)', 'ok rescue=- confirm=I-004', 'rb'),
        ("clear I-004, don't kill it", 'ok rescue=- confirm=-', 'rb'),
        ('ok, keep I-003', 'ask | ok rescue=- confirm=-', 'ask'),
        ('rescue I-012: cheap, kill I-004', 'ask | ok rescue=I-012 confirm=I-004', 'ask'),
    ],
    'G5': [
        ('keep I-003, keep I-007', 'ok kill=-', 'act'),
        ('ok thanks', 'ok kill=-', 'act'),
        ('kill I-003\nkeep I-007', 'ok kill=I-003', 'act'),
        ('no need kill I-003', 'ok kill=-', 'rb'),
        ('kill I-003 (dup of I-011)', 'ok kill=I-003', 'rb'),
        ("kill I-003, the reason is it's same like I-011", 'ok kill=I-003', 'rb'),
        ('nein, not I-003, kill I-007', 'ok kill=I-007', 'rb'),
        ("I don't not want to kill I-003", 'ask | readback ok kill=I-003', 'ask'),
        ('kill I-003 because is not differentiated, not unique', 'ok kill=I-003', 'rb'),
        ('keep I-003: it is not duplicate', 'ok kill=-', 'rb'),
        ("don't kill any", 'ok kill=-', 'rb'),
        ('kill I-003, revert back on I-007', 'ok kill=I-003 | ask', 'rb'),
        ('I-003 no, I-007 yes', 'ask', 'ask'),
        ('I am agree to kill I-003', 'ok kill=I-003', 'rb'),
        ('please to kill I-007', 'ok kill=I-007', 'rb'),
        ('ok bas kill I-003', 'ok kill=I-003', 'ask'),
        ('khalas kill I-007', 'ok kill=I-007', 'act'),
        ('mata I-003', 'ask | ok kill=I-003', 'ask'),
        ('Kindly proceed with the elimination of I-003; I-007 may be retained.', 'ok kill=I-003', 'ask'),
        ('Dear all,\nAfter discussing with the team we decided: kill I-003. Keep I-007 please.\nBR,\nDmitri',
         'ok kill=I-003', 'ask'),
        ('kill I-003 and park I-007', 'ok kill=I-003', 'rb'),
        ('kill nobody', 'ok kill=-', 'ask'),
        ('table I-007, kill I-003', 'ok kill=I-003 | ask', 'ask'),
        ('kill I-003: not unique', 'ok kill=I-003', 'rb'),
        ('kill I-003\nkill I-007', 'ok kill=I-003,I-007', 'act'),
        ('kill I-003.', 'ok kill=I-003', 'act'),
        ('ok, thanks', 'ok kill=-', 'act'),
        ('kill I-007; keep I-003', 'ok kill=I-007 keep=I-003', 'act'),
        ('yes', 'ask | ok kill=- | readback', 'act'),
        ('kill:I-003', 'ok kill=I-003', 'act'),
        ('kill=I-003', 'ok kill=I-003', 'rb'),
        ('kill [I-003]', 'ok kill=I-003', 'rb'),
        ('kill `I-003`', 'ok kill=I-003', 'act'),
        ('kill: [I-003]\nkeep: [I-007]', 'ok kill=I-003 keep=I-007', 'rb'),
        ('- [x] kill I-003\n- [ ] kill I-007', 'ok kill=I-003', 'rb'),
        ('kill I-003 # dup of I-007', 'ok kill=I-003', 'rb'),
        ('For each K4 candidate: `kill I-003` or `keep I-007`', 'ok kill=I-003 keep=I-007 | ask', 'rb'),
        ('kill I-003, actually keep it', 'ask | ok kill=-', 'ask'),
        ('kill I-003 because it duplicates I-007', 'ok kill=I-003', 'rb'),
        ("keep I-003 (don't kill it, it's the only SMS idea)", 'ok kill=- | ask', 'rb'),
        ('kill I-003 - wait, no', 'ask | ok kill=-', 'ask'),
        ("keep both, don't kill anything", 'ok kill=-', 'rb'),
        ('kill I-003 but not I-007', 'ok kill=I-003', 'rb'),
        ('ok, but kill I-003', 'ok kill=I-003 | ask', 'rb'),
        ("kill I-003 if it's really a dup", 'ask', 'ask'),
        ("Sam (Slack): 'kill I-003'", 'ask', 'ask'),
        ('kill I-003, publish all', 'ok kill=I-003 | ask', 'rb'),
        ('> I read your reply as: kill I-003 and I-007.\nno, only I-003', 'ok kill=I-003 | ask', 'ask'),
    ],
    'G9': [
        ('Passed.', 'passed', 'act'),
        ('Missed.', 'missed', 'act'),
        ('passed: 14 of 20 nurses used it', 'passed', 'act'),
        ('missed: 3 of 20', 'missed', 'act'),
        ('inconclusive: only 5 nurses answered', 'inconclusive', 'act'),
        ('PASSED - 16/20', 'passed', 'act'),
        ('passed, 70% of swaps done in the app', 'passed', 'act'),
        ('missed, 2 of 10 signups', 'missed', 'act'),
        ('inconclusive (the ward was closed for a week)', 'inconclusive', 'rb'),
        ('passed? no. missed, 4 of 20', 'missed', 'rb'),
        ("missed but don't kill the idea please", 'ask', 'ask'),
        ('almost passed, 9 of 10 target', 'ask | readback missed', 'ask'),
        ('passed I think', 'ask', 'rb'),
        ('we passed it to the manager', 'ask', 'ask'),
        ("I don't not think it passed", 'ask', 'ask'),
        ('not missed, passed with 12 of 20', 'passed', 'rb'),
        ('passed (not sure about the counting)', 'ask', 'ask'),
        ('missed? no, inconclusive', 'inconclusive', 'rb'),
        ("Let's table the result, it's not ready", 'ask', 'ask'),
        ('inconclusive? no, passed 14/20', 'passed', 'rb'),
        ('missed: we did not reach 10 signups', 'missed', 'rb'),
        ('result: passed, 11 with a target of 10', 'passed', 'rb'),
        ('inconclusive, not enough nurses', 'inconclusive', 'rb'),
        ('Nahi hua pass, sirf 3 of 10', 'ask | missed', 'ask'),
        ('bestanden, 15 von 20', 'ask | passed', 'ask'),
        ('\xe9chou\xe9, 2 sur 10', 'ask | missed', 'ask'),
        ('\u043d\u0435 \u043f\u0440\u043e\u0448\u0435\u043b, 2 \u0438\u0437 10', 'ask | missed', 'ask'),
        ('\u901a\u8fc7\u4e86, 14/20', 'ask | passed', 'ask'),
        ('Dear team,\nThe probe was completed last week. Result: PASSED (17 of 20 nurses swapped at least on'
         'ce).\nRegards,\nAisha',
         'passed', 'rb'),
        ('Kindly record the result as inconclusive; the pilot ward was closed.', 'inconclusive', 'rb'),
        ('The target was 10, we got 4. So missed.', 'missed', 'rb'),
        ('failed, 1 of 10', 'missed', 'rb'),
        ('khalas missed', 'missed', 'act'),
        ('yalla passed 15/20', 'passed', 'act'),
        ('si, passed', 'passed', 'rb'),
        ('ok passed', 'passed', 'rb'),
        ('yes', 'ask', 'ask'),
        ('passed: 14 of 20 nurses swapped a shift', 'passed', 'act'),
        ('missed: 2 of 20 signed up', 'missed', 'act'),
        ('inconclusive: only 5 replies', 'inconclusive', 'act'),
        ('missed, 3/20', 'missed', 'act'),
        ('passed, 18/20 used it', 'passed', 'act'),
        ('inconclusive.', 'inconclusive', 'act'),
        ('result: PASSED', 'passed', 'rb'),
        ('result=missed', 'missed', 'rb'),
        ('{"result": "INCONCLUSIVE", "note": "n=5"}', 'inconclusive', 'rb'),
        ("--result passed --note '14/20'", 'passed', 'rb'),
        ('- [x] passed', 'passed', 'rb'),
        ('- [ ] passed\n- [x] missed', 'missed', 'rb'),
        ('**MISSED**', 'missed', 'act'),
        ('`inconclusive`', 'inconclusive', 'act'),
        ('passed # 14/20, above the 10 threshold', 'passed', 'rb'),
        ('missed # 2/20', 'missed', 'rb'),
        ('Reply `passed`, `missed` or `inconclusive`', 'ask', 'ask'),
        ('Reply `passed` with the observed numbers: 14/20', 'passed | ask', 'rb'),
        ('PASS', 'passed', 'ask'),
        ('FAIL', 'missed | ask', 'rb'),
        ('\u2705 passed', 'passed', 'rb'),
        ('passed (14/20 > 10)', 'passed', 'rb'),
        ('missed by a mile: 1/20', 'missed', 'act'),
        ('passed? the numbers were borderline', 'ask', 'ask'),
        ("missed? I'm not sure", 'ask', 'ask'),
        ('passed, but only barely (11/20)', 'passed', 'rb'),
        ('passed, actually inconclusive', 'ask | inconclusive', 'ask'),
        ('not missed, inconclusive: 5 replies', 'inconclusive', 'rb'),
        ("I don't know yet, still waiting on numbers", 'ask', 'ask'),
        ("missed (don't kill it though)", 'ask', 'ask'),
        ('passed - no wait, missed', 'ask | missed', 'ask'),
        ('inconclusive, not missed', 'inconclusive', 'rb'),
        ('passed 14/20 # Sam ran the test', 'passed', 'rb'),
        ('not inconclusive - it passed', 'passed', 'rb'),
        ('passed, approve', 'passed | ask', 'rb'),
        ('> I read your reply as: MISSED.\nno, inconclusive', 'inconclusive | ask', 'rb'),
    ],
    'GB': [
        ('raise to 400 please', 'raise cap=400', 'act'),
        ('stop thanks', 'stop', 'act'),
        ('raise to 245', 'raise cap=245', 'act'),
        ('no raise', 'stop | ask', 'ask'),
        ('raise to 300 but after the meeting', 'ask', 'ask'),
        ('no stop, raise to 300', 'raise cap=300 | ask', 'rb'),
        ('We would like to request that the budget not be increased.', 'stop | ask', 'ask'),
        ('raise to 500, no, 300', 'ask', 'ask'),
        ('raise to 200 or 250, as you think', 'ask', 'ask'),
        ('raise to 300 requests or stop if it is more than 50 dollars', 'ask', 'ask'),
        ('raise to 300 as the card says 65 more are needed', 'raise cap=300', 'rb'),
        ('please to raise until 300', 'raise cap=300 | ask', 'ask'),
        ('increase the budget to 300 requests', 'raise cap=300', 'rb'),
        ('make it 300', 'raise cap=300 | ask', 'rb'),
        ('okay raise, 300', 'raise cap=300', 'rb'),
        ('bas, stop here', 'stop', 'rb'),
        ('yalla raise to 300', 'raise cap=300', 'act'),
        ('si raise to 300', 'raise cap=300', 'rb'),
        ('nein, stop', 'stop', 'rb'),
        ('Kindly increase the cap to 300 requests.', 'raise cap=300', 'rb'),
        ("I don't want to spend more, stop", 'stop', 'rb'),
        ('Hi, please raise to 300. Thanks!\nSent from my iPhone', 'raise cap=300', 'rb'),
        ('Dear team,\nPlease raise the limit to 260 requests.\nBest,\nJuan', 'raise cap=260', 'rb'),
        ('raise to 500', 'raise cap=500', 'act'),
        ('raise to 300, thanks', 'raise cap=300', 'act'),
        ('stop.', 'stop', 'act'),
        ('raise_to=300', 'raise cap=300', 'rb'),
        ('--raise-to 300', 'raise cap=300', 'ask'),
        ('--max-calls 300', 'raise cap=300', 'rb'),
        ('{"raise_to": 300}', 'raise cap=300', 'rb'),
        ('{"stop": true}', 'stop', 'rb'),
        ('raise_to: 300', 'raise cap=300', 'act'),
        ('- [x] stop', 'stop', 'rb'),
        ('`raise to 300`', 'raise cap=300', 'act'),
        ('raise to 300 # should be enough', 'raise cap=300', 'rb'),
        ('raise to 3e2', 'raise cap=300 | ask', 'ask'),
        ('raise to 300 requests', 'raise cap=300', 'rb'),
        ('Reply `raise to <number of requests>` to continue', 'ask', 'ask'),
        ('stop # too expensive', 'stop', 'rb'),
        ('raise to 300 (from 200)', 'raise cap=300', 'rb'),
        ('raise to 300? how much is that', 'ask', 'ask'),
        ('raise? what does a request cost', 'ask', 'ask'),
        ('raise to 300, not 3000', 'raise cap=300', 'rb'),
        ('no, stop', 'stop', 'rb'),
        ('idk, raise to 300', 'ask | readback raise cap=300', 'ask'),
        ('not 300. raise to 250', 'raise cap=250', 'rb'),
        ('raise to 300, continue', 'raise cap=300', 'rb'),
        ('> I read your reply as: raise the cap to 3000 requests.\nno, 300', 'raise cap=300 | ask', 'rb'),
    ],
    'GX': [
        ('continue thanks', 'continue', 'act'),
        ('stop please', 'stop', 'act'),
        ('Reframe.', 'reframe', 'act'),
        ('ok stop', 'stop', 'rb'),
        ('no continue, stop', 'stop | ask', 'rb'),
        ('reframe? no, continue', 'continue', 'rb'),
        ('continue but change the question little bit', 'ask', 'ask'),
        ('We would prefer that the effort not be stopped.', 'continue | ask', 'ask'),
        ('khalas', 'ask', 'ask'),
        ("I don't not want to continue", 'ask', 'ask'),
        ('stop the reframe, continue', 'continue | ask', 'ask'),
        ('reframe and continue', 'ask', 'ask'),
        ('table it', 'ask', 'ask'),
        ('Kindly continue with the current framing.', 'continue', 'rb'),
        ('nein, nicht stoppen, weiter', 'ask | continue', 'ask'),
        ('si continue', 'continue', 'rb'),
        ('reframe, the problem is about the night shift, not the weekend', 'reframe', 'rb'),
        ('revert back later', 'ask', 'ask'),
        ('Dear team,\nAfter the review we decided to stop the whole effort. Thank you for the work.\nRegards'
         ',\nHassan',
         'stop', 'ask'),
        ('continue, the synthesis said stop but I disagree', 'continue', 'rb'),
        ('arr\xeater', 'ask | stop', 'ask'),
        ('\u043f\u0440\u043e\u0434\u043e\u043b\u0436\u0430\u0439', 'ask | continue', 'ask'),
        ('\u7ee7\u7eed', 'ask | continue', 'ask'),
        ('neither stop nor reframe', 'ask | continue', 'ask'),
        ('continue, thanks', 'continue', 'act'),
        ('stop.', 'stop', 'act'),
        ('Reframe', 'reframe', 'act'),
        ('- [x] reframe', 'reframe', 'rb'),
        ('- [ ] stop\n- [x] continue', 'continue', 'rb'),
        ('**stop**', 'stop', 'act'),
        ('continue # the kill condition is too strict', 'continue', 'rb'),
        ('reframe # the problem is wrong', 'reframe', 'rb'),
        ('continue (not stop)', 'continue', 'rb'),
        ('stop && reframe', 'ask', 'ask'),
        ('stop # not worth it', 'stop', 'rb'),
        ('stop? what happens to my ideas', 'ask', 'ask'),
        ("don't reframe", 'ask', 'ask'),
        ('continue, but reframe the question slightly', 'ask | reframe', 'ask'),
        ('maybe stop', 'ask', 'ask'),
        ('stop for now', 'stop | ask', 'rb'),
        ('continue? I think so', 'ask | continue', 'rb'),
        ('continue, actually stop', 'ask | stop', 'ask'),
        ('continue if the probe is cheap', 'ask', 'ask'),
        ("continue, don't stop", 'continue', 'rb'),
        ('never stop, continue', 'continue', 'rb'),
        ('continue, ok', 'continue', 'rb'),
        ('stop, no publish', 'stop | ask', 'rb'),
    ],
}
RESIDUAL = {
    ('G2c', _key('I am not agree with the ASSUMED items')): 'correct',
    ('G4', _key('rescue=I-012')): 'ok rescue=I-012 confirm=-',
    ('G9', _key('passed I think')): 'passed',
}


def matches(intent, got):
    """The reading matches one alternative of the intent; `readback [<reading>]` matches only a read-back."""
    for alt in intent.split(" | "):
        parts = alt.split()
        if parts[0] == "readback":
            if got.get("how") == "rb" and (len(parts) == 1 or q.matches(" ".join(parts[1:]), got)):
                return True
        elif q.matches(alt, got):
            return True
    return False


class GateCorpusY(tl.EngineTestCase):
    variant = "product"
    make_ctx = s.GateCorpusS.make_ctx  # the Q fixtures on the product variant
    read = w.GateCorpusW.read

    def check(self, gate):
        with mock.patch("os.fsync", lambda fd: None):  # a run per row, in a temp dir: no need to reach the disk
            for n, (reply, intent, how) in enumerate(ROWS[gate]):
                with self.subTest(gate=gate, reply=reply):
                    got = self.read(gate, reply, n)
                    if how == "ask":
                        self.assertEqual(got["r"], "ask", "pinned as asked again, got %r" % (got,))
                    else:
                        want = RESIDUAL.get((gate, _key(reply)), intent)
                        self.assertEqual(got["how"], how, "want %s %s, got %r" % (how, want, got))
                        self.assertTrue(matches(want, got), "want %s %s, got %r" % (how, want, got))

    def test_review_replies(self):
        """Replies from the review that the corpus rows do not pin the way the reader got them wrong: G12 `ok reject`
        without a number, `reject 3, rest ok` (the rest accepted), the reason hint that says brackets, G14 lists that
        keep the proposal alone with no handoff, and G0 privacy requests with a German compound."""
        rows = (("G12", "ok reject", None), ("G12", "reject 3, rest ok", "ok acc=all rej=0003"),
                ("G12", "reject 3 because we use push, not SMS", None), ("G14", "only the proposal, none", None),
                ("G14", "just the proposal, handoff none", None), ("G0k", "keine Websuche\ngo", None),
                ("G0k", "ohne Websuche bitte, los geht's", None))
        with mock.patch("os.fsync", lambda fd: None):
            for n, (gate, reply, intent) in enumerate(rows):
                with self.subTest(gate=gate, reply=reply):
                    got = self.read(gate, reply, 800 + n)
                    if intent is None:
                        self.assertEqual(got["r"], "ask", got)
                        self.assertNotIn("put a reason after", got.get("why") or "")
                    else:
                        self.assertEqual(got["how"], "rb", got)
                        self.assertTrue(matches(intent, got), got)

    def test_pinned_rows_are_rows(self):
        keys = set((g, _key(r[0])) for g in ROWS for r in ROWS[g])
        self.assertEqual(set(RESIDUAL) - keys, set())
        self.assertEqual(set(r[2] for g in ROWS for r in ROWS[g]) - {"act", "rb", "ask"}, set())


def _add(gate):
    setattr(GateCorpusY, "test_%s" % gate.lower(), lambda self: self.check(gate))


for _gate in ROWS:
    _add(_gate)


class Floods(unittest.TestCase):
    """The reader stays linear: a 20000-character reply is read, and checked for a documented form, in under 3 s."""

    def test_linear(self):
        n = 20000
        floods = (
            ("G11", "B" + "." * n, {"choice": "B"}), ("G11", "please " * (n // 7) + "B", {"choice": "B"}),
            ("G11", "B " + "ty." * (n // 3), {"choice": "B"}), ("G11", "go with" + " " * n + "B", {"choice": "B"}),
            ("G11", "B + steal A: x" + " " * n + "y", {"choice": "B"}),
            ("G13", "changes: " + "will send " * (n // 10), {"action": "changes"}),
            ("G4", "rescue I-012: " + "only if " * (n // 8), {"rescue": [{"id": "I-012", "reason": "x"}]}),
            ("G9", "passed, " + "14 of 20 " * (n // 9), {"result": "PASSED"}),
            ("G9", "passed" + " Ab" * (n // 3), {"result": "PASSED"}),
            ("G5", "- [ ] kill I-003\n" * (n // 17), {}), ("G5", "- [x] kill I-003\n" * (n // 17), {}),
            ("G13", "no need " * (n // 8) + "switch", {}), ("G12", "reject 3, rest ok " * (n // 18), {}),
            ("G2c", "prepone " * (n // 8), {}), ("G1", "I don't not want " * (n // 17), {}),
            ("G0", "topic: " + "never mind " * (n // 11) + "\ngo", None),
            ("G0", "\nlooking forward to x" * (n // 20), None), ("G0", "internet " * (n // 9), None),
            ("GB", "raise to 300 but after " * (n // 23), {}))
        for gid, text, ans in floods:
            t0 = time.perf_counter()
            gates.parse_reply(gid, text, None, [])
            if ans is None:
                gates.parse_kickoff(text, [])
            else:
                gates.canonical(None, gid, dict(ans, reply=text))
            self.assertLess(time.perf_counter() - t0, 10.0, (gid, text[:24]))


class Kickoff(unittest.TestCase):
    """Two kickoff variants beside the corpus rows: a privacy request in transliterated Russian is asked about, and an
    email closing line before `go` is no seed idea (a seed that only starts like a closing stays one)."""

    def test_privacy_and_closing_lines(self):
        for text, ideas, kinds in (
                ("bez interneta, tolko lokalno\ngo", ["bez interneta, tolko lokalno"], ["privacy"]),
                ("- nurses swap shifts\nLooking forward to the results.\ngo", ["nurses swap shifts"], []),
                ("- nurses swap shifts\nThanks in advance!\ngo", ["nurses swap shifts"], []),
                ("- a\nHave a great onboarding for new nurses\ngo", ["a", "Have a great onboarding for new nurses"],
                 [])):
            with self.subTest(text=text):
                doubts = []
                self.assertEqual(gates.parse_kickoff(text, doubts)["seeds"]["ideas"], ideas)
                self.assertEqual([d[0] for d in doubts], kinds)


if __name__ == "__main__":
    unittest.main()
