"""Phase P (PA-gate-reader): the gate-reply corpus (KIT_SPEC 4.12, 6.10).

Every row is one reply at one gate and the reading it must get, driven through the real entry points
(gates.prepare_answer -> validate -> apply; the v1-run offer through pipeline.answer_gate). The table holds every
corpus reply the 2.1.0 audit tree misread, plus every fourth reply it read as intended, so a change that breaks a
documented form fails here too. Left out: 'Publish. No, really.' at G14, still read as no publish (a bare `no` after a
statement refuses it, as 'Publish? No.' does).

Intent: alternatives separated by " | ", each `<reading> key=value ...`. `ask` means the reply is asked again (never an
unrequested action). Fixtures: G5 candidates I-003 and I-007; G11 suggestion A; G12 ADRs 1-3; G13 arch A with
runner-up I-002.
"""

import os
import sys
import unittest
from unittest import mock

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "fixtures", "engine"))
import engine_testlib as tl  # noqa: E402
import test_r_ra_gate_corpus_q as q  # noqa: E402

from ublib.engine import gates, pipeline, render_arch  # noqa: E402
from ublib.engine import state as st  # noqa: E402

MATRIX = {"leader": "A", "leader_status": "clear", "candidates": [
    {"label": "A", "score": 4.0, "rank": 1, "veto": "none"}, {"label": "B", "score": 3.5, "rank": 2, "veto": "none"},
    {"label": "C", "score": 3.0, "rank": 3, "veto": "none"}]}
ADR = {"context": "c", "options": [{"name": "opt one", "pros": ["p"], "cons": ["c"]},
                                   {"name": "opt two", "pros": ["p"], "cons": ["c"]}],
       "chosen": "opt one", "rationale": "r", "consequences": ["x"], "risks": [], "qg": []}

ROWS = {
    'G0k': [
        ('yes go', 'start seeds=0'),
        ('\u201cgo\u201d', 'start seeds=0'),
        ('**go**', 'start seeds=0'),
        ('sounds good \U0001f44d', 'start seeds=0'),
        ('Yes \u2014 standard mode, guided.', 'start seeds=0 mode=standard autopilot=guided'),
        ('switch to deep mode and go', 'start seeds=0 mode=deep | ask'),
        ('use deep mode', 'start seeds=0 mode=deep | ask'),
        ('Can we do quick instead?', 'start seeds=0 mode=quick | ask'),
        ('wait, change the mode to deep', 'start seeds=0 mode=deep | ask'),
        ('no, make it deep', 'start seeds=0 mode=deep | ask'),
        ('private please, go', 'start seeds=0 private=True vendors=off'),
        ('private mode', 'start seeds=0 private=True vendors=off | ask'),
        ('private mode please', 'start seeds=0 private=True vendors=off | ask'),
        ('keep it private', 'start seeds=0 private=True vendors=off | ask'),
        ('Make it private and go', 'start seeds=0 private=True vendors=off | ask'),
        ('vendors: no', 'start seeds=0 vendors=off'),
        ('web: no, vendors: no', 'start seeds=0 web=off vendors=off | ask'),
        ('web: no / vendors: no', 'start seeds=0 web=off vendors=off | ask'),
        ('vendors: off', 'start seeds=0 vendors=off | ask'),
        ('web: off', 'start seeds=0 web=off | ask'),
        ('vendors: none', 'start seeds=0 vendors=off | ask'),
        ('vendors no', 'start seeds=0 vendors=off | ask'),
        ('no web search', 'start seeds=0 web=off | ask'),
        ('no other vendors please', 'start seeds=0 vendors=off | ask'),
        ('Go, but no web search', 'start seeds=0 web=off | ask'),
        ("don't send my idea to other vendors", 'start seeds=0 vendors=off | ask'),
        ('My idea: nurses trade shifts by text\ngo', 'start seeds=1'),
        ('hold on', 'ask'),
        ('no thanks', 'ask'),
        ('not yet, let me think', 'ask'),
        ('Hmm, not sure', 'ask'),
        ('Actually, no.', 'ask'),
        ('Probably not.', 'ask'),
        ("Let's not.", 'ask'),
        ('not today', 'ask'),
        ('wait, I have questions first', 'ask'),
        ('private please', 'start seeds=0 private=True vendors=off'),
        ('web: no, vendors: no\ngo', 'start seeds=0 web=off vendors=off'),
        ('web: maybe', 'ask'),
        ('vendors: disabled', 'start seeds=0 vendors=off'),
        ('- a shift-swap board\nkeep my idea private', 'ask | start seeds=1 private=True vendors=off'),
    ],
    'G0v1': [
        ('ok', 'extend'),
        ('go, deep mode', 'extend'),
        ('Yep, extend.', 'extend | ask'),
        ('stop', 'stop'),
        ('nope', 'stop'),
        ('no thanks', 'stop'),
        ("don't extend", 'stop'),
        ('stop \u2014 too expensive', 'stop'),
        ("that's enough, stop", 'stop'),
        ('No need, thanks', 'stop | ask'),
        ('wait', 'ask | stop'),
        ('hmm not sure', 'ask'),
        ('Not sure what extend means', 'ask'),
        ("I don't understand", 'ask'),
        ('no idea what a v1 run is', 'ask'),
        ('\U0001f914', 'ask'),
        ("Let's not.", 'stop | ask'),
        ('not sure', 'ask'),
    ],
    'G1': [
        ('DONE', 'done'),
        ('yep', 'done'),
        ("Done. Not my best work but it's there", 'done'),
        ('**done**', 'done'),
        ('okay, finished writing', 'done | ask'),
        ('skip, no ideas', 'skip'),
        ('not done, skip', 'skip'),
        ('i have none, skip it', 'skip'),
        ('not quite done', 'ask'),
        ('done? not quite', 'ask'),
        ('almost done', 'ask'),
        ('nearly done, 2 more mins', 'ask'),
        ('done in 5 minutes', 'ask'),
        ("I'll be done soon", 'ask'),
        ('skip: no ideas yet', 'skip'),
        ('skip it', 'skip'),
        ('Done? Probably not.', 'ask'),
        ('Skip? Actually, no.', 'ask'),
        ('Actually, no.', 'ask'),
        ('Done? Not even close, still writing.', 'ask'),
        ('Skip? Probably not, give me a minute.', 'ask'),
    ],
    'G10': [
        ('LGTM', 'confirm'),
        ('all good \U0001f44d', 'confirm'),
        ('that works for me', 'confirm'),
        ('\u201cok\u201d', 'confirm'),
        ('Great, proceed', 'confirm'),
        ('ok, continue', 'confirm | ask'),
        ('Correct, move on', 'confirm | ask'),
        ('Yes, next', 'confirm | ask'),
        ('Good, carry on', 'confirm | ask'),
        ('all set', 'confirm | ask'),
        ("we're good", 'confirm | ask'),
        ("that's accurate", 'confirm | ask'),
        ('The users are nurses, not doctors', 'correct'),
        ('Change the success metric to 20% fewer unfilled shifts', 'correct'),
        ('Correct? No. Users are nurses', 'correct'),
        ('hmm', 'ask'),
        ('Drivers look right', 'confirm'),
        ('Quality goals are fine', 'confirm | ask'),
        ('the quality goals and constraints look right', 'confirm | ask'),
        ('Weights look good', 'confirm | ask'),
        ('Constraints are correct', 'confirm | ask'),
        ('hard constraints ok', 'confirm | ask'),
        ('The scenarios are fine, thanks', 'confirm | ask'),
        ('No issues', 'confirm | ask'),
        ('No objections', 'confirm | ask'),
        ("correct, don't wait", 'confirm'),
        ('Please fix the drivers', 'correct'),
        ('Correct, but add more drivers', 'correct | ask'),
        ('ok, change the drivers', 'correct | ask'),
        ('Yes, but fix the frame', 'correct | ask'),
        ('please add more', 'correct | ask'),
        ('That is correct', 'confirm'),
        ('Spot on', 'confirm'),
        ('All correct', 'confirm'),
        ('Great', 'confirm | ask'),
        ('no notes', 'confirm | ask'),
    ],
    'G11': [
        ('yes, accept the recommendation', 'A'),
        ('B', 'B'),
        ('ok go with B', 'B'),
        ('Architecture B', 'B'),
        ('B \U0001f642', 'B'),
        ("B - it's cheaper", 'B'),
        ('B+steal', 'B'),
        ("Let's do B", 'B | ask'),
        ('B over C', 'B | ask'),
        ('B (the offline one)', 'B | ask'),
        ('B? Hmm, no.', 'ask'),
        ('B? Well, no. A', 'A | ask'),
        ('C? Honestly, no.', 'ask'),
        ('the second one', 'B | ask'),
        ('B? \U0001f44e', 'ask'),
        ('B? Probably not.', 'ask'),
        ('B? Rather not.', 'ask'),
        ("B? I'd rather not.", 'ask'),
        ('B? Maybe not.', 'ask'),
        ('B? Better not.', 'ask'),
        ('B? Not today.', 'ask'),
        ('B? Not really, no.', 'ask'),
        ('B? Actually, no.', 'ask'),
        ('B? Well, no.', 'ask'),
        ('B? Um, no.', 'ask'),
        ('B? Honestly, no.', 'ask'),
        ("B? Let's not.", 'ask'),
        ('B? Skip.', 'ask'),
        ('B? Skip it.', 'ask'),
        ('B? None.', 'ask'),
        ('B? Nothing.', 'ask'),
        ('B? No need.', 'ask'),
        ('B? Not needed.', 'ask'),
        ('B? No, thank you.', 'ask'),
        ('B? Not sure.', 'ask'),
        ('B. No, really.', 'B | ask'),
        ('A - no', 'ask'),
        ('C? No.', 'ask'),
        ('No, B.', 'B | ask'),
        ('...', 'ask'),
        ('The suggestion is fine, B was close', 'A | ask'),
        ('Sounds good (B was also nice)', 'A | ask'),
        ("I'd pick B because it can hold more traffic", 'B'),
        ('Go with C since we can stop the pipeline cleanly', 'C'),
        ("I'd choose A because it lets us pause jobs", 'A'),
    ],
    'G12': [
        ('LGTM', 'ok acc=all rej=-'),
        ('All accepted.', 'ok acc=all rej=- | ask'),
        ('accept 1 and 2', 'ok acc=0001,0002 rej=-'),
        ('accept 1-3', 'ok acc=0001,0002,0003 rej=- | ok acc=all rej=- | ask'),
        ('accept 1 2, reject 3', 'ok acc=0001,0002 rej=0003'),
        ('No to 3, yes to the rest', 'ok rej=0003 | ask'),
        ('reject: 3', 'ok rej=0003'),
        ('Reject #2 and #3', 'ok rej=0002,0003'),
        ('reject 2-3', 'ok rej=0002,0003 | ask'),
        ("reject 3 (don't want SMS)", 'ok rej=0003 | ask'),
        ('1 and 2 are fine, reject 3', 'ok acc=0001,0002 rej=0003 | ask'),
        ('reject 3? Hmm, no.', 'ask | ok rej=-'),
        ('reject 3? Well, no', 'ask | ok rej=-'),
        ('reject 3 and 4', 'ask'),
        ('reject 3? Probably not.', 'ok rej=- | ask'),
        ('reject 3? Rather not.', 'ok rej=- | ask'),
        ("reject 3? I'd rather not.", 'ok rej=- | ask'),
        ('reject 3? Maybe not.', 'ok rej=- | ask'),
        ('reject 3? Better not.', 'ok rej=- | ask'),
        ('reject 3? Not today.', 'ok rej=- | ask'),
        ('reject 3? Not sure.', 'ask | ok rej=-'),
        ('reject 3. Actually, no.', 'ok rej=- | ask'),
        ('reject 3, 2 is fine', 'ask | ok rej=0003'),
        ('reject 3 since it would stop us scaling', 'ok rej=0003'),
        ('reject 2, 3', 'ok rej=0002,0003'),
        ('reject 3-1', 'ask'),
    ],
    'G13': [
        ('**Approve**', 'approve'),
        ('ok', 'approve'),
        ('Great work, approved', 'approve'),
        ('Approve? Yes.', 'approve'),
        ('sign off', 'approve | ask'),
        ('signed off', 'approve | ask'),
        ('I sign off on it', 'approve | ask'),
        ('all set', 'approve | ask'),
        ("we're good", 'approve | ask'),
        ("Let's do it", 'approve | ask'),
        ('approve and publish', 'approve | ask'),
        ('approve and continue', 'approve | ask'),
        ('approve and move on', 'approve | ask'),
        ('approve and finalize', 'approve | ask'),
        ('The ADRs look good', 'approve | ask'),
        ('One-pager looks great', 'approve | ask'),
        ('Open questions are fine', 'approve | ask'),
        ("I'm happy with it", 'approve | ask'),
        ('shorten the exec summary', 'changes'),
        ('switch to B', 'switch to=B'),
        ('not yet', 'ask'),
        ('?', 'ask'),
        ('switch to a simpler architecture', 'ask'),
        ('No notes', 'approve | ask'),
        ('no objections', 'approve | ask'),
        ('Please fix the proposal', 'changes'),
        ('please fix it', 'changes | ask'),
        ('Please change the proposal', 'changes'),
        ('Please add more', 'changes | ask'),
        ('Needs more work, please', 'changes | ask'),
        ('ok, fix the proposal', 'changes | ask'),
        ('Yes, change the architecture', 'changes | ask'),
        ('Good, but it needs more work', 'changes | ask'),
        ('Looks good, but can you add more?', 'changes | ask'),
        ('approve, but add more on the drivers', 'changes | ask'),
        ('Keep it as is but add more to the proposal', 'changes | ask'),
        ('No changes to the architecture, but the proposal needs more work', 'changes | ask'),
        ('Ok but it needs more work', 'changes | ask'),
        ('Fine, but fix the proposal', 'changes | ask'),
        ('Good, but edit the proposal', 'changes | ask'),
        ('yes, but change it', 'changes | ask'),
        ('fix the proposal', 'changes'),
        ('changes: fix it', 'changes | ask'),
        ('changes: please fix the proposal', 'changes'),
        ('Looks good, nothing to change', 'approve'),
        ('approve all', 'approve'),
        ('Great work', 'approve | ask'),
        ('Love it', 'approve | ask'),
        ('ok.', 'approve'),
        ('ok, continue', 'approve | ask'),
    ],
    'G14': [
        ('yes, publish', 'ok pub=all'),
        ('\u201cpublish\u201d', 'ok pub=all'),
        ('Publish? Yes. Handoff: ce', 'ok pub=all ho=ce'),
        ('publish architecture and proposal', 'ok pub=architecture,proposal'),
        ('publish all but the proposal', 'ok pub=architecture,adr'),
        ('publish arch + proposal', 'ok pub=architecture,proposal | ok pub=architecture,adr,proposal | ask'),
        ("don't publish the proposal, just the architecture", 'ok pub=architecture | ok pub=architecture,adr | ask'),
        ('Publish (not the ADRs)', 'ok pub=architecture,proposal | ask'),
        ("don't publish", 'ok pub=none'),
        ('Publish \u2014 no.', 'ok pub=none'),
        ('publish? No way', 'ok pub=none'),
        ("I'd rather not publish", 'ok pub=none'),
        ('Publish? Hmm, no.', 'ok pub=none | ask'),
        ('Publish? Well, not yet.', 'ok pub=none | ask'),
        ('Publish? Sadly, no.', 'ok pub=none | ask'),
        ('Publish? Honestly no', 'ok pub=none | ask'),
        ("Publish? I'd say no", 'ok pub=none | ask'),
        ('yes', 'ok pub=all | ask'),
        ('yes please, ce', 'ok pub=all ho=ce | ask'),
        ('sure', 'ok pub=all | ask'),
        ('go ahead', 'ok pub=all | ask'),
        ('ce', 'ok ho=ce'),
        ('don\xb4t publish', 'ok pub=none | ask'),
        ('don`t publish', 'ok pub=none | ask'),
        ('Publish? \u274c', 'ok pub=none | ask'),
        ('Publish? \U0001f44e', 'ok pub=none | ask'),
        ('Publish. Actually, no.', 'ok pub=none | ask'),
        ('Publish\n\nActually no', 'ok pub=none | ask'),
        ('**Publish:** no', 'ok pub=none'),
        ('Publish? Probably not.', 'ok pub=none | ask'),
        ('Publish? Rather not.', 'ok pub=none | ask'),
        ("Publish? I'd rather not.", 'ok pub=none | ask'),
        ('Publish? Maybe not.', 'ok pub=none | ask'),
        ('Publish? Better not.', 'ok pub=none | ask'),
        ('Publish? Not today.', 'ok pub=none | ask'),
        ('Publish? Not really, no.', 'ok pub=none | ask'),
        ('Publish? Actually, no.', 'ok pub=none | ask'),
        ('Publish? Well, no.', 'ok pub=none | ask'),
        ('Publish? Um, no.', 'ok pub=none | ask'),
        ('Publish? Honestly, no.', 'ok pub=none | ask'),
        ("Publish? Let's not.", 'ok pub=none | ask'),
        ('Publish? Skip.', 'ok pub=none | ask'),
        ('Publish? Skip it.', 'ok pub=none | ask'),
        ('Publish? None.', 'ok pub=none | ask'),
        ('Publish? Nothing.', 'ok pub=none | ask'),
        ('Publish? No need.', 'ok pub=none | ask'),
        ('Publish? Not needed.', 'ok pub=none | ask'),
        ('Publish? Of course not.', 'ok pub=none | ask'),
        ('Publish? Not sure.', 'ask | ok pub=none'),
        ('Publish it. Stop asking.', 'ok pub=all | ask'),
        ('Publish? No need, thanks.', 'ok pub=none | ask'),
        ('publish - handoff: none', 'ok pub=all ho=none'),
        ('Publish? No. Handoff: none', 'ok pub=none ho=none'),
        ('cancel publishing', 'ok pub=none'),
        ('Publish? No, thanks.', 'ok pub=none'),
        ('do not publish', 'ok pub=none'),
        ('publish, handoff ce later', 'ok pub=all'),
        ('don\u2032t publish', 'ok pub=none | ask'),
        ('don\uff07t publish', 'ok pub=none | ask'),
        ('don\u201bt publish', 'ok pub=none | ask'),
        ('publish all but the ADRs', 'ask'),  # the ADRs go with the architecture and proposal copies
        ('Publish. No handoff.', 'ok pub=all ho=none'),
    ],
    'G2c': [
        ('LGTM', 'confirm'),
        ('all good \U0001f44d', 'confirm'),
        ('that works for me', 'confirm'),
        ('\u201cok\u201d', 'confirm'),
        ('Great, proceed', 'confirm'),
        ('ok, continue', 'confirm | ask'),
        ('Correct, move on', 'confirm | ask'),
        ('Yes, next', 'confirm | ask'),
        ('Good, carry on', 'confirm | ask'),
        ('all set', 'confirm | ask'),
        ("we're good", 'confirm | ask'),
        ("that's accurate", 'confirm | ask'),
        ('The users are nurses, not doctors', 'correct'),
        ('Change the success metric to 20% fewer unfilled shifts', 'correct'),
        ('Correct? No. Users are nurses', 'correct'),
        ('hmm', 'ask'),
        ('Please fix the frame', 'correct'),
        ('Yes, but add more to the frame', 'correct | ask'),
        ('ok, change it', 'correct | ask'),
        ('no issues', 'confirm | ask'),
    ],
    'G2f': [
        ('Restore!', 'restore'),
        ('Please restore CONTEXT.md', 'restore'),
        ("don't keep, restore", 'restore'),
        ('Hmm, restore I guess', 'restore'),
        ("I'd rather restore", 'restore | ask'),
        ('restore instead', 'restore | ask'),
        ("restore it (the framing shouldn't touch my repo)", 'restore | ask'),
        ("restore it since I didn't approve that edit", 'restore | ask'),
        ("don't keep it", 'restore | ask'),
        ('put it back', 'restore | ask'),
        ('revert it', 'restore | ask'),
        ('undo the change', 'restore | ask'),
        ('roll it back', 'restore | ask'),
        ('I want the original back', 'restore | ask'),
        ('go back to the old version', 'restore | ask'),
        ('discard the changes', 'restore | ask'),
        ('fine, keep', 'keep'),
        ('never mind, keep', 'keep'),
        ('no', 'ask | keep'),
        ('yes', 'ask'),
        ('Restore? Probably not.', 'keep | ask'),
        ('Restore? Rather not.', 'keep | ask'),
        ("Restore? I'd rather not.", 'keep | ask'),
        ('Restore? Maybe not.', 'keep | ask'),
        ('Restore? Better not.', 'keep | ask'),
        ('Restore? Not today.', 'keep | ask'),
        ('Restore? Hmm, no.', 'keep | ask'),
        ('Restore? Nah, not this run.', 'keep | ask'),
        ('Restore? Not sure.', 'ask | keep'),
        ('restore, keep', 'ask'),
        ('keep, restore', 'ask'),
        ('restore it (the framing broke our wording)', 'restore'),
    ],
    'G4': [
        ('none', 'ok rescue=- confirm=-'),
        ('Rescue I-012 \u2014 cheap to test', 'ok rescue=I-012 confirm=-'),
        ('save I-012', 'ok rescue=I-012 confirm=- | ask'),
        ('rescue I-012 and I-015', 'ok rescue=I-012,I-015 confirm=- | ask'),
        ('confirm I-004 and I-005', 'ok rescue=- confirm=I-004,I-005'),
        ('clear I-004, confirm I-005', 'ok rescue=- confirm=I-005'),
        ('rescue I-012\nconfirm I-004', 'ok rescue=I-012 confirm=I-004'),
        ('confirm I-004 since I-005 already covers it', 'ok rescue=- confirm=I-004 | ask'),
        ('confirm I-004 - duplicate of I-005', 'ok rescue=- confirm=I-004 | ask'),
        ('confirm I-004 (it duplicates I-002)', 'ok rescue=- confirm=I-004 | ask'),
        ('confirm I-004, it overlaps I-005', 'ok rescue=- confirm=I-004 | ask'),
        ('kill I-004', 'ok rescue=- confirm=I-004 | ask'),
        ('remove I-004', 'ok rescue=- confirm=I-004 | ask'),
        ('I-004 is a dud, kill it', 'ok rescue=- confirm=I-004 | ask'),
        ('Kill the flagged one (I-004)', 'ok rescue=- confirm=I-004 | ask'),
        ('drop I-004', 'ok rescue=- confirm=I-004 | ask | ok rescue=- confirm=-'),
        ('keep I-004', 'ok rescue=- confirm=- | ask'),
        ('**confirm I-004**', 'ok rescue=- confirm=I-004'),
        ('confirm I-003? Probably not.', 'ok confirm=- | ask'),
        ('confirm I-003? no', 'ok confirm=- | ask'),
        ('rescue I-004 because nurses need a wait list', 'ok rescue=I-004'),
        ('rescue I-004: the pause feature is unique', 'ok rescue=I-004'),
        ('confirm I-006, it is just a cancel flow', 'ok confirm=I-006'),
        ("I'd rather confirm I-004", 'ok confirm=I-004'),
        ('rescue I-004, it could matter later', 'ok rescue=I-004'),
        ('rescue I-004 because nurses cancel shifts at short notice', 'ok rescue=I-004'),
        ('rescue I-004: nurses hold two jobs, this fits them', 'ok rescue=I-004'),
        ('rescue I-004: it helps nurses stop burnout', 'ok rescue=I-004'),
        ('rescue I-012: nurses hate to wait', 'ok rescue=I-012'),
        ('rescue I-012 because shift swaps stop at 6pm', 'ok rescue=I-012'),
        ('rescue I-012: it cuts the wait for a swap', 'ok rescue=I-012'),
        ('rescue I-012: it could stop burnout', 'ok rescue=I-012'),
        ('rescue I-012 because the ward can hold a pilot', 'ok rescue=I-012'),
        ('rescue I-012: night staff cannot wait for a fix', 'ok rescue=I-012'),
        ("rescue I-012: users don't have this today", 'ok rescue=I-012'),
        ('rescue I-012: cheap to test later', 'ok rescue=I-012'),
        ('rescue I-012: we could pilot it on hold lines', 'ok rescue=I-012'),
        ('rescue I-012: patients wait hours for this', 'ok rescue=I-012'),
        ('confirm I-004, rescue I-012: it removes the wait', 'ok confirm=I-004 rescue=I-012'),
        ('rescue I-012: not now', 'ok rescue=- | ask'),
        ('rescue I-012: it beats I-004 on wait times', 'ok rescue=I-012 confirm=-'),
        ('rescue I-004, rescue I-005', 'ok rescue=I-004,I-005'),
        ('rescue I-004 and I-005', 'ok rescue=I-004,I-005'),
    ],
    'G5': [
        ('no kills', 'ok kill=-'),
        ('yes kill I-003', 'ok kill=I-003'),
        ('**kill I-003**', 'ok kill=I-003'),
        ('keep I-003, kill I-007', 'ok kill=I-007 keep=I-003'),
        ('I-003: kill, I-007: keep', 'ok kill=I-003 keep=I-007'),
        ("I don't want to kill I-003", 'ok kill=-'),
        ('kill I-003 later', 'ok kill=- | ask'),
        ('kill I-003 - it duplicates I-007', 'ok kill=I-003 | ask'),
        ('kill I-003, it overlaps I-007', 'ok kill=I-003 | ask'),
        ('kill I-003 because I-007 covers it better', 'ok kill=I-003 | ask'),
        ('kill I-003, not I-007', 'ok kill=I-003 | ask'),
        ('kill I-003 not I-007', 'ok kill=I-003 | ask'),
        ('kill I-003, leave I-007', 'ok kill=I-003 | ask'),
        ('kill I-003 and park I-007', 'ok kill=I-003 | ask'),
        ('kill I-003, I-007 stays', 'ok kill=I-003 | ask'),
        ('keep I-003 (better than I-007)', 'ok kill=- keep=I-003 | ask'),
        ('kill both', 'ok kill=I-003,I-007 | ask'),
        ('kill them all', 'ok kill=I-003,I-007 | ask'),
        ('kill i-003', 'ok kill=I-003 | ask'),
        ('kill 3 and 7', 'ok kill=I-003,I-007 | ask'),
        ('don\xb4t kill I-003', 'ok kill=- | ask'),
        ('don`t kill I-003', 'ok kill=- | ask'),
        ('kill I-003. No second thoughts.', 'ok kill=I-003'),
        ('kill I-003? Probably not.', 'ok kill=- | ask'),
        ('kill I-003? Rather not.', 'ok kill=- | ask'),
        ("kill I-003? I'd rather not.", 'ok kill=- | ask'),
        ('kill I-003? Maybe not.', 'ok kill=- | ask'),
        ('kill I-003? Better not.', 'ok kill=- | ask'),
        ('kill I-003? Not today.', 'ok kill=- | ask'),
        ('kill I-003? Not sure.', 'ok kill=- | ask'),
        ("I'd rather kill I-003", 'ok kill=I-003'),
        ('Too much overlap so kill I-003', 'ok kill=I-003'),
        ('No doubt about it: kill I-003', 'ok kill=I-003'),
        ('Rather than keep it, kill I-003', 'ok kill=I-003 | ask'),
        ('Instead kill I-003', 'ok kill=I-003'),
        ('Nothing new there so kill I-003', 'ok kill=I-003 | ask'),
        ("Let's stop dithering and kill I-003", 'ok kill=I-003 | ask'),
        ('Without a differentiator we should kill I-003', 'ok kill=I-003 | ask'),
        ("I don't see the point so kill I-003", 'ok kill=I-003 | ask'),
        ('keep I-007, its cancel flow is the differentiator', 'ok kill=- keep=I-007'),
        ('keep I-007 - the pause button is unique', 'ok kill=- keep=I-007'),
        ('keep I-007 because nurses hate the wait list', 'ok kill=- keep=I-007'),
        ('kill I-003, the bus stop idea is done', 'ok kill=I-003'),
        ('keep I-007, kill I-003 because shift swaps stop at midnight', 'ok kill=I-003 keep=I-007'),
        ('wait on I-003', 'ok kill=- | ask'),
        ('keep I-007, nurses cancel shifts all the time', 'ok kill=- keep=I-007'),
        ('keep I-007: it cuts wait times', 'ok kill=- keep=I-007'),
        ('keep I-007 - we can pilot it later', 'ok kill=- keep=I-007'),
        ('keep I-007, it helps nurses stop double-booking', 'ok kill=- keep=I-007'),
        ('keep I-003: it cuts the wait', 'ok kill=- keep=I-003'),
        ('kill I-003 and I-007 later', 'ok kill=- | ask'),
        ('kill all', 'ok kill=I-003,I-007 | ask'),
        ('kill them', 'ok kill=I-003,I-007 | ask'),
        ('don\uff07t kill I-003', 'ok kill=- | ask'),
        ('kill I-003, I-007 is fine', 'ok kill=I-003 | ask'),
    ],
    'G9': [
        ('passed, 12/10 needed', 'passed'),
        ('Result: passed', 'passed'),
        ('passed: yes', 'passed'),
        ('missed', 'missed'),
        ('fail', 'missed'),
        ("Missed. Didn't hit 10 signups", 'missed'),
        ("didn't pass", 'missed | ask'),
        ('Passed? Not really, only 3 of 10', 'missed | ask'),
        ('Passed? Sadly, no. 3 of 10', 'missed | ask'),
        ('Passed? Hmm, not really', 'missed | ask'),
        ('Passed? Well, no.', 'missed | ask'),
        ('Passed? Honestly, no - 3 of 10', 'missed | ask'),
        ('Passed? Unfortunately, not.', 'missed | ask'),
        ('passed? not even close', 'missed | ask'),
        ('Passed? Nowhere near, 2 of 10', 'missed | ask'),
        ("Passed? I'd say no", 'missed | ask'),
        ('Passed? Hardly.', 'missed | ask'),
        ('Missing the target', 'missed | ask'),
        ('too early to tell', 'inconclusive | ask'),
        ('passed... not really sure though', 'inconclusive | ask'),
        ('didn\xb4t pass, 3 of 10', 'missed | ask'),
        ('didn`t pass, 3 of 10', 'missed | ask'),
        ('pass rate: 3 of 10', 'missed | ask'),
        ('3 of 10, below the pass bar', 'missed | ask'),
        ('short of the pass threshold (3/10)', 'missed | ask'),
        ('we got 3 of 10 and the pass mark was 8', 'missed | ask'),
        ('Passed. Actually, no \u2014 3 of 10', 'missed | ask'),
        ('Passed? \u274c', 'missed | ask'),
        ('Missed? Nope, passed!', 'passed | ask'),
        ('Passed? Probably not.', 'missed | ask'),
        ('Passed? Probably not. 3 of 10', 'missed | ask'),
        ('Passed? Rather not.', 'missed | ask'),
        ('Passed? Rather not. 3 of 10', 'missed | ask'),
        ("Passed? I'd rather not.", 'missed | ask'),
        ("Passed? I'd rather not. 3 of 10", 'missed | ask'),
        ('Passed? Maybe not.', 'missed | ask'),
        ('Passed? Maybe not. 3 of 10', 'missed | ask'),
        ('Passed? Better not.', 'missed | ask'),
        ('Passed? Better not. 3 of 10', 'missed | ask'),
        ('Passed? Not today.', 'missed | ask'),
        ('Passed? Not today. 3 of 10', 'missed | ask'),
        ('Passed? Hmm, no.', 'missed | ask'),
        ('Passed? Hmm, no. 3 of 10', 'missed | ask'),
        ('Passed? Not really, no. 3 of 10', 'missed | ask'),
        ('Passed? Actually, no.', 'missed | ask'),
        ('Passed? Actually, no. 3 of 10', 'missed | ask'),
        ('Passed? Well, no. 3 of 10', 'missed | ask'),
        ('Passed? Um, no.', 'missed | ask'),
        ('Passed? Um, no. 3 of 10', 'missed | ask'),
        ('Passed? Honestly, no.', 'missed | ask'),
        ('Passed? Honestly, no. 3 of 10', 'missed | ask'),
        ("Passed? Let's not.", 'missed | ask'),
        ("Passed? Let's not. 3 of 10", 'missed | ask'),
        ('Passed? Skip.', 'missed | ask'),
        ('Passed? Skip. 3 of 10', 'missed | ask'),
        ('Passed? Skip it.', 'missed | ask'),
        ('Passed? Skip it. 3 of 10', 'missed | ask'),
        ('Passed? None.', 'missed | ask'),
        ('Passed? None. 3 of 10', 'missed | ask'),
        ('Passed? Nothing.', 'missed | ask'),
        ('Passed? Nothing. 3 of 10', 'missed | ask'),
        ('Passed? No need.', 'missed | ask'),
        ('Passed? No need. 3 of 10', 'missed | ask'),
        ('Passed? Not needed.', 'missed | ask'),
        ('Passed? Not needed. 3 of 10', 'missed | ask'),
        ("Passed? I don't think so. 3 of 10", 'missed | ask'),
        ('Passed? No, thank you. 3 of 10', 'missed | ask'),
        ('Passed? Absolutely not. 3 of 10', 'missed | ask'),
        ('Passed? Not sure. 3 of 10', 'ask | inconclusive'),
        ('Passed? Probably not. Only 3 of 10.', 'missed | ask'),
        ('Passed? Well, no. Only 3 of 10.', 'missed | ask'),
        ('Passed? Close, but no. 5 of 10.', 'missed | ask'),
        ('Passed? Not even close, 2 of 10 signed up.', 'missed | ask'),
        ('Passed? Not really...', 'missed | ask'),
        ('Passed? Probably not. Only 3 of 10 signed up.', 'missed | ask'),
        ('passed, no churn', 'passed'),
        ('passed: 8 of 10, no complaints', 'passed'),
        ('Passed? Not at all - 3 of 10', 'missed | ask'),
        ('passed, missed', 'ask'),
        ('passed: 12 of 10 needed and no churn', 'passed'),
        ("it didn't pass, it missed", 'missed'),
        ('passed, 8 of 10 joined the wait list', 'passed'),
        ("passed? we didn't hit the target", 'missed | ask'),
        ('passed with 3 of 10, which falls short', 'missed | ask'),
        ('passed, but below the bar', 'missed | ask'),
        ('passed with 3 of 10, which is a fail', 'missed | ask'),
        ('passed with 3 of 10 - under the 6 we needed', 'missed | ask'),
        ('passed 3/10, short of the goal', 'missed | ask'),
        ('missed: only 3 of 10 passed', 'missed'),
        ('passed: 8 of 10 finished, 2 failed', 'passed | ask'),
        ('missed, only 3 of 10 passed the screener', 'missed | ask'),
        ('passed: 3 of 10 missed', 'passed | ask'),
        ('Pass rate 30%, missed', 'missed'),
        ('didn\u2032t pass, 3 of 10', 'missed | ask'),
    ],
    'GB': [
        ('go to 500', 'raise cap=500'),
        ('yes, raise to 300', 'raise cap=300'),
        ("raise to 400 \u2014 it's worth it", 'raise cap=400'),
        ('**300**', 'raise cap=300'),
        ("don't stop, raise to 300", 'raise cap=300'),
        ('stop here', 'stop'),
        ('Stop. Not worth more money', 'stop'),
        ('stop: no more requests', 'stop'),
        ('raise to 300? no.', 'ask | stop'),
        ('raise to 300? Hmm, no.', 'ask | stop'),
        ('raise to 300? Well, not yet', 'ask | stop'),
        ('raise by 100', 'ask'),
        ('add 200 more', 'ask'),
        ('another 150', 'ask'),
        ('double it', 'ask'),
        ('no', 'ask | stop'),
        ('raise to 300. Actually, no.', 'ask | stop'),
        ('raise to 300? Probably not.', 'ask | stop'),
        ('raise to 300? Rather not.', 'ask | stop'),
        ("raise to 300? I'd rather not.", 'ask | stop'),
        ('raise to 300? Maybe not.', 'ask | stop'),
        ('raise to 300? Better not.', 'ask | stop'),
        ('raise to 300? Not today.', 'ask | stop'),
        ('raise to 300? Actually, no.', 'ask | stop'),
        ('raise to 300? Well, no.', 'ask | stop'),
        ('raise to 300? Um, no.', 'ask | stop'),
        ('raise to 300? Honestly, no.', 'ask | stop'),
        ("raise to 300? Let's not.", 'ask | stop'),
        ('raise to 300? Skip.', 'ask | stop'),
        ('raise to 300? Skip it.', 'ask | stop'),
        ('raise to 300? None.', 'ask | stop'),
        ('raise to 300? Nothing.', 'ask | stop'),
        ('raise to 300? No need.', 'ask | stop'),
        ('raise to 300? Not needed.', 'ask | stop'),
        ('raise to 300? No, not now.', 'ask | stop'),
        ('raise to 300? Of course not.', 'ask | stop'),
        ('raise to 300? Not sure.', 'ask'),
        ('stop - not worth more', 'stop'),
        ('raise to 1234567890', 'ask'),
        ('100 more', 'ask'),
        ('another 100', 'ask'),
    ],
    'GX': [
        ('reframe around nurses only', 'reframe'),
        ('reframe instead', 'reframe | ask'),
        ('Continue, the red team is too pessimistic', 'continue'),
        ("I don't want to stop, continue", 'continue'),
        ("Continue. Don't stop now.", 'continue'),
        ('\u201ccontinue\u201d', 'continue'),
        ('reframe? well, no \u2014 continue', 'continue'),
        ('keep going', 'continue | ask'),
        ('stop: this is not worth it', 'stop'),
        ('Stop \U0001f6d1', 'stop'),
        ('Continue? Hmm, no. Stop.', 'stop'),
        ('Continue? Sadly, no.', 'stop | ask'),
        ('Continue? Honestly, no.', 'stop | ask'),
        ('continue but reframe the users', 'ask'),
        ('Reframe? Probably not.', 'ask'),
        ('Reframe? Rather not.', 'ask'),
        ("Reframe? I'd rather not.", 'ask'),
        ('Reframe? Maybe not.', 'ask'),
        ('Reframe? Better not.', 'ask'),
        ('Reframe? Not today.', 'ask'),
        ('Reframe? Hmm, no.', 'ask'),
        ('Reframe? Not really, no.', 'ask'),
        ('Reframe? Not sure.', 'ask'),
        ('stop, not worth it', 'stop'),
        ('stop: too expensive', 'stop'),
        ('continue and wait for the probe', 'continue'),
    ],
}


def _ids(xs):
    return ",".join(sorted(set(xs))) if xs else "-"


def matches(intent, got):
    for alt in intent.split(" | "):
        parts = alt.split()
        if got.get("r") == parts[0] and all(got.get(k) == v for k, v in (p.split("=", 1) for p in parts[1:])):
            return True
    return False


def outcome(gate, ctx, ans, effects):
    s = ctx.state
    if gate == "G0k":
        p = s.get("privacy") or {}
        return {"r": "start", "seeds": str(len((ans.get("seeds") or {}).get("ideas") or [])),
                "mode": s.get("mode"), "autopilot": s.get("autopilot"),
                "private": str(bool((s.get("options") or {}).get("private"))),
                "web": "on" if p.get("web") else "off", "vendors": "on" if p.get("vendors") else "off"}
    if gate == "G1":
        return {"r": "skip" if ans.get("skip") else "done" if ans.get("done") else "?"}
    if gate in ("G2c", "G10"):
        r = "correct" if ans.get("corrections") else "confirm" if ans.get("confirm") else "?"
        if gate == "G10" and r == "correct":
            r = "correct" if any(e[0] == "reset" for e in effects) else "correct(no-redo)"
        return {"r": r}
    if gate == "G2f":
        return {"r": "restore" if ans.get("restore") else "keep"}
    if gate == "G4":
        return {"r": "ok", "rescue": _ids([x.get("id") for x in ans.get("rescue") or []]),
                "confirm": _ids(ans.get("confirm_flags") or [])}
    if gate == "G5":
        return {"r": "ok", "kill": _ids(s.get("killed") or []), "keep": _ids(ans.get("keep") or [])}
    if gate == "G9":
        return {"r": (ans.get("result") or "?").lower()}
    if gate == "GB":
        return {"r": "stop"} if ans.get("stop") else {"r": "raise", "cap": str(ans.get("raise_to"))}
    if gate == "GX":
        return {"r": ans.get("action") or "?"}
    if gate == "G11":
        return {"r": (s.get("choice") or {}).get("arch") or "?",
                "suggestion": str(bool(ans.get("accept_recommendation")))}
    if gate == "G12":
        acc = ans.get("accept") or []
        return {"r": "ok", "acc": "all" if "all" in acc else _ids(acc), "rej": _ids(ans.get("reject") or [])}
    if gate == "G13":
        o = {"r": ans.get("action") or "?"}
        if ans.get("switch_to"):
            o["to"] = ans["switch_to"]
        return o
    pub = ans.get("publish")  # G14
    pub = "all" if pub is True else "none" if pub is False else "unset" if pub is None else ",".join(pub)
    return {"r": "ok", "pub": pub, "ho": ans.get("handoff") or "unset"}


class GateCorpus(tl.EngineTestCase):
    def build(self, gate, n):
        ctx = self.make_ctx(mode="deep" if gate in ("G10", "G12") else "standard", run_name="2026-09-27-c%d" % n)
        if gate == "G1":
            ctx.write("00_HUMAN_SEEDS.md", "# Seeds\n\n## Ideas\n- nurses swap shifts by SMS\n- a dumb idea: fax\n")
        if gate == "G2c":
            ctx.write("01_FRAME.md", "# Frame\n\n## Problem\nshift swaps\n")
        if gate == "G10":
            ctx.write("10_ARCHITECTURE/00_BRIEF.md", "# Brief\n")
        if gate in ("G11", "G13"):
            ctx.write_json("10_ARCHITECTURE/candidates/map.json", {"A": {"family": "claude"}, "B": {"family": "gpt"},
                                                                   "C": {"family": "kimi"}})
            ctx.write_json("10_ARCHITECTURE/matrix.json", MATRIX)
            ctx.state["choice"] = {"idea": "I-001", "arch": "A" if gate == "G13" else None, "runner_up": "I-002"}
        if gate == "G5":
            ctx.state["k4_candidates"] = ["I-003", "I-007"]
            ctx.state["killed"] = []
        if gate == "G12":
            ctx.write_json("10_ARCHITECTURE/decisions.json", {"adrs": [
                dict(ADR, title="Use Postgres"), dict(ADR, title="Use a monolith"), dict(ADR, title="Use SMS")]})
            render_arch.rerender_adrs(ctx)
        return ctx

    def read(self, gate, reply, n):
        if gate == "G0v1":
            return q.read_v1(self, "2026-09-27-v%d" % n, {"reply": reply})
        gid = "G0" if gate == "G0k" else gate
        ctx = self.build(gate, n)
        ans, _notes, errs = gates.prepare_answer(ctx, gid, {"reply": reply})
        if errs:
            return {"r": "ask", "why": errs[0]}
        with mock.patch.object(gates.registry, "render_shortlist", lambda *a, **k: None):
            effects = gates.apply(ctx, gid, ans) if gate not in ("G9", "G13") else []
        return outcome(gate, ctx, ans, effects)

    def check(self, gate):
        for n, (reply, intent) in enumerate(ROWS[gate]):
            with self.subTest(gate=gate, reply=reply):
                got = self.read(gate, reply, n)
                self.assertTrue(matches(intent, got), "want %s, got %r" % (intent, got))


def _add(gate):
    setattr(GateCorpus, "test_%s" % gate.lower(), lambda self: self.check(gate))


for _gate in ROWS:
    _add(_gate)


if __name__ == "__main__":
    unittest.main()
