"""Phase J, the origin-label check (KIT_SPEC 6.7 rule 6): a judge prompt is refused for the run's own alias IDs and
for origin labels ('Origin: gpt', '(origin: human)', 'strategy: S2'), not for ordinary words ('generated by',
'strategy:', 'origin:') or alias-shaped tokens ('L4-7', 'H-2'); the user's topic never blocks its own run, and a
refusal names the file that holds the match and the step that prepares the prompt again (hunt: origin-label check
blocks screen, tournament and architecture judge steps on ordinary words)."""

import os
import sys
import unittest
from unittest import mock

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "fixtures", "engine"))
import engine_testlib as tl  # noqa: E402

import stubs  # noqa: E402  (tests/harness, put on sys.path by engine_testlib)
from ublib.engine import builders  # noqa: E402
from ublib.engine import privacy as pv  # noqa: E402
from ublib.engine import state as st  # noqa: E402

ORDINARY = ("Fair rotas generated by a constraint solver each month.", "Deployment strategy: blue-green on one VM.",
            "CORS origin: https://app.example", "Two app nodes behind an L4-7 load balancer.",
            "Rotas for H-2 visa holders", "Pricing strategy: free for the first ward, then per bed.",
            "Test plans generated by GPT-4 style tools", "Family: human-centred care")
LABELS = ("Origin: claude", "(origin: gpt)", "(origin: human-mixed)", "strategy: S2", "Strategy = G1",
          "written by kimi-alt", "generated by Claude", "origin: openai")


class OriginLabelTests(unittest.TestCase):
    def test_ordinary_words_pass(self):
        for text in ORDINARY:
            pv.check_origin_labels(text, "6.2-claude", aliases=["S2-01", "H-01", "H-02", "L1-03"])

    def test_origin_labels_and_the_runs_alias_ids_are_refused(self):
        for text in LABELS + ("merged from S2-01", "the lens idea L1-03"):
            with self.assertRaises(pv.PolicyBlock, msg=text) as cm:
                pv.check_origin_labels(text, "6.2-claude", aliases=["S2-01", "G1-02", "L1-03"])
            self.assertEqual(cm.exception.rule, "origin_label_check")

    def test_the_users_topic_never_blocks_its_run(self):
        topic = "detect essays generated by Claude in schools"
        pv.check_origin_labels("BRIEF: %s\nIDEAS" % topic.upper(), "Q.3s-claude", aliases=[], allow=[topic])
        with self.assertRaises(pv.PolicyBlock):
            pv.check_origin_labels("BRIEF: %s\nIDEAS\nwritten by gpt" % topic, "x", aliases=[], allow=[topic])


class JudgeInputTests(tl.EngineTestCase):
    def test_a_refused_screen_prompt_names_its_source_and_the_prepare_step(self):
        ctx = self.make_ctx(families=("claude", "gpt"))
        ctx.write("pool/S2_contrarian.md", "### S2-01 Night swap board\n- Pitch: p\n")
        ctx.write("screen/header.md", "You are a judge. BRIEF: shift swaps\n")
        ctx.write("screen/ideas.md", "I-001 | Night swap board | the S2-01 board, merged | m\n")
        ctx.write("screen/claude.prompt.md", "You are a judge.\nIDEAS\nI-001 | Night swap board | the S2-01 board, "
                                             "merged | m\nPrint only the result.\n")
        spec = {"id": "claude", "template": None, "prompt_file": "screen/claude.prompt.md", "kind": "judge",
                "family": "claude", "tools": "none", "cwd": "empty", "out": "screen/claude.out.json",
                "contract": {"type": "text"}, "checks": ["origin_label"]}
        self.assertEqual(builders.run_aliases(ctx), ["S2-01"])
        with self.assertRaises(pv.PolicyBlock) as cm:
            builders.make_job(ctx, {"id": "6.2"}, spec)
        msg = str(cm.exception)
        self.assertIn("the alias ID S2-01 (in screen/ideas.md)", msg)
        self.assertIn(" redo ", msg)
        self.assertIn(" 6.1 --yes", msg)
        self.assertIn(" 6.1 --yes", cm.exception.fix[0])
        ctx.write("screen/claude.prompt.md", "You are a judge.\nIDEAS\nI-001 | Night swap board | a board for the "
                                             "L4-7 team, generated by a solver | m\nPrint only the result.\n")
        builders.make_job(ctx, {"id": "6.2"}, spec)


def curated_with(field, text):
    orig = stubs._quick_curated

    def fn(ctx):
        out = orig(ctx)
        out["ideas"][0][field] = text
        return out
    return fn


class QuickRunTests(tl.EngineTestCase):
    """A quick full-auto run on two families, driven with the stubs; only the curated text of Q-01 changes."""

    def run_quick(self, field=None, text=None, **kw):
        ctx = tl.full_auto_ctx(self, mode="quick", families=("claude", "gpt"), **kw)
        if field is None:
            return ctx, tl.drive(ctx)
        with mock.patch.object(stubs, "_quick_curated", curated_with(field, text)):
            return ctx, tl.drive(ctx)

    def test_generated_by_in_a_pitch_reaches_done(self):
        self.assertEqual(self.run_quick("pitch", "Fair rotas generated by a constraint solver each month.")[1]["type"],
                         "DONE")

    def test_an_alias_shaped_title_reaches_done(self):
        self.assertEqual(self.run_quick("title", "Swap router behind an L4-7 load balancer")[1]["type"], "DONE")

    def test_a_strategy_line_reaches_done(self):
        self.assertEqual(self.run_quick("mechanism", "Pricing strategy: free for the first ward.")[1]["type"], "DONE")

    def test_the_users_topic_reaches_done(self):
        self.assertEqual(self.run_quick(topic="detect essays generated by AI in schools")[1]["type"], "DONE")

    def test_an_origin_label_blocks_the_quick_screen_and_names_the_curation(self):
        ctx, card = self.run_quick("pitch", "A shared swap board (Origin: gpt).")
        self.assertEqual(card["type"], "BLOCKED")
        self.assertEqual(st.step_state(ctx.state, "Q.3s"), "blocked")
        say = card.get("say") or ""
        self.assertIn("'Origin: gpt' (in quick/curated.json)", say)
        self.assertIn(" Q.3p --yes", say)


class ArchitectureRunTests(tl.EngineTestCase):
    def test_ordinary_words_in_the_candidates_reach_done(self):
        # the architecture judges (12.6) read the candidate sheets: a strategy line and an L4-7 load balancer
        orig = stubs._arch_candidate

        def candidate(ctx):
            out = orig(ctx)
            out.update(summary="Deployment strategy: blue-green on one VM.",
                       deployment="Two app nodes behind an L4-7 load balancer.")
            return out
        os.makedirs(os.path.join(self.project, ".git"), exist_ok=True)
        ctx = tl.full_auto_ctx(self, mode="standard", variant="software", run_name="2026-09-27-sw")
        with mock.patch.object(stubs, "_arch_candidate", candidate):
            card = tl.drive(ctx)
        self.assertEqual(card["type"], "DONE")
        self.assertEqual(st.step_state(ctx.state, "12.6"), "done")


if __name__ == "__main__":
    unittest.main()
