"""Static tests for the skill content (KIT_SPEC 6.12-6.14, 7.4-7.6, 8.3-8.5, 9, 12.3).

Covers SK/SKILL.md, SK/references/*.md and SK/templates/** (prompts, host, gates, docs, schemas, manifest.json):
inventory, ASCII/LF/no '${', header and skill-guard lines, known placeholders, OUTPUT RULE, evidence-rule wording,
structured-output schema subset, and contract coherence (synthetic outputs pass ublib.validate.check_contract).
"""

import json
import os
import re
import shutil
import sys
import tempfile
import unittest

_KIT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_SK = os.path.join(_KIT, "skills", "ultimate-brainstorm")
_SCRIPTS = os.path.join(_SK, "scripts")
if _SCRIPTS not in sys.path:
    sys.path.insert(0, _SCRIPTS)

from ublib import schema_lite  # noqa: E402
from ublib.validate import check_contract  # noqa: E402

TPL = os.path.join(_SK, "templates")
REF = os.path.join(_SK, "references")

# ---------------------------------------------------------------- spec inventory (6.12, 6.14)

SPEC_PROMPTS = (
    "PING FRAME-QUESTIONS FRAME-FINAL FRAME-DRAFT P-GROUND GEN-HEADER S1F S2-VS S3-EDE S4-TRANSFER S5-OPS "
    "S5-RESEARCH GAP REOPEN LENS QUICK-GEN CURATOR QUICK-CURATE SCREEN-HEADER TOURNAMENT-HEADER CHECK EVOLVE "
    "EVOLVE-CONTRAST NORMALIZER PRECOMMIT REVIEWER REBUTTAL SYNTHESIS PROBE QUICK-PROBE ARCH-DRIVERS ARCH-CANDIDATE "
    "ARCH-JUDGE ARCH-PREMORTEM ARCH-PACKAGE-STRUCTURE ARCH-PACKAGE-CROSSCUT ARCH-DECISIONS ARCH-PACKAGE-LITE "
    "STACK-VERIFY ARCH-REVIEW ARCH-FIX APPROACH PROPOSAL-A PROPOSAL-B PROPOSAL-C EXEC-ONEPAGER PRFAQ PROPOSAL-LITE "
    "PROPOSAL-RUBRIC PROPOSAL-REDTEAM PROPOSAL-FIX").split()
SPEC_HOST = "FRAME-GRILL FRAME-GRILL-DOCS S1-CE BMAD-SEEDS FORGE CONTEXT-MERGE HOST-BATCH HANDOFF-RUN".split()
SPEC_GATES = "G0 G1 G2 G2c G2f G3 G4 G5 G6 G7 G8a G8b G9 G10 G11 G12 G13 G14 GB GX".split()
SPEC_DOCS = ("RUN PROGRESS SHORTLIST TOURNAMENT DECISION QUICK-DECISION GOALS-CONSTRAINTS QUALITY-SCENARIOS "
             "CONTEXT-VIEW ARCH-README ADR-MADR RISKS STACK PROPOSAL-APPENDICES HANDOFF SEEDS HANDOFF-CE "
             "HANDOFF-SPECKIT HANDOFF-SUPERPOWERS HANDOFF-OPENSPEC").split()
SPEC_SCHEMAS = ("frame-questions merges quick-curated quick-probe arch-drivers arch-candidate arch-judge "
                "arch-decisions stack-verify findings rubric redteam").split()
SPEC_REFERENCES = ("pipeline hosts families components variants techniques kill-rules architecture proposal "
                   "install troubleshooting").split()
SPEC_STANDARD_PLACEHOLDERS = (
    "BRIEF FACTS LANDSCAPE AXES HMW AUDIENCE HARD_CONSTRAINTS CRITERIA_ANCHORS CRITERIA_WEIGHTS STRATEGY_ID IDEA "
    "CARD CHECKS CELL CLUSTER_NAMES LEDGER_TITLES POOL_BUNDLE SEEDS_BUNDLE FRAME_FULL DECISION PROBE ARCH_BRIEF "
    "QAS_TABLE ARCHETYPE OTHER_ARCHETYPES CANDIDATE_SHEETS CHOSEN_CANDIDATE DRIVERS_JSON STRUCTURE_FILES PREMORTEM "
    "FINDINGS LINT_REPORT PACK_A PACK_B PACK_C SOURCES_TABLE SECTIONS_ALL RUBRIC_FIXES REDTEAM_ITEMS USER_CHANGES "
    "LANG VARIANT MODE DATE RUN_NAME OUTPUT_RULE SCHEMA_TEXT ALLOWED_FILES ROUND_CAP COMPONENT_NAME").split()
JOB_KINDS = ("ping generator researcher curator judge checker normalizer reviewer synthesis writer arch-author "
             "arch-judge rubric redteam fixer frame").split()

GUARD = "Do not load or invoke any skill; this prompt is the whole task."
HEADER_RX = re.compile(r"^<!-- ub-template: ([A-Z0-9][A-Za-z0-9-]*) v1 kind=([a-z-]+) -->$")
PH_RX = re.compile(r"\{\{([A-Z][A-Z0-9_]*)\}\}")
CHOICES_RX = re.compile(r"<!-- ub-choices: ([A-Z][A-Z0-9_]*) key=([A-Z][A-Z0-9_]*)\n(.*?)\n-->", re.S)
COMMENT_RX = re.compile(r"<!--.*?-->\n?", re.S)
ARG_RX = re.compile(r"<!-- ub-argument:begin -->\n(.*?)<!-- ub-argument:end -->", re.S)
ORIGIN_ALIAS_RX = re.compile(r"\b(S\d+|G\d+|R\d+|L\d+|H|HP|H2|IMP|S1R)-\d+\b")
ORIGIN_WORDS_RX = re.compile(r"origin:|strategy:|generated by", re.I)
SCHEMA_KEYWORDS = {"type", "properties", "required", "additionalProperties", "items", "enum", "description",
                   "minimum", "maximum"}

V1_SEEDS = ("# Human seeds (write alone, before seeing any AI idea; or replace everything with 'SKIPPED: <reason>')\n\n"
            "## Problem\n\n## Primary idea (to pressure-test)\n\n## Ideas\n\n## Obvious\n\n## Off-limits\n")


def read(path):
    with open(path, "rb") as f:
        raw = f.read()
    return raw.decode("utf-8")


def load_manifest():
    with open(os.path.join(TPL, "manifest.json"), encoding="utf-8") as f:
        return json.load(f)


def template_files():
    """{(folder, NAME): abs path} for every .md/.tpl template."""
    out = {}
    for folder in ("prompts", "host", "gates", "docs"):
        d = os.path.join(TPL, folder)
        for fn in sorted(os.listdir(d)):
            p = os.path.join(d, fn)
            if fn.endswith(".md"):
                out[(folder, fn[:-3])] = p
            elif fn.endswith(".tpl"):
                out[(folder, "INDEX-HTML" if fn == "index.html.tpl" else fn[:-4])] = p
    return out


def render(text, values, prompt=False):
    """Reference renderer for the manifest rules: drop line 1, (prompts) drop comments after choices, fill values,
    drop lines that are one empty placeholder."""
    lines = text.split("\n")
    body = "\n".join(lines[1:])
    if prompt:
        for name, key, rows in CHOICES_RX.findall(body):
            table = dict(r.split(" | ", 1) for r in rows.split("\n"))
            if key in values:
                values = dict(values)
                values[name] = table[values[key]]
        body = COMMENT_RX.sub("", body)
    out = []
    for ln in body.split("\n"):
        m = re.fullmatch(r"\{\{([A-Z][A-Z0-9_]*)\}\}", ln.strip())
        if m and not values.get(m.group(1), ""):
            continue
        out.append(ln)
    text = "\n".join(out)
    for _ in range(2):  # a value may itself contain a placeholder (ARCHETYPE -> OTHER_ARCHETYPES)
        text = PH_RX.sub(lambda mm: str(values.get(mm.group(1), "")), text)
    return text


def instance(schema):
    """A minimal instance of a structured-output schema (first enum value, 3 for numbers)."""
    t = schema.get("type")
    if "enum" in schema:
        return schema["enum"][0]
    if t == "object":
        return {k: instance(v) for k, v in schema.get("properties", {}).items()}
    if t == "array":
        return [instance(schema.get("items", {"type": "string"}))]
    if t == "integer" or t == "number":
        return 3
    if t == "boolean":
        return True
    return "stub"


class Inventory(unittest.TestCase):
    def setUp(self):
        self.m = load_manifest()
        self.files = template_files()

    def names(self, folder):
        return sorted(n for (f, n) in self.files if f == folder)

    def test_prompts_match_spec_and_manifest(self):
        self.assertEqual(self.names("prompts"), sorted(SPEC_PROMPTS))
        self.assertEqual(sorted(self.m["prompts"]), sorted(SPEC_PROMPTS))

    def test_host_gates_docs_match_spec_and_manifest(self):
        self.assertEqual(self.names("host"), sorted(SPEC_HOST))
        self.assertEqual(sorted(self.m["host"]), sorted(SPEC_HOST))
        self.assertEqual(self.names("gates"), sorted(SPEC_GATES))
        self.assertEqual(sorted(self.m["gates"]), sorted(SPEC_GATES))
        docs = set(self.names("docs"))
        self.assertTrue(set(SPEC_DOCS) | {"INDEX-HTML"} <= docs, sorted(set(SPEC_DOCS) - docs))
        self.assertEqual(sorted(docs), sorted(self.m["docs"]))
        self.assertEqual(sorted(docs - set(SPEC_DOCS) - {"INDEX-HTML"}), sorted(self.m["doc_extras"]))
        self.assertTrue(os.path.isfile(os.path.join(TPL, "docs", "index.html.tpl")))

    def test_schemas_match_spec(self):
        found = sorted(fn[:-len(".schema.json")] for fn in os.listdir(os.path.join(TPL, "schemas")))
        self.assertEqual(found, sorted(SPEC_SCHEMAS))
        self.assertEqual(sorted(self.m["schemas"]), sorted(SPEC_SCHEMAS))

    def test_no_stray_files(self):
        allowed_top = {"prompts", "host", "gates", "docs", "schemas", "manifest.json"}
        self.assertEqual(set(os.listdir(TPL)), allowed_top)
        for folder in ("prompts", "host", "gates"):
            for fn in os.listdir(os.path.join(TPL, folder)):
                self.assertTrue(fn.endswith(".md"), fn)

    def test_references_present_and_v1_files_not_shipped(self):
        found = sorted(fn[:-3] for fn in os.listdir(REF) if fn.endswith(".md"))
        self.assertEqual(found, sorted(SPEC_REFERENCES))
        for gone in ("prompts.md", "stages.md", "tools.md"):
            self.assertFalse(os.path.exists(os.path.join(REF, gone)), gone)


class TextRules(unittest.TestCase):
    """ASCII only, LF, UTF-8 without BOM, no '${', trailing newline (3.1, 6.12)."""

    def all_text_files(self):
        for root in (TPL, REF):
            for dirpath, _, files in os.walk(root):
                for fn in files:
                    yield os.path.join(dirpath, fn)
        yield os.path.join(_SK, "SKILL.md")

    def test_ascii_lf_no_bom(self):
        for p in self.all_text_files():
            with open(p, "rb") as f:
                raw = f.read()
            self.assertFalse(raw.startswith(b"\xef\xbb\xbf"), p)
            self.assertNotIn(b"\r", raw, p)
            self.assertTrue(all(b < 128 for b in raw), "non-ASCII byte in %s" % p)
            self.assertTrue(raw.endswith(b"\n"), p)

    def test_templates_have_no_dollar_brace(self):
        for dirpath, _, files in os.walk(TPL):
            for fn in files:
                self.assertNotIn("${", read(os.path.join(dirpath, fn)), fn)

    def test_reference_sizes(self):
        for fn in os.listdir(REF):
            self.assertLessEqual(os.path.getsize(os.path.join(REF, fn)), 25 * 1024, fn)


class Headers(unittest.TestCase):
    KIND_BY_FOLDER = {"host": {"host"}, "gates": {"gate"}, "docs": {"doc"}}

    def test_header_line(self):
        for (folder, name), path in template_files().items():
            first = read(path).split("\n", 1)[0]
            m = HEADER_RX.match(first)
            self.assertIsNotNone(m, "%s/%s: bad header %r" % (folder, name, first))
            self.assertEqual(m.group(1), name, path)
            kinds = self.KIND_BY_FOLDER.get(folder, set(JOB_KINDS) | {"partial"})
            self.assertIn(m.group(2), kinds, path)

    def test_prompt_kind_matches_manifest(self):
        m = load_manifest()
        for name, info in m["prompts"].items():
            first = read(os.path.join(TPL, "prompts", name + ".md")).split("\n", 1)[0]
            self.assertEqual(HEADER_RX.match(first).group(2), info["kind"], name)

    def test_skill_guard_on_isolated_prompts(self):
        m = load_manifest()
        for name, info in m["prompts"].items():
            second = read(os.path.join(TPL, "prompts", name + ".md")).split("\n")[1]
            if name == "GEN-HEADER":
                self.assertFalse(info["isolated"])
                self.assertNotEqual(second, GUARD)
            else:
                self.assertTrue(info["isolated"], name)
                self.assertEqual(second, GUARD, name)

    def test_output_rule_last(self):
        for name in SPEC_PROMPTS:
            if name == "GEN-HEADER":
                continue
            text = read(os.path.join(TPL, "prompts", name + ".md"))
            lines = [ln for ln in text.split("\n") if ln.strip()]
            self.assertIn("OUTPUT RULE", lines, name)
            self.assertEqual(lines[-1], "{{OUTPUT_RULE}}", name)
            self.assertLess(lines.index("OUTPUT RULE"), len(lines) - 1, name)


class Placeholders(unittest.TestCase):
    def setUp(self):
        self.m = load_manifest()
        self.used = {}
        for (_, name), path in template_files().items():
            text = read(path)
            for ph in PH_RX.findall(text):
                self.used.setdefault(ph, set()).add(name)
            for _, key, _ in CHOICES_RX.findall(text):
                self.used.setdefault(key, set()).add(name)

    def test_only_upper_snake_braces(self):
        for (_, name), path in template_files().items():
            text = PH_RX.sub("", read(path))
            self.assertNotIn("{{", text, name)
            self.assertNotIn("}}", text, name)

    def test_every_placeholder_known_and_used(self):
        known = set(self.m["placeholders"])
        self.assertEqual(sorted(set(self.used) - known), [], "unknown placeholders")
        self.assertEqual(sorted(known - set(self.used)), [], "unused registry entries")

    def test_standard_placeholders(self):
        for ph in SPEC_STANDARD_PLACEHOLDERS:
            self.assertIn(ph, self.m["placeholders"], ph)
            self.assertTrue(self.m["placeholders"][ph]["standard"], ph)
        extras = [k for k, v in self.m["placeholders"].items() if v["standard"]]
        self.assertEqual(sorted(extras), sorted(SPEC_STANDARD_PLACEHOLDERS))
        for v in self.m["placeholders"].values():
            self.assertTrue(v["desc"].strip())

    def test_engine_registry_knows_prompt_and_host_placeholders(self):
        """Prompt and host placeholders are filled by the engine registry (unknown names make the engine refuse the
        job), so every one must be registered. Gate and doc placeholders are filled from per-render mappings."""
        try:
            from ublib.engine import registry  # noqa: F401  (B3 engine; may not exist yet)
        except Exception:
            self.skipTest("ublib.engine.registry not available")
        names = getattr(registry, "PLACEHOLDERS", None)
        if names is None:
            self.skipTest("registry exposes no PLACEHOLDERS")
        needed = set()
        for (folder, name), path in template_files().items():
            if folder in ("prompts", "host"):
                needed |= set(PH_RX.findall(read(path)))
                needed |= set(key for _, key, _ in CHOICES_RX.findall(read(path)))
        self.assertEqual(sorted(needed - set(names)), [])

    def test_json_prompts_embed_schema_text(self):
        for name, info in self.m["prompts"].items():
            c = info["contract"] or {}
            if c.get("type") == "json" or name == "ARCH-CANDIDATE":
                self.assertIn("{{SCHEMA_TEXT}}", read(os.path.join(TPL, "prompts", name + ".md")), name)
        # a files job has no schema of its own: the decisions.json format is spelled out instead
        lite = read(os.path.join(TPL, "prompts", "ARCH-PACKAGE-LITE.md"))
        self.assertIn("FORMAT OF decisions.json", lite)
        for key in ('"adrs"', '"risks"', '"debt"', '"risk_ids"', '"payoff_trigger"', '"confirmation"'):
            self.assertIn(key, lite)

    def test_generators_include_gen_header_or_define_format(self):
        for name in ("S1F", "S2-VS", "S3-EDE", "S4-TRANSFER", "S5-OPS", "S5-RESEARCH", "GAP", "REOPEN", "QUICK-GEN"):
            text = read(os.path.join(TPL, "prompts", name + ".md"))
            self.assertEqual(text.split("\n")[2], "{{GEN_HEADER}}", name)
            self.assertIn("STRATEGY {{STRATEGY_ID}}", text, name)


class EvidenceRules(unittest.TestCase):
    """The v1 evidence rules survive in the templates (6.7)."""

    def t(self, name, folder="prompts"):
        return read(os.path.join(TPL, folder, name + ".md"))

    def test_isolated_generators_see_no_pool_seeds_or_landscape(self):
        blind = ("GEN-HEADER", "S1F", "S2-VS", "S3-EDE", "S4-TRANSFER", "S5-OPS", "S5-RESEARCH", "GAP", "LENS",
                 "QUICK-GEN", "EVOLVE-CONTRAST")
        for name in blind:
            text = self.t(name)
            for ph in ("{{POOL_BUNDLE}}", "{{SEEDS_BUNDLE}}", "{{SEED_PROBLEM}}", "{{LANDSCAPE}}"):
                self.assertNotIn(ph, text, "%s must not contain %s" % (name, ph))
        self.assertIn("{{LANDSCAPE}}", self.t("REOPEN"))  # the one landscape-aware generator
        header = self.t("GEN-HEADER")
        for phrase in ("you will never", "Warm-up (not counted)", "not a category",
                       "swapping in a competitor's name", "Read no files and run no commands"):
            self.assertIn(phrase, header)

    def test_only_curators_get_pool_and_seeds(self):
        for name in SPEC_PROMPTS:
            text = self.t(name)
            if "{{POOL_BUNDLE}}" in text or "{{SEEDS_BUNDLE}}" in text:
                self.assertIn(name, ("CURATOR", "QUICK-CURATE"))

    def test_framing_is_question_only(self):
        for name in ("FRAME-QUESTIONS", "FRAME-FINAL", "FRAME-DRAFT"):
            self.assertRegex(self.t(name), r"[Pp]ropose no solutions|[Nn]ever propose solutions", name)
        for name in ("FRAME-GRILL", "FRAME-GRILL-DOCS"):
            text = self.t(name, "host")
            self.assertIn("Do not propose solutions, example ideas or idea categories", text)
            self.assertIn("Recommended answers are allowed only for constraints", text)
        self.assertIn("ONLY on questions whose topic is\n   constraint, scope or timeline", self.t("FRAME-QUESTIONS"))

    def test_judges_are_neutral_and_carry_no_origin_labels(self):
        for name in ("SCREEN-HEADER", "TOURNAMENT-HEADER", "ARCH-JUDGE"):
            text = self.t(name)
            self.assertIn("did not write", text, name)
            self.assertIsNone(ORIGIN_ALIAS_RX.search(text), name)
            self.assertIsNone(ORIGIN_WORDS_RX.search(text), name)
        self.assertIn("It is NOT novelty", self.t("SCREEN-HEADER"))
        self.assertIn("Neutral labels, random order", self.t("ARCH-JUDGE"))
        self.assertIn("ignore wording", self.t("TOURNAMENT-HEADER"))

    def test_novelty_only_from_evidence(self):
        check = self.t("CHECK")
        self.assertIn('Never write "novel" or "no prior work"', check)
        self.assertIn("NOT LOCATED (within this search boundary)", check)
        for name in ("PROPOSAL-A", "PROPOSAL-B", "PROPOSAL-C", "EXEC-ONEPAGER", "PRFAQ", "PROPOSAL-LITE",
                     "PROPOSAL-FIX"):
            text = self.t(name)
            self.assertIn('Never use the word "novel"', text, name)
            self.assertIn("[S-###]", text, name)
            self.assertIn("[ASSUMPTION: ...]", text, name)
            self.assertIn("[ESTIMATE: range; basis]", text, name)
            self.assertIn("Never invent customers, quotes, metrics or moats", text, name)
            self.assertIn("Never change an architecture decision", text, name)
            self.assertIn("Say what is not being done", text, name)
            self.assertIn("{{LANG}}", text, name)

    def test_curator_only_merges_and_debate_only_narrows(self):
        self.assertIn("Do not create, improve or judge ideas. Only merge and map.", self.t("CURATOR"))
        self.assertIn("do not improve, weaken or add facts", self.t("NORMALIZER"))
        self.assertIn("Never invent a weakness", self.t("REVIEWER"))
        self.assertIn("Add no new points", self.t("REBUTTAL"))
        self.assertIn("Do not choose for the user", self.t("SYNTHESIS"))
        self.assertIn("never edit the\noriginals", self.t("EVOLVE"))

    def test_verbalized_sampling_wording_kept(self):
        vs = self.t("S2-VS")
        self.assertIn("Please sample at random from the tails of the\ndistribution", vs)
        self.assertIn("probability less than 0.01", vs)
        self.assertIn("Changed: N of 40", self.t("S3-EDE"))

    def test_probe_is_preregistered(self):
        probe = self.t("PROBE")
        self.assertIn("Pre-register the test NOW", probe)
        self.assertIn("INCONCLUSIVE never counts as a\npass", probe)

    def test_arch_candidate_framing(self):
        text = self.t("ARCH-CANDIDATE")
        self.assertIn("You are ONE independent architect; others design alternatives you will never see.", text)
        self.assertIn("the archetype is a starting stance, not a cage", text)

    def test_handoff_seeds_end_with_do_not_reopen(self):
        for name in ("HANDOFF-CE", "HANDOFF-SPECKIT", "HANDOFF-SUPERPOWERS", "HANDOFF-OPENSPEC"):
            lines = [ln for ln in self.t(name, "docs").split("\n") if ln.strip()]
            self.assertEqual(lines[-1], "Do not reopen the choice of idea or architecture.", name)
        self.assertIn("Milestone 0 (09_PROBE.md)\nruns first; do not plan beyond its kill criterion",
                      self.t("HANDOFF-CE", "docs"))


class Choices(unittest.TestCase):
    def table(self, name):
        text = read(os.path.join(TPL, "prompts", name + ".md"))
        blocks = CHOICES_RX.findall(text)
        self.assertEqual(len(blocks), 1, name)
        ph, key, rows = blocks[0]
        table = {}
        for r in rows.split("\n"):
            k, v = r.split(" | ", 1)
            table[k] = v
        self.assertIn("{{%s}}" % ph, COMMENT_RX.sub("", text), name)
        return key, table

    def test_archetypes(self):
        key, t = self.table("ARCH-CANDIDATE")
        self.assertEqual(key, "ARCHETYPE_ID")
        self.assertEqual(set(t), {"A", "B-local-first", "B-buy", "B-event", "C", "D", "A-software", "B-software"})
        self.assertTrue(t["A"].startswith("Boring by default: a modular monolith on managed services"))
        self.assertIn("{{OTHER_ARCHETYPES}}", t["C"])
        self.assertEqual(t["A-software"], "Smallest change to the current architecture (cite files).")
        self.assertEqual(t["B-software"], "One new bounded component or service.")
        self.assertTrue(t["D"].startswith("Cost-minimal"))

    def test_lenses(self):
        key, t = self.table("LENS")
        self.assertEqual((key, sorted(t)), ("STRATEGY_ID", ["L1", "L2", "L3", "L4", "L5", "L6"]))
        key, t = self.table("ARCH-REVIEW")
        self.assertEqual((key, sorted(t)), ("REVIEW_LENS", ["L1", "L2", "L3", "L4"]))

    def test_render_picks_choice_and_strips_comments(self):
        text = read(os.path.join(TPL, "prompts", "ARCH-CANDIDATE.md"))
        out = render(text, {"ARCHETYPE_ID": "C", "OTHER_ARCHETYPES": "A (boring), B (event-driven)"}, prompt=True)
        self.assertTrue(out.startswith(GUARD))
        self.assertNotIn("<!--", out)
        self.assertIn("The others are: A (boring), B (event-driven).", out)
        self.assertNotIn("{{", out)


class HostTemplates(unittest.TestCase):
    def test_argument_blocks(self):
        with_args = {"FRAME-GRILL", "FRAME-GRILL-DOCS", "S1-CE", "BMAD-SEEDS", "FORGE", "CONTEXT-MERGE"}
        for name in SPEC_HOST:
            text = read(os.path.join(TPL, "host", name + ".md"))
            blocks = ARG_RX.findall(text)
            self.assertEqual(len(blocks), 1 if name in with_args else 0, name)
            outside = ARG_RX.sub("", text)
            self.assertEqual(PH_RX.findall(outside), [], "%s: placeholders outside the argument block" % name)
            self.assertIn("task.done_cmd" if name in with_args else "", text)

    def test_round_cap_and_redirect(self):
        grill = read(os.path.join(TPL, "host", "FRAME-GRILL.md"))
        self.assertIn("At most {{ROUND_CAP}} rounds", grill)
        docs = read(os.path.join(TPL, "host", "FRAME-GRILL-DOCS.md"))
        self.assertIn("write to {{RUN_DIR}}/CONTEXT.proposed.md instead", docs)
        self.assertIn("Never create, edit or rewrite CONTEXT.md", docs)

    def test_host_batch_forbids_forks(self):
        text = read(os.path.join(TPL, "host", "HOST-BATCH.md"))
        self.assertIn("Read <prompt_file> and follow it exactly. Write only the requested output to <out>. Reply with "
                      "one line.", text)
        self.assertIn('subagent_type "general-purpose"; never the fork type', text)
        self.assertIn('AgentSwarm with items = the prompt files and prompt_template "Read ITEM and follow it exactly."',
                      text.replace("\n  ", " "))
        self.assertNotIn("SKILL.md", text)  # the single source never points back


class Gates(unittest.TestCase):
    """Gate text = fixed evidence-rule wording around the engine's per-gate SUMMARY and reply syntax (4.12, 6.7)."""

    def gate(self, g):
        return read(os.path.join(TPL, "gates", g + ".md"))

    def test_every_gate_has_summary_and_reply_help(self):
        m = load_manifest()
        known = set(m["gate_context"])
        for g in SPEC_GATES:
            text = self.gate(g)
            for ph in ("{{SUMMARY}}", "{{HOW_TO_REPLY}}", "{{RUN_NAME}}"):
                self.assertEqual(text.count(ph), 1, "%s %s" % (g, ph))
            self.assertLess(text.index("{{SUMMARY}}"), text.index("{{HOW_TO_REPLY}}"), g)
            self.assertEqual(sorted(set(PH_RX.findall(text)) - known), [], g)

    def test_gut_pick_before_scores_and_decision_shows_raw_verdicts_first(self):
        g8a = self.gate("G8a")
        self.assertIn("Pick before you see any score", g8a)
        self.assertIn("tally stays sealed", g8a)
        for word in ("STANDINGS", "SUGGESTION", "debiased", "%"):
            self.assertNotIn(word, g8a)
        g8b = self.gate("G8b")
        self.assertIn("rule, not a\nrecommendation: you decide", g8b)
        self.assertNotIn("Suggested by rule", g8b)  # the engine's SUMMARY carries that line once
        self.assertIn("raw red-team verdict lines come before the synthesis summary", g8b)
        self.assertIn("your own words are recorded", g8b)

    def test_kickoff_asks_for_human_ideas_first(self):
        g0 = self.gate("G0")
        self.assertIn("your own ideas come first: type them now, one per line", g0)
        self.assertIn("reply `go`", g0)
        self.assertIn("no idea text is\nsent to any model before you reply", g0)
        self.assertIn("revealed after your choice", self.gate("G11"))
        self.assertIn("asked even in full-auto", self.gate("GX"))
        self.assertIn("INCONCLUSIVE never counts as a pass", self.gate("G9"))
        self.assertIn("without your yes (the ADRs go with the architecture and proposal", self.gate("G14"))

    def test_engine_gate_display_when_available(self):
        """With the engine present, the display function fills every name (no '(n/a)')."""
        try:
            from ublib.engine import gates as eg  # noqa: F401
        except Exception:
            self.skipTest("ublib.engine.gates not available")
        src = read(eg.__file__)
        for name in load_manifest()["gate_context"]:
            self.assertIn('"%s"' % name, src, name)


class Docs(unittest.TestCase):
    def doc(self, name):
        return read(os.path.join(TPL, "docs", name + ".md"))

    def test_seeds_renders_to_v1_template(self):
        self.assertEqual(render(self.doc("SEEDS"), {}), V1_SEEDS)

    def test_run_view_keeps_v1_lines(self):
        out = render(self.doc("RUN"), {"SLUG": "night-tutor", "MODE": "standard", "VARIANT": "product",
                                       "TOPIC": "t", "AUTOPILOT": "guided", "HOST_FAMILY": "claude",
                                       "HOST_AGENT": "claude-code", "OTHER_FAMILIES": "gpt via codex-cli",
                                       "PRIVACY_A": "yes", "PRIVACY_B": "no", "PYTHON": "py -3",
                                       "DETECTED_TOOLS": "none", "STRATEGY_MAP": "S1=claude S2=claude S3=gpt",
                                       "S1_SEEN": "n/a", "STAGE_LOG": "  - 2026-09-23T09:00:00Z 0.1 done init"})
        lines = out.split("\n")
        self.assertEqual(lines[0], "# Run: night-tutor")
        for prefix in ("- mode: standard", "- variant: product", "- topic: t", "- autopilot: guided",
                       "- host family: claude (claude-code)", "- other family: gpt via codex-cli",
                       "- privacy: (a) web + other vendors: yes   (b) code facts / repo files to other vendors: no",
                       "- python: py -3", "- detected tools: none",
                       "- strategy -> family map: S1=claude S2=claude S3=gpt", "- human saw S1 ranking: n/a",
                       "- session plan:", "- stage log:"):
            self.assertTrue(any(ln.startswith(prefix) for ln in lines), prefix)

    def test_adr_is_madr_minimal(self):
        out = render(self.doc("ADR-MADR"), {"ADR_STATUS": "proposed", "DATE": "2026-09-23"})
        self.assertTrue(out.startswith("---\nstatus: proposed\ndate: 2026-09-23\n"))
        for h in ("## Context and Problem Statement", "## Decision Drivers", "## Considered Options",
                  "## Decision Outcome", "### Consequences", "### Confirmation", "## More Information"):
            self.assertIn("\n" + h + "\n", out)
        self.assertIn('Chosen option: "', out)

    def test_arch_docs_headings(self):
        g = self.doc("GOALS-CONSTRAINTS")
        for h in ("# Goals and constraints", "## Product goal", "## Quality goals", "## Hard constraints",
                  "## Soft constraints", "## Not in scope", "## Planning assumptions", "## Open questions"):
            self.assertIn(h + "\n", g)
        self.assertIn("## Utility tree", self.doc("QUALITY-SCENARIOS"))
        ctx = self.doc("CONTEXT-VIEW")
        self.assertLess(ctx.index("{{C4_CONTEXT}}"), ctx.index("{{CONTEXT_FLOWCHART}}"))
        risks = self.doc("RISKS")
        self.assertIn("## Risks\n", risks)
        self.assertIn("## Technical debt\n", risks)
        self.assertIn("Rescued: {{RESCUED}}", self.doc("SHORTLIST"))
        self.assertIn("## Parked (K4 candidate)", self.doc("SHORTLIST"))
        self.assertIn("Novelty NOT checked - run Stage 7 before investing.", self.doc("QUICK-DECISION"))

    def test_proposal_appendices(self):
        text = self.doc("PROPOSAL-APPENDICES")
        heads = re.findall(r"^## (Appendix [A-F]\. [A-Za-z ]+)$", text, re.M)
        self.assertEqual(heads, ["Appendix A. ADR Index", "Appendix B. Assumptions Index",
                                 "Appendix C. Candidate Comparison", "Appendix D. Idea Selection Record",
                                 "Appendix E. Glossary", "Appendix F. Sources"])

    def test_index_html_shell(self):
        html = read(os.path.join(TPL, "docs", "index.html.tpl"))
        for needle in ("{{MERMAID_CDN}}", "pre.mermaid", "prefers-color-scheme: dark", "@media print",
                       "nav.toc { display: none; }", "break-before: page", 'id="toc"', "{{TOC}}", "{{BODY}}",
                       "{{ONE_PAGER}}", "{{BADGE}}", "position: sticky", 'id="one-pager"', "catch (e)"):
            self.assertIn(needle, html)
        self.assertNotIn("<link", html)  # inline CSS only; only the mermaid module loads remotely
        self.assertLess(html.index("{{ONE_PAGER}}"), html.index("{{BODY}}"))

    def test_engine_filled_docs_use_only_their_mapping(self):
        m = load_manifest()
        files = template_files()
        for name, mapping in m["doc_mappings"].items():
            text = read(files[("docs", name)])
            self.assertEqual(sorted(set(PH_RX.findall(text)) - set(mapping)), [], name)
            filled = render(text, dict((k, "x") for k in mapping))
            self.assertNotIn("{{", filled, name)
        self.assertEqual(PH_RX.findall(self.doc("DECISION")), ["DECISION_BODY"])
        self.assertEqual(PH_RX.findall(self.doc("HANDOFF")), ["HANDOFF_BODY"])

    def test_engine_fill_doc_accepts_them_when_available(self):
        try:
            from ublib.engine import builders
        except Exception:
            self.skipTest("ublib.engine.builders not available")
        fill_doc = getattr(builders, "fill_doc", None)
        if fill_doc is None:
            self.skipTest("builders exposes no fill_doc")
        files = template_files()
        for name, mapping in load_manifest()["doc_mappings"].items():
            out = fill_doc(read(files[("docs", name)]), dict((k, "v") for k in mapping))
            self.assertIsNotNone(out, name)
            self.assertNotIn("{{", out, name)


class Schemas(unittest.TestCase):
    def load(self, name):
        with open(os.path.join(TPL, "schemas", name + ".schema.json"), encoding="utf-8") as f:
            return json.load(f)

    def walk(self, node, path, root=False):
        allowed = SCHEMA_KEYWORDS | ({"$id"} if root else set())
        self.assertTrue(set(node) <= allowed, "%s: keywords %s" % (path, sorted(set(node) - allowed)))
        if node.get("type") == "object":
            self.assertIs(node.get("additionalProperties"), False, path)
            self.assertEqual(sorted(node.get("required", [])), sorted(node.get("properties", {})), path)
            self.assertTrue(node.get("properties"), path)
            for k, v in node["properties"].items():
                self.walk(v, path + "." + k)
        elif node.get("type") == "array":
            self.walk(node["items"], path + "[]")
        else:
            self.assertIn(node.get("type"), ("string", "number", "integer", "boolean"), path)

    def test_structured_output_subset(self):
        for name in SPEC_SCHEMAS:
            s = self.load(name)
            self.assertEqual(s["$id"], name)
            self.assertEqual(s["type"], "object")
            self.walk(s, name, root=True)
            self.assertEqual(schema_lite.validate(instance(s), s), [], name)

    def test_spec_fields(self):
        d = self.load("arch-drivers")["properties"]
        self.assertEqual(list(d), ["product_goal", "quality_goals", "hard_constraints", "soft_constraints",
                                   "not_in_scope", "qas", "context", "planning_assumptions", "open_questions"])
        self.assertEqual(d["quality_goals"]["items"]["properties"]["source"]["enum"], ["STATED", "ASSUMPTION"])
        rub = self.load("rubric")["properties"]
        self.assertEqual(sorted(rub["scores"]["properties"]),
                         sorted(["decision_readiness", "substance_over_theater", "strategic_coherence",
                                 "doneness_clarity", "scope_honesty", "downstream_usability", "shape_fit"]))
        self.assertEqual(self.load("stack-verify")["properties"]["rows"]["items"]["properties"]["status"]["enum"],
                         ["VERIFIED", "UNVERIFIED", "NOT SEARCHED"])
        self.assertEqual(self.load("findings")["properties"]["findings"]["items"]["properties"]["severity"]["enum"],
                         ["P0", "P1", "P2", "P3"])
        merges = self.load("merges")["properties"]
        self.assertEqual(sorted(merges), ["axes", "ideas", "notes"])
        self.assertEqual(sorted(merges["notes"]["properties"]), ["leak_check", "merge_log", "rerun"])
        judge = self.load("arch-judge")["properties"]["candidates"]["items"]["properties"]
        self.assertEqual(sorted(judge), sorted(["label", "veto", "veto_reason", "scores", "sensitivity_points",
                                                "tradeoff_points", "risks", "non_risks"]))


class Contracts(unittest.TestCase):
    """Each manifest contract is coherent with its template and accepts a well-formed synthetic output."""

    def setUp(self):
        self.m = load_manifest()
        self.run = tempfile.mkdtemp(prefix="ub-tpl-")

    def tearDown(self):
        shutil.rmtree(self.run, ignore_errors=True)

    def tpl(self, name):
        return read(os.path.join(TPL, "prompts", name + ".md"))

    def synth_files(self, c):
        per = c.get("per_file") or {}
        parts = []
        for rel in c.get("required") or []:
            if rel == "decisions.json":  # a register: validated against its kit schema (validate.REGISTER_SCHEMAS)
                with open(os.path.join(TPL, "schemas", "arch-decisions.schema.json"), encoding="utf-8") as f:
                    body = json.dumps(instance(json.load(f)))
            elif rel.endswith(".json"):
                body = '{"Value": 60, "Feasibility": 40}'
            else:
                rules = per.get(rel, {})
                chunks = ["# Doc"]
                for h in rules.get("headings", []):
                    chunks.append("%s stub title\nSome text." % h if not h.endswith(":") else "%s stub" % h)
                for mt in rules.get("mermaid", []):
                    chunks.append("```mermaid\n%s\n  A[One] --> B[Two]\n```" % mt)
                body = "\n\n".join(chunks)
            parts.append("=== FILE: %s ===\n%s\n=== END FILE ===" % (rel, body))
        if c.get("status_trailer"):
            parts.append('=== STATUS ===\n{"status":"complete","assumptions":[],"open_questions":[],"reason":""}\n'
                         "=== END STATUS ===")
        return "\n".join(parts) + "\n"

    def synth(self, name, info):
        c = dict(info["contract"])
        t = c["type"]
        if t == "text":
            samples = {"PING": "PONG", "GAP": "TENSION: the cell mixes two exclusive audiences",
                       "PRECOMMIT": "I-001: BACK - clear pain", "REBUTTAL": "Item 1: HOLD - the check cites data"}
            return c, samples[name]
        if t == "idea-blocks":
            prefix = c["prefix"].replace("{{STRATEGY_ID}}", "S3")
            c["prefix"] = prefix
            blocks = ["### %s-%02d Idea %d\n- Pitch: p\n- Mechanism: m\n- Fails if: f" % (prefix, i, i)
                      for i in range(1, c["min"] + 1)]
            return c, "\n\n".join(blocks)
        if t == "json":
            if not c["schema"].startswith("SK:"):
                return None, None  # run-relative schema written by bs.py schemas
            with open(os.path.join(_SK, c["schema"][3:]), encoding="utf-8") as f:
                obj = instance(json.load(f))
            if c.get("cover"):
                c["cover"] = dict(c["cover"], ids=["stub"])
            return c, json.dumps(obj)
        if t == "sections":
            parts = ["%s\nText." % h for h in c["headings"]]
            if c.get("json_tail"):
                with open(os.path.join(_SK, c["json_tail"][3:]), encoding="utf-8") as f:
                    parts.append("```json\n%s\n```" % json.dumps(instance(json.load(f))))
            if c.get("final_line"):
                parts.append(info["final_example"])
            return c, "\n\n".join(parts)
        if t == "cards":
            c["ids"] = ["I-001", "I-002"]
            cards = ["## %s\n%s" % (cid, "\n".join("%s value" % p for p in c["lines"])) for cid in c["ids"]]
            return c, "\n\n".join(cards)
        if t == "files":
            return c, self.synth_files(c)
        self.fail("unknown contract type %s" % t)

    def test_synthetic_outputs_validate(self):
        checked = 0
        for name, info in self.m["prompts"].items():
            if info["contract"] is None:
                self.assertEqual(name, "GEN-HEADER")
                continue
            c, text = self.synth(name, info)
            if c is None:
                continue
            ok, errors, _ = check_contract(text, c, self.run)
            self.assertTrue(ok, "%s: %s" % (name, errors))
            checked += 1
        self.assertGreaterEqual(checked, 45)

    def test_contract_headings_and_files_are_named_in_templates(self):
        for name, info in self.m["prompts"].items():
            c = info["contract"] or {}
            text = self.tpl(name)
            for h in c.get("headings", []):
                self.assertIn(h, text, "%s: heading %s not in template" % (name, h))
            if c.get("final_line"):
                ex = info["final_example"]
                self.assertRegex(ex, c["final_line"])
                self.assertIn(ex.split(":")[0] + ":", text, name)
            if c.get("type") == "files":
                self.assertIn("{{ALLOWED_FILES}}", text, name)
                self.assertIn("split_root", info, name)
                for rel in c.get("required", []):
                    self.assertIn(rel.split("/")[-1], text, "%s: %s not named" % (name, rel))
                for rel, rules in (c.get("per_file") or {}).items():
                    for h in rules.get("headings", []):
                        self.assertIn(h, text, "%s: %s heading %s" % (name, rel, h))
                    for mt in rules.get("mermaid", []):
                        self.assertIn(mt, text, "%s: %s mermaid %s" % (name, rel, mt))
                if c.get("status_trailer"):
                    self.assertIn("=== STATUS ===", text, name)
            if c.get("type") == "json" and c["schema"].startswith("SK:"):
                self.assertTrue(os.path.isfile(os.path.join(_SK, c["schema"][3:])), name)

    def test_frame_headings_everywhere(self):
        for name in ("FRAME-FINAL", "FRAME-DRAFT"):
            text = self.tpl(name)
            for h in self.m["frame_headings"]:
                self.assertIn(h, text, name)
        self.assertIn("## Domain language", self.tpl("FRAME-FINAL"))

    def test_final_line_regexes_match_spec(self):
        p = self.m["prompts"]
        self.assertEqual(p["CHECK"]["contract"]["final_line"],
                         r"^VERDICT: (CROWDED|ADJACENT|NOT LOCATED|NOT CHECKED); DIFFERENTIATOR: .+$")
        self.assertEqual(p["REVIEWER"]["contract"]["final_line"],
                         r"^VERDICT: (BACK IF .+|BACK|DON'T BACK)(; confidence (0(\.\d+)?|1(\.0+)?))?$")
        self.assertEqual(p["PROBE"]["contract"]["final_line"], r"^RESULT: PENDING$")
        self.assertTrue(p["SYNTHESIS"]["contract"]["final_line"].startswith("^WHOLE-EFFORT: (CONTINUE|STOP)"))
        self.assertEqual(p["ARCH-CANDIDATE"]["contract"]["headings"][0], "## 1 Paradigm")
        self.assertEqual(len(p["ARCH-CANDIDATE"]["contract"]["headings"]), 12)


class SkillMd(unittest.TestCase):
    def setUp(self):
        self.text = read(os.path.join(_SK, "SKILL.md"))

    def frontmatter(self):
        self.assertTrue(self.text.startswith("---\n"))
        end = self.text.index("\n---\n", 4)
        fm = {}
        cur = None
        for ln in self.text[4:end].split("\n"):
            if not ln.strip():
                continue
            if ln.startswith("  ") and cur:
                k, _, v = ln.strip().partition(":")
                fm[cur][k.strip()] = v.strip().strip('"')
                continue
            k, _, v = ln.partition(":")
            k, v = k.strip(), v.strip()
            if v:
                fm[k] = v.strip('"')
                cur = None
            else:
                fm[k], cur = {}, k
        return fm

    def test_size_and_frontmatter(self):
        self.assertLessEqual(len(self.text.encode("utf-8")), 12 * 1024)
        fm = self.frontmatter()
        self.assertTrue(set(fm) <= {"name", "description", "license", "compatibility", "metadata", "allowed-tools"})
        self.assertEqual(fm["name"], "ultimate-brainstorm")
        self.assertEqual(fm["name"], os.path.basename(_SK))
        self.assertLessEqual(len(fm["description"]), 1024)
        self.assertLessEqual(len(fm["compatibility"]), 500)
        self.assertEqual(fm["license"], "MIT")
        with open(os.path.join(_KIT, "VERSION"), encoding="utf-8") as f:
            self.assertEqual(fm["metadata"]["version"], f.read().strip())

    def test_driver_content(self):
        for needle in ("${CLAUDE_SKILL_DIR}", "${KIMI_SKILL_DIR}", "## Setup", "## Commands", "## The loop",
                       "## Hosts", "## Hard rules", '"answer_template"', '"answer_cmd"', '"task.done_cmd"',
                       "KIT/templates/host/HOST-BATCH.md", "| Claude Code | /ultimate-brainstorm | 540 |",
                       "| Codex | $ultimate-brainstorm | 100 |", "| Kimi Code | /skill:ultimate-brainstorm | 270 |",
                       "| ZCode, other | $ultimate-brainstorm | 50 |", "never a fork",
                       "brainstorm/.kickoff.txt", "--text-file"):
            self.assertIn(needle, self.text)
        # HOST-BATCH.md is the one source of the sub-agent task text (SKILL.md only points to it)
        self.assertNotIn("Read <prompt_file> and follow it", self.text)
        # the Start line writes the kickoff file, and hard rule 7 allows exactly that one write outside the run folder
        self.assertIn("to the file brainstorm/.kickoff.txt", self.text)
        self.assertIn("UB init --host HOST --text-file brainstorm/.kickoff.txt", self.text)
        rule7 = re.search(r"^7\. (.+?)(?=^\d+\. )", self.text, re.M | re.S).group(1)
        self.assertIn("(and brainstorm/.kickoff.txt for the Start command)", " ".join(rule7.split()))
        rules = re.findall(r"^(\d+)\. ", self.text[self.text.index("## Hard rules"):], re.M)
        self.assertGreaterEqual(len(rules), 11)
        for phrase in ("Human first", "Framing asks questions", "Never paste pool/", "Never call anything \"novel\"",
                       "The human decides", "Never commit", "never switch model families yourself",
                       "Privacy answers are binding", "never in a", "follow only that file"):
            self.assertIn(phrase, self.text)


if __name__ == "__main__":
    unittest.main()
