"""B3 engine: evidence and privacy guards (KIT_SPEC 6.7, 6.8): seed-leak and pool-leak detection, origin-label
refusal, code stripping for other vendors, the job.privacy stamp and the BLOCKED card naming the rule."""

import os
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "fixtures", "engine"))
import engine_testlib as tl  # noqa: E402

from ublib.engine import builders, pipeline, registry  # noqa: E402
from ublib.engine import privacy as pv  # noqa: E402

SEEDS = """# Human seeds

## Problem
Night nurses cannot swap shifts easily.

## Primary idea (to pressure-test)
- A shared points ledger for swapping night shifts

## Ideas
- Nurses trade shifts through a points ledger that the ward can see
- short one

## Obvious
- A marketplace app for shifts between hospitals

## Off-limits
- Anything touching payroll systems directly
"""


class SeedLeakTests(tl.EngineTestCase):
    def setUp(self):
        tl.EngineTestCase.setUp(self)
        self.ctx = self.make_ctx()
        self.ctx.write("00_HUMAN_SEEDS.md", SEEDS)

    def test_seed_lines(self):
        lines = pv.seed_lines(self.ctx.run_dir)
        self.assertIn("Nurses trade shifts through a points ledger that the ward can see", lines)
        self.assertIn("A shared points ledger for swapping night shifts", lines)
        self.assertIn("A marketplace app for shifts between hospitals", lines)
        self.assertNotIn("short one", lines)  # under 20 characters
        self.assertFalse(any("payroll" in x for x in lines))  # Off-limits is not sealed
        self.assertFalse(any("swap shifts easily" in x for x in lines))  # nor is the Problem

    def test_leak_is_refused_with_the_rule_name(self):
        prompt = "BRIEF\nsomething\n  nurses trade shifts   through a points ledger that the ward can see\n"
        with self.assertRaises(pv.PolicyBlock) as cm:
            pv.check_seed_leak(prompt, self.ctx.run_dir, "4.2-S3")
        self.assertEqual(cm.exception.rule, "seed_leak_check")
        pv.check_seed_leak("nothing sealed here", self.ctx.run_dir, "x")

    def test_topic_and_proposal_idea_are_allowed(self):
        prompt = "Topic: A shared points ledger for swapping night shifts"
        pv.check_seed_leak(prompt, self.ctx.run_dir, "x", allow=["A shared points ledger for swapping night shifts"])
        with self.assertRaises(pv.PolicyBlock):
            pv.check_seed_leak(prompt, self.ctx.run_dir, "x")

    def test_dispatch_returns_a_blocked_card_naming_the_rule(self):
        ctx = self.ctx
        # the frame (hence the generator BRIEF) carries a sealed seed line
        ctx.write("01_FRAME.md", "# FRAME: x\n## Job statement\nx\n## Problem\nNurses trade shifts through a points "
                                 "ledger that the ward can see\n## Axes\n- A: a | b\n")
        steps = [{"id": "4.2", "stage": 4, "title": "Diverge", "type": "DISPATCH", "fanout": "strategies",
                  "job": {"kind": "generator"}, "min_ok": "3/5"}]
        card = pipeline.advance(ctx, steps, 0)
        self.assertEqual(card["type"], "BLOCKED")
        self.assertIn("seed_leak_check", card["say"])
        self.assertEqual(ctx.deps.batch.launched, [])

    def test_the_curator_may_see_seeds(self):
        ctx = self.ctx
        ctx.write("pool/S2_vs.md", "### S2-01 Some idea title here\n- Pitch: p\n- Mechanism: m\n- Fails if: f\n")
        items = registry.FANOUTS["curator"](ctx, {"id": "5.1"})
        job = builders.make_job(ctx, {"id": "5.1"}, items[0], write=False)
        prompt = ctx.read(job["prompt_file"]) if ctx.exists(job["prompt_file"]) else builders.fill(
            ctx, builders.template_text("CURATOR"), {"template": "CURATOR", "family": "claude",
                                                      "contract": items[0]["contract"]})
        self.assertIn("points ledger", prompt)


class PoolLeakTests(tl.EngineTestCase):
    def test_pool_title_in_generator_prompt_is_refused(self):
        ctx = self.make_ctx()
        ctx.write("pool/S3_enumerate.md", "### S3-01 Rota aware reminder that follows shifts\n- Pitch: p\n")
        with self.assertRaises(pv.PolicyBlock) as cm:
            pv.check_pool_leak("please use: Rota aware reminder that follows shifts", ctx.run_dir, "5.3-G1")
        self.assertEqual(cm.exception.rule, "pool_leak_check")
        pv.check_pool_leak("unrelated text", ctx.run_dir)


class OriginLabelTests(unittest.TestCase):
    def test_alias_ids_and_origin_words_refused(self):
        for bad in ("compare S3-04 with I-002", "HP-01 is strong", "origin: human", "Strategy: S2",
                    "this was generated by GPT", "IMP-03", "S1R-02", "L4-11", "QB-03 is sharper", "QA-12"):
            with self.assertRaises(pv.PolicyBlock, msg=bad) as cm:
                pv.check_origin_labels(bad, "6.2-claude")
            self.assertEqual(cm.exception.rule, "origin_label_check")

    def test_neutral_prompt_passes(self):
        pv.check_origin_labels("## I-001\nTitle: x\nPrior art: ADJACENT\nQAS-01 C-1 EXT-2 R-001 HC-1", "x")

    def test_run_checks_dispatches_by_name(self):
        with self.assertRaises(pv.PolicyBlock):
            pv.run_checks("G2-01", ["origin_label"], ".", "x")


CODE_FACTS = """## A. FACTS
- src/app.py handles shift swaps (src/app.py:10)
```python
def swap(a, b):
    return b, a
```
    indented_code = 1
- more facts

## A2. DOMAIN TERMS (today's system)
- **Shift**: a work period.
- **Swap** [proposed]: an exchange of two shifts.
"""


class CodeStripTests(tl.EngineTestCase):
    def test_strip_code_keeps_paths(self):
        out = pv.strip_code(CODE_FACTS)
        self.assertIn("src/app.py handles shift swaps (src/app.py:10)", out)
        self.assertNotIn("def swap", out)
        self.assertNotIn("indented_code", out)
        self.assertIn("[code omitted: privacy code = no]", out)

    def test_filter_facts_for_other_vendor(self):
        ctx = self.make_ctx(variant="software")
        self.assertTrue(pv.needs_code_strip(ctx.state, "gpt"))
        self.assertFalse(pv.needs_code_strip(ctx.state, "claude"))
        out = pv.filter_facts(CODE_FACTS, ctx.state, "gpt")
        self.assertNotIn("def swap", out)
        self.assertNotIn("**Shift**", out)
        self.assertIn("**Swap** [proposed]", out)
        self.assertEqual(pv.filter_facts(CODE_FACTS, ctx.state, "claude"), CODE_FACTS)
        ctx.state["privacy"]["code"] = True
        self.assertFalse(pv.needs_code_strip(ctx.state, "gpt"))

    def test_facts_placeholder_is_filtered_per_family(self):
        ctx = self.make_ctx(variant="software")
        ctx.write("02_CONTEXT.md", CODE_FACTS + "\n## B. LANDSCAPE\n- x\n## C. SEARCH BOUNDARY\n- y\n")
        gpt = registry.PLACEHOLDERS["FACTS"](ctx, {"family": "gpt"})
        claude = registry.PLACEHOLDERS["FACTS"](ctx, {"family": "claude"})
        self.assertNotIn("def swap", gpt)
        self.assertIn("def swap", claude)

    def test_repo_cwd_is_never_used_for_other_vendors(self):
        ctx = self.make_ctx(variant="software")
        spec = {"id": "x", "template": "PING", "family": "gpt", "tools": "read+web", "cwd": "repo",
                "repo_root": self.project, "out": "logs/x.txt", "contract": {"type": "text"}}
        job = builders.make_job(ctx, {"id": "3.1"}, spec, write=False)
        self.assertEqual(job["cwd"], "empty")
        self.assertIsNone(job["repo_root"])
        self.assertEqual(job["tools"], "web")
        self.assertTrue(job["privacy"]["code_ok"])
        spec["family"] = "claude"
        job = builders.make_job(ctx, {"id": "3.1"}, spec, write=False)
        self.assertEqual(job["cwd"], "repo")


class JobStampTests(tl.EngineTestCase):
    def test_privacy_stamp(self):
        ctx = self.make_ctx(privacy={"web": False})
        stamp = pv.job_privacy(ctx.state, "gpt", "web", "empty")
        self.assertFalse(stamp["web_ok"])
        self.assertTrue(stamp["vendor_ok"])
        ctx.state["privacy"]["allowed_vendors"] = ["anthropic"]
        self.assertFalse(pv.job_privacy(ctx.state, "gpt", "none", "empty")["vendor_ok"])
        self.assertFalse(pv.job_privacy(ctx.state, "gpt", "none", "repo")["code_ok"])

    def test_web_tools_removed_when_privacy_says_no(self):
        ctx = self.make_ctx(privacy={"web": False})
        spec = {"id": "x", "template": "PING", "family": "claude", "tools": "read+web", "out": "logs/x.txt",
                "contract": {"type": "text"}}
        job = builders.make_job(ctx, {"id": "3.1"}, spec, write=False)
        self.assertEqual(job["tools"], "read")
        self.assertIn("NOT allowed", registry.PLACEHOLDERS["PRIVACY_NOTE"](ctx, {"template": "CHECK",
                                                                                  "tools": "none"}))


if __name__ == "__main__":
    unittest.main()
